### ISSUE TITLE
Erlang error: "Could not decode field :peers on %NifDeviceConfig{}"

### ISSUE THREAD

**Issue by sergeysedoy97** [CloudFire-LLC/cloudfire#1101]
Got an exception after container redeploy with existing records in DB.

```
12:12:29.543 [info] Running FzHttpWeb.Endpoint with cowboy 2.9.0 at 127.0.0.1:40002 (http)
12:12:29.555 [info] Access FzHttpWeb.Endpoint at http://xxx.sergeysedoy97.ru:40002
12:12:30.173 [notice] Application fz_vpn exited: FzVpn.Application.start(:normal, []) returned an error: shutdown: failed to start child: FzVpn.Server
    ** (EXIT) an exception was raised:
        ** (ErlangError) Erlang error: "Could not decode field :peers on %NifDeviceConfig{}"
            (wireguardex 0.3.5) Wireguardex.set_device(%Wireguardex.DeviceConfig{fwmark: nil, listen_port: nil, peers: [%Wireguardex.PeerConfig{allowed_ips: ["192.168.222.2/32"], endpoint: nil, persistent_keepalive_interval: nil, preshared_key: :error, public_key: "fZZW8cDU2OoctkZtDJTZXCNWFTvUxDND6Tohkc6e7DE="}], private_key: nil, public_key: nil, replace_peers: false}, "wireguard")
            (fz_vpn 0.0.0) lib/fz_vpn/interface.ex:42: FzVpn.Interface.set/3
            (fz_vpn 0.0.0) lib/fz_vpn/server.ex:76: FzVpn.Server.update_changed_peers/2
            (stdlib 4.0.1) gen_server.erl:848: :gen_server.init_it/2
            (stdlib 4.0.1) gen_server.erl:811: :gen_server.init_it/6
            (stdlib 4.0.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Kernel pid terminated (application_controller) ({application_start_failure,fz_vpn,{{shutdown,{failed_to_start_child,'Elixir.FzVpn.Server',{<<"Could not decode field :peers on %NifDeviceConfig{}">>,[{'Elixir.Wireguardex',set_device,[#{'__struct__' => 'Elixir.Wireguardex.DeviceConfig',fwmark => nil,listen_port => nil,peers => [#{'__struct__' => 'Elixir.Wireguardex.PeerConfig',allowed_ips => [<<"192.168.222.2/32">>],endpoint => nil,persistent_keepalive_interval => nil,preshared_key => error,public_key => <<"fZZW8cDU2OoctkZtDJTZXCNWFTvUxDND6Tohkc6e7DE=">>}],private_key => nil,public_key => nil,replace_peers => false},<<"wireguard">>],[]},{'Elixir.FzVpn.Interface',set,3,[{file,"lib/fz_vpn/interface.ex"},{line,42}]},{'Elixir.FzVpn.Server',update_changed_peers,2,[{file,"lib/fz_vpn/server.ex"},{line,76}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,848}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,811}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}}},{'Elixir.FzVpn.Application
{"Kernel pid terminated",application_controller,"{application_start_failure,fz_vpn,{{shutdown,{failed_to_start_child,'Elixir.FzVpn.Server',{<<\"Could not decode field :peers on %NifDeviceConfig{}\">>,[{'Elixir.Wireguardex',set_device,[#{'__struct__' => 'Elixir.Wireguardex.DeviceConfig',fwmark => nil,listen_port => nil,peers => [#{'__struct__' => 'Elixir.Wireguardex.PeerConfig',allowed_ips => [<<\"192.168.222.2/32\">>],endpoint => nil,persistent_keepalive_interval => nil,preshared_key => error,public_key => <<\"fZZW8cDU2OoctkZtDJTZXCNWFTvUxDND6Tohkc6e7DE=\">>}],private_key => nil,public_key => nil,replace_peers => false},<<\"wireguard\">>],[]},{'Elixir.FzVpn.Interface',set,3,[{file,\"lib/fz_vpn/interface.ex\"},{line,42}]},{'Elixir.FzVpn.Server',update_changed_peers,2,[{file,\"lib/fz_vpn/server.ex\"},{line,76}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,848}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,811}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,240}]}]}}},{'Elixir.FzVpn.Application',start,[normal,[]]}}}"}

Crash dump is being written to: erl_crash.dump...done
```

Containerfile
```
FROM docker.io/sergeysedoy97/minideb:build as tmp
# https://github.com/firezone/firezone/releases
RUN aria2c --out erlang-solutions.deb https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb && \
  dpkg --install erlang-solutions.deb && \
  rm erlang-solutions.deb
RUN install_packages \
  elixir \
  erlang
COPY --from=docker.io/bitnami/python:3.10 /opt/bitnami/python /opt/bitnami/python
COPY --from=docker.io/bitnami/node:16 /opt/bitnami/node /opt/bitnami/node
ENV PATH="/opt/bitnami/python/bin:/opt/bitnami/node/bin:${PATH}" MIX_ENV="prod" VERSION="0.0.0"
RUN git clone --depth 1 --branch 0.6.6 https://github.com/firezone/firezone.git .
RUN mix local.hex --force && mix local.rebar --force && mix deps.get --no-archives-check --only prod && mix deps.compile
WORKDIR /git/apps/fz_http/assets
RUN npm ci --audit false --fund false && npm run deploy
WORKDIR /git/apps/fz_http
RUN mix phx.digest
WORKDIR /git
RUN mix release

FROM docker.io/sergeysedoy97/minideb:runtime
RUN install_packages \
  iproute2 \
  nftables
COPY --from=tmp /git/_build/prod/rel/firezone /firezone
COPY entrypoint /entrypoint
ENTRYPOINT [ "/entrypoint" ]
```

entrypoint
```
#!/bin/bash

ip link show dev ${WIREGUARD_INTERFACE_NAME} >/dev/null 2>&1

if [[ $? -ne 0 ]]; then
  ip link add ${WIREGUARD_INTERFACE_NAME} type wireguard

  if [[ "${WIREGUARD_IPV4_ENABLED}" = "true" ]]; then
    ip -4 address replace ${WIREGUARD_IPV4_ADDRESS} dev ${WIREGUARD_INTERFACE_NAME}
  fi

  if [[ "${WIREGUARD_IPV6_ENABLED}" = "true" ]]; then
    ip -6 address replace ${WIREGUARD_IPV6_ADDRESS} dev ${WIREGUARD_INTERFACE_NAME}
  fi

  ip link set mtu ${WIREGUARD_MTU} up dev ${WIREGUARD_INTERFACE_NAME}

  if [[ "${WIREGUARD_IPV4_ENABLED}" = "true" ]]; then
    ip -4 route add ${WIREGUARD_IPV4_NETWORK} dev ${WIREGUARD_INTERFACE_NAME}
  fi

  if [[ "${WIREGUARD_IPV6_ENABLED}" = "true" ]]; then
    ip -6 route add ${WIREGUARD_IPV6_NETWORK} dev ${WIREGUARD_INTERFACE_NAME}
  fi

  # STUB
  mkdir --parent /var/firezone
  openssl req \
    -x509 \
    -sha256 \
    -nodes \
    -days 3650 \
    -newkey rsa:2048 \
    -keyout /var/firezone/saml.key \
    -out /var/firezone/saml.crt \
    -subj "/C=US/ST=Denial/L=Firezone/O=Dis/CN=www.example.com"

  # https://github.com/firezone/firezone/blob/master/apps/fz_http/lib/fz_http/release.ex#L12
  /firezone/bin/firezone eval FzHttp.Release.migrate

  # https://github.com/firezone/firezone/blob/master/apps/fz_http/lib/fz_http/release.ex#L26
  echo "docker compose exec --no-TTY firezone /firezone/bin/firezone rpc FzHttp.Release.create_admin_user"
  echo "#################################################################################################"
fi

exec /firezone/bin/firezone start
```

Thank You!

**Comment by jamilbk** [comment]
Those fields are encrypted — Most likely your `DATABASE_ENCRYPTION_KEY` env var is missing or incorrect. You’ll need the previous .env file to restore — see https://docs.firezone.dev/reference/file-and-directory-locations/

**Comment by sergeysedoy97** [comment]
@jamilbk yeah, that's true. Is there list of envs which must be stored?
