### ISSUE TITLE
Crash on start after upgrade to v0.7.0

### ISSUE THREAD

**Issue by toreanderson** [CloudFire-LLC/cloudfire#1295]
After the `docker.io/firezone/firezone:latest` container image was upgraded to ID47d0fce412dd (presumably going from v0.6.16 to v0.7.0) , it crashes at start-up with the following error messages:

```
10:35:13.356 [info] == Running 20221223190406 FzHttp.Repo.Migrations.MigratePksToUuid.change/0 forward
10:35:13.363 [info] alter table connectivity_checks
** (Postgrex.Error) ERROR 23502 (not_null_violation) column "id" of relation "connectivity_checks" contains null values

    table: connectivity_checks
    column: id
    (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.14.2) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:1005: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.9.2) lib/ecto/migration/runner.ex:326: Ecto.Migration.Runner.log_and_execute_ddl/3
    (ecto_sql 3.9.2) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
    (elixir 1.14.2) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql 3.9.2) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
    nofile:1: (file)
sh: true: unknown operand
10:35:15.196 [info] Running FzHttpWeb.Endpoint with cowboy 2.9.0 at 0.0.0.0:13000 (http)
10:35:15.201 [info] Access FzHttpWeb.Endpoint at https://vpn.i.bitbit.net
10:35:15.304 [notice] Application fz_http exited: FzHttp.Application.start(:normal, []) returned an error: shutdown: failed to start child: FzHttp.OIDC.StartProxy
    ** (EXIT) an exception was raised:
        ** (Postgrex.Error) ERROR 42703 (undefined_column) column c0.default_client_persistent_keepalive does not exist

    query: SELECT c0."id", c0."allow_unprivileged_device_management", c0."allow_unprivileged_device_configuration", c0."local_auth_enabled", c0."disable_vpn_on_oidc_error", c0."default_client_persistent_keepalive", c0."default_client_mtu", c0."default_client_endpoint", c0."default_client_dns", c0."default_client_allowed_ips", c0."vpn_session_duration", c0."logo", c0."openid_connect_providers", c0."saml_identity_providers", c0."inserted_at", c0."updated_at" FROM "configurations" AS c0
            (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
            (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:828: Ecto.Adapters.SQL.execute/6
            (ecto 3.9.4) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
            (ecto 3.9.4) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
            (ecto 3.9.4) lib/ecto/repo/queryable.ex:159: Ecto.Repo.Queryable.one!/3
            (fz_http 0.7.0) lib/fz_http/configurations.ex:11: FzHttp.Configurations.get!/1
            (fz_http 0.7.0) lib/fz_http/oidc/start_proxy.ex:17: FzHttp.OIDC.StartProxy.start_link/1
            (stdlib 4.1.1) supervisor.erl:414: :supervisor.do_start_child_i/3
{"Kernel pid terminated",application_controller,"{application_start_failure,fz_http,{{shutdown,{failed_to_start_child,'Elixir.FzHttp.OIDC.StartProxy',{'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 6995,message => nil,postgres => #{code => undefined_column,file => <<\"parse_relation.c\">>,line => <<\"3651\">>,message => <<\"column c0.default_client_persistent_keepalive does not exist\">>,pg_code => <<\"42703\">>,position => <<\"163\">>,routine => <<\"errorMissingColumn\">>,severity => <<\"ERROR\">>,unknown => <<\"ERROR\">>},query => <<\"SELECT c0.\\"id\\", c0.\\"allow_unprivileged_device_management\\", c0.\\"allow_unprivileged_device_configuration\\", c0.\\"local_auth_enabled\\", c0.\\"disable_vpn_on_oidc_error\\", c0.\\"default_client_persistent_keepalive\\", c0.\\"default_client_mtu\\", c0.\\"default_client_endpoint\\", c0.\\"default_client_dns\\", c0.\\"default_client_allowed_ips\\", c0.\\"vpn_session_duration\\", c0.\\"logo\\", c0.\\"openid_connect_providers\\", c0.\\"saml_identity_providers\\", c0.\\"inserted_at\\", c0.\\"updated_at\\" FROM \\"configurations\\" AS c0\">>},[{'Elixir.Ecto.Adapters.SQL',raise_sql_call_error,1,[{file,\"lib/ecto/adapters/sql.ex\"},{line,913},{error_info,#{module => 'Elixir.Exception'}}]},{'Elixir.Ecto.Adapters.SQL',execute,6,[{file,\"lib/ecto/adapters/sql.ex\"},{line,828}]},{'Elixir.Ecto.Repo.Queryable',execute,4,[{file,\"lib/ecto/repo/queryable.ex\"},{line,229}]},{'Elixir.Ecto.Repo.Queryable',all,3,[{file,\"lib/ecto/repo/queryable.ex\"},{line,19}]},{'Elixir.Ecto.Repo.Queryable','one!',3,[{file,\"lib/ecto/repo/queryable.ex\"},{line,159}]},{'Elixir.FzHttp.Configurations','get!',1,[{file,\"lib/fz_http/configurations.ex\"},{line,11}]},{'Elixir.FzHttp.OIDC.StartProxy',start_link,1,[{file,\"lib/fz_http/oidc/start_proxy.ex\"},{line,17}]},{supervisor,do_start_child_i,3,[{file,\"supervisor.erl\"},{line,414}]}]}}}},{'Elixir.FzHttp.Application',start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,fz_http,{{shutdown,{failed_to_start_child,'Elixir.FzHttp.OIDC.StartProxy',{'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.Postgrex.Error',connection_id => 6995,message => nil,postgres => #{code => undefined_column,file => <<"parse_relation.c">>,line => <<"3651">>,message => <<"column c0.default_client_persistent_keepalive does not exist">>,pg_code => <<"42703">>,position => <<"163">>,routine => <<"errorMissingColumn">>,severity => <<"ERROR">>,unknown => <<"ERROR">>},query => <<"SELECT c0.\"id\", c0.\"allow_unprivileged_device_management\", c0.\"allow_unprivileged_device_configuration\", c0.\"local_auth_enabled\", c0.\"disable_vpn_on_oidc_error\", c0.\"default_client_persistent_keepalive\", c0.\"default_client_mtu\", c0.\"default_client_endpoint\", c0.\"default_client_dns\", c0.\"default_client_allowed_ips\", c0.\"vpn_session_duration\", c0.\"logo\", c0.\"openid_connect_providers\", c0.\"saml_identity_providers\", c0.\"inser

Crash dump is being written to: erl_crash.dump...done
```

**Comment by toreanderson** [comment]
After downgrading to `:0.6.16`, it works again. However now an error message occurs at each (re)start. I do not believe this was there before, so it would seem that the failed upgrade followed by the downgrade has left the database in some kind of inconsistent state. Fortunately, however, it seems that it is is not critical to operation.

```
Jan 13 11:46:56 systemd[1]: Started Podman container-84cbe9fd46b5754cc255804b3365fbfe17b74bf56e49a32fc2b46231d7545c74.service.
Jan 13 11:46:57 firezone[3408067]: 10:46:57.606 [info] == Running 20221224210654 FzHttp.Repo.Migrations.FixSitesNullableFields.change/0 forward
Jan 13 11:46:57 firezone[3408067]: ** (ArgumentError) construction of binary failed: segment 1 of type 'binary': expected a binary but got: nil
Jan 13 11:46:57 firezone[3408067]:     /app/lib/fz_http-0.6.16/priv/repo/migrations/20221224210654_fix_sites_nullable_fields.exs:14: FzHttp.Repo.Migrations.FixSitesNullableFields.change/0
Jan 13 11:46:57 firezone[3408067]:     (ecto_sql 3.9.2) lib/ecto/migration/runner.ex:288: Ecto.Migration.Runner.perform_operation/3
Jan 13 11:46:57 firezone[3408067]:     (stdlib 4.1.1) timer.erl:235: :timer.tc/1
Jan 13 11:46:57 firezone[3408067]:     (ecto_sql 3.9.2) lib/ecto/migration/runner.ex:25: Ecto.Migration.Runner.run/8
Jan 13 11:46:57 firezone[3408067]:     (ecto_sql 3.9.2) lib/ecto/migrator.ex:337: Ecto.Migrator.attempt/8
Jan 13 11:46:57 firezone[3408067]:     (ecto_sql 3.9.2) lib/ecto/migrator.ex:258: anonymous fn/5 in Ecto.Migrator.do_up/5
Jan 13 11:46:57 firezone[3408067]:     (ecto_sql 3.9.2) lib/ecto/migrator.ex:308: anonymous fn/6 in Ecto.Migrator.async_migrate_maybe_in_transaction/7
Jan 13 11:46:57 firezone[3408067]:     nofile:1: (file)
Jan 13 11:47:00 firezone[3408067]: 10:47:00.125 [info] Running FzHttpWeb.Endpoint with cowboy 2.9.0 at 0.0.0.0:13000 (http)
```

**Comment by elhijo** [comment]
I'm facing the exact same issue, except that once downgraded I dont have any error message.

**Comment by gbe0** [comment]
Similar issue, how I get an error for a different table:

```bash
---- Begin output of bin/firezone eval "FzHttp.Release.migrate" ----
STDOUT: 19:50:12.384 [info] == Running 20221223190406 FzHttp.Repo.Migrations.MigratePksToUuid.change/0 forward
19:50:12.395 [info] alter table connectivity_checks
19:50:12.405 [info] execute "DROP INDEX devices_uuid_index"
19:50:12.411 [info] rename column id to id_tmp on table devices
19:50:12.412 [info] rename column uuid to id on table devices
19:50:12.413 [info] alter table devices
19:50:12.418 [info] execute "DROP INDEX rules_uuid_index"
19:50:12.419 [info] rename column id to id_tmp on table rules
19:50:12.423 [info] rename column uuid to id on table rules
19:50:12.424 [info] alter table rules
19:50:12.429 [info] alter table oidc_connections
STDERR: ** (Postgrex.Error) ERROR 23502 (not_null_violation) column "id" of relation "oidc_connections" contains null values

    table: oidc_connections
    column: id
    (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.14.0) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:1005: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.9.2) lib/ecto/migration/runner.ex:326: Ecto.Migration.Runner.log_and_execute_ddl/3
    (ecto_sql 3.9.2) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
    (elixir 1.14.0) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql 3.9.2) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
    nofile:1: (file)
---- End output of bin/firezone eval "FzHttp.Release.migrate" ----
```

**Comment by jahlib** [comment]
anybody fix this already?

**Comment by AndrewDryga** [comment]
Hello 👋. The blame is on me - looks like our seed data did not cover the migration case you hit into, I'm sorry for the inconvenience and already working on a fix for this issue. 0.7.1 should be out shortly
