### ISSUE TITLE
0.7.3 problem with send email recover password

### ISSUE THREAD

**Issue by ihard** [CloudFire-LLC/cloudfire#1342]
My env for email:
```
OUTBOUND_EMAIL_FROM=admin@firezone.example.com
OUTBOUND_EMAIL_PROVIDER=smtp
OUTBOUND_EMAIL_CONFIGS={"smtp": { "relay": "smtp.gmail.com", "username": "username@gmail.com", "password": "secret", "port": 587 }}
```

On page https://firezone.example.com/auth/reset_password after Send email  get Internal Server Error

Nginx logs:
```
myip - - [19/Jan/2023:14:00:52 +0000] "GET /auth/reset_password HTTP/2.0" 200 345910 "https://firezone.example.com/auth/identity" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15" "-"
myip - - [19/Jan/2023:14:05:33 +0000] "POST /auth/magic_link HTTP/2.0" 500 21 "https://firezone.example.com/auth/reset_password" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15" "-"
```

FIrezone logs:
```
14:05:32.207 request_id=Fzu62g6KreqQjoAAAAQR [info] POST /auth/magic_link
14:05:33.457 request_id=Fzu62g6KreqQjoAAAAQR remote_ip=myip [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'
```

**Comment by jamilbk** [comment]
Thanks for the report! Unfortunately the Firezone container log you captured doesn't capture the backtrace. I was able to reproduce.

Will have a fix out in a bit.

cc @AndrewDryga

```
firezone-firezone-1  | Request: POST /auth/magic_link
firezone-firezone-1  | ** (exit) an exception was raised:
firezone-firezone-1  |     ** (Protocol.UndefinedError) protocol Swoosh.Email.Recipient not implemented for nil of type Atom, Swoosh.Email.Recipient needs to be implemented for nil
firezone-firezone-1  | 
firezone-firezone-1  | Default implementations of Recipient include
firezone-firezone-1  | * a string representing an email address like `foo.bar@example.com`
firezone-firezone-1  | * or a two-element tuple `{name, address}`, where name and address are strings.
firezone-firezone-1  |   - name is allowed to be nil in this case
firezone-firezone-1  | . This protocol is implemented for the following type(s): Any, BitString, Tuple
firezone-firezone-1  |         (swoosh 1.9.1) lib/swoosh/email/recipient.ex:77: Swoosh.Email.Recipient.Any.format/1
firezone-firezone-1  |         (swoosh 1.9.1) lib/swoosh/email.ex:210: Swoosh.Email.from/2
firezone-firezone-1  |         (fz_http 0.7.3) lib/fz_http_web/mailer/auth_email.ex:14: FzHttpWeb.Mailer.AuthEmail.magic_link/1
firezone-firezone-1  |         (fz_http 0.7.3) lib/fz_http_web/controllers/auth_controller.ex:129: FzHttpWeb.AuthController.magic_link/2
firezone-firezone-1  |         (fz_http 0.7.3) lib/fz_http_web/controllers/auth_controller.ex:1: FzHttpWeb.AuthController.action/2
firezone-firezone-1  |         (fz_http 0.7.3) lib/fz_http_web/controllers/auth_controller.ex:1: FzHttpWeb.AuthController.phoenix_controller_pipeline/2
firezone-firezone-1  |         (phoenix 1.7.0-rc.2) lib/phoenix/router.ex:425: Phoenix.Router.__call__/5
firezone-firezone-1  |         (fz_http 0.7.3) lib/fz_http_web/endpoint.ex:1: FzHttpWeb.Endpoint.plug_builder_call/2
```

**Comment by jamilbk** [comment]
Hi @ihard -- hmm, actually it looks like you're still running 0.7.2. Could you ensure you've pulled 0.7.3 and re-upped the container? I think this issue may be caused by that.

```
docker compose -f $HOME/.firezone/docker-compose.yml pull firezone/firezone
docker compose -f $HOME/.firezone/docker-compose.yml up -d
```

**Comment by jamilbk** [comment]
Hi @ihard -- it looks like one of your email config env vars isn't being read properly.

Could you run the following to confirm the values loaded in the `firezone` container:

```
docker compose -f $HOME/.firezone/.env exec -it firezone printenv | grep OUTBOUND
```

Note that you'll need to wrap OUTBOUND_EMAIL_CONFIGS value in single-quotes to be a valid JSON-encoded string, e.g.

```
OUTBOUND_EMAIL_CONFIGS='{"smtp": { "relay": "smtp.gmail.com", "username": "username@gmail.com", "password": "secret", "port": 587 }}'
```

**Comment by ihard** [comment]
My variables are exactly the same as i specified in the first post. 
If I put it in single quotes, it will cause an application error, it will not start with the next trace:

```
ERROR! Config provider Config.Reader failed with:
** (Jason.DecodeError) unexpected byte at position 0: 0x27 ("'")
    lib/jason.ex:92: Jason.decode!/2
    lib/fz_http/mailer.ex:29: FzHttpWeb.Mailer.configs_for/1
    /app/releases/0.7.3/runtime.exs:99: (file)
    (elixir 1.14.2) src/elixir.erl:309: anonymous fn/4 in :elixir.eval_external_handler/1
    (stdlib 4.1.1) erl_eval.erl:748: :erl_eval.do_apply/7
    (stdlib 4.1.1) erl_eval.erl:961: :erl_eval.expr_list/7
    (stdlib 4.1.1) erl_eval.erl:454: :erl_eval.expr/6
    (stdlib 4.1.1) erl_eval.erl:961: :erl_eval.expr_list/7

{"init terminating in do_boot",{#{'__exception__'=>true,'__struct__'=>'Elixir.Jason.DecodeError',data=><<"'{\"smtp\": { \"relay\": \"smtp.gmail.com\", \"username\": \"username@gmail.com\", \"password\": \"secret\", \"port\": 587 }}'">>,position=>0,token=>nil},[{'Elixir.Jason','decode!',2,[{file,"lib/jason.ex"},{line,92},{error_info,#{module=>'Elixir.Exception'}}]},{'Elixir.FzHttpWeb.Mailer',configs_for,1,[{file,"lib/fz_http/mailer.ex"},{line,29}]},{elixir_eval,'__FILE__',1,[{file,"/app/releases/0.7.3/runtime.exs"},{line,99}]},{elixir,'-eval_external_handler/1-fun-2-',4,[{file,"src/elixir.erl"},{line,309}]},{erl_eval,do_apply,7,[{file,"erl_eval.erl"},{line,748}]},{erl_eval,expr_list,7,[{file,"erl_eval.erl"},{line,961}]},{erl_eval,expr,6,[{file,"erl_eval.erl"},{line,454}]},{erl_eval,expr_list,7,[{file,"erl_eval.erl"},{line,961}]}]}}
init terminating in do_boot ({,[{Elixir.Jason,decode!,2,[{_},{_},{_}]},{Elixir.FzHttpWeb.Mailer,configs_for,1,[{_},{_}]},{elixir_eval,__FILE__,1,[{_},{_}]},{elixir,-eval_external_handler/1-fun-2-,4,[{_},{_}]},{erl_eval,do_apply,7,[{_},{_}]},{erl_eval,expr_list,7,[{_},{_}]},{erl_eval,expr,6,[{_},{_}]},{erl_eval,expr_list,7,[{_},{_}]}]})

Crash dump is being written to: erl_crash.dump...done
ERROR! Config provider Config.Reader failed with:
** (Jason.DecodeError) unexpected byte at position 0: 0x27 ("'")
    lib/jason.ex:92: Jason.decode!/2
    lib/fz_http/mailer.ex:29: FzHttpWeb.Mailer.configs_for/1
    /app/releases/0.7.3/runtime.exs:99: (file)
    (elixir 1.14.2) src/elixir.erl:309: anonymous fn/4 in :elixir.eval_external_handler/1
    (stdlib 4.1.1) erl_eval.erl:748: :erl_eval.do_apply/7
    (stdlib 4.1.1) erl_eval.erl:961: :erl_eval.expr_list/7
    (stdlib 4.1.1) erl_eval.erl:454: :erl_eval.expr/6
    (stdlib 4.1.1) erl_eval.erl:961: :erl_eval.expr_list/7

{"init terminating in do_boot",{#{'__exception__'=>true,'__struct__'=>'Elixir.Jason.DecodeError',data=><<"'{\"smtp\": { \"relay\": \"smtp.gmail.com\", \"username\": \"username@gmail.com\", \"password\": \"secret\", \"port\": 587 }}'">>,position=>0,token=>nil},[{'Elixir.Jason','decode!',2,[{file,"lib/jason.ex"},{line,92},{error_info,#{module=>'Elixir.Exception'}}]},{'Elixir.FzHttpWeb.Mailer',configs_for,1,[{file,"lib/fz_http/mailer.ex"},{line,29}]},{elixir_eval,'__FILE__',1,[{file,"/app/releases/0.7.3/runtime.exs"},{line,99}]},{elixir,'-eval_external_handler/1-fun-2-',4,[{file,"src/elixir.erl"},{line,309}]},{erl_eval,do_apply,7,[{file,"erl_eval.erl"},{line,748}]},{erl_eval,expr_list,7,[{file,"erl_eval.erl"},{line,961}]},{erl_eval,expr,6,[{file,"erl_eval.erl"},{line,454}]},{erl_eval,expr_list,7,[{file,"erl_eval.erl"},{line,961}]}]}}
init terminating in do_boot ({,[{Elixir.Jason,decode!,2,[{_},{_},{_}]},{Elixir.FzHttpWeb.Mailer,configs_for,1,[{_},{_}]},{elixir_eval,__FILE__,1,[{_},{_}]},{elixir,-eval_external_handler/1-fun-2-,4,[{_},{_}]},{erl_eval,do_apply,7,[{_},{_}]},{erl_eval,expr_list,7,[{_},{_}]},{erl_eval,expr,6,[{_},{_}]},{erl_eval,expr_list,7,[{_},{_}]}]})

Crash dump is being written to: erl_crash.dump...done
ERROR! Config provider Config.Reader failed with:

```
without single quotes, there are no errors. 

My version:
```
docker version
Client:
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.2
 Git commit:        20.10.12-0ubuntu2~20.04.1
 Built:             Wed Apr  6 02:14:38 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.2
  Git commit:       20.10.12-0ubuntu2~20.04.1
  Built:            Thu Feb 10 15:03:35 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.9-0ubuntu1~20.04.6
  GitCommit:
 runc:
  Version:          1.1.0-0ubuntu1~20.04.2
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:
```

```
docker-compose version
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.10
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

The problem turned out to be on my side, I used the account password and I needed to create a password for the application.

**Comment by jamilbk** [comment]
Gotcha -- wrapping in single quotes is needed depending on how the variables are supplied, so it looks like yours do not need escaping.
