### ISSUE TITLE
REST API Get Configuration parsing error when custom logo image

### ISSUE THREAD

**Issue by AYDEV-FR** [CloudFire-LLC/cloudfire#1363]
Hi,

When I try to get configuration trought REST API like this :
```
curl -i \
  -X GET "https://FIREZONE URL/v0/configuration" \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer TOKEN'

HTTP/2 500
alt-svc: h3=":443"; ma=2592000
cache-control: max-age=0, private, must-revalidate
content-type: application/json; charset=utf-8
date: Mon, 23 Jan 2023 10:37:28 GMT
server: Caddy
server: Cowboy
x-request-id: Fzzp0fVTY8y-JOYAAAbh
content-length: 23

"Internal Server Error"
```

I obtain this log in firezone container 
```
Request: GET /v0/configuration
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol Jason.Encoder not implemented for %FzHttp.Configurations.Logo{url: nil, data: "iVBORw0KGgoAAAANSUhEUgAAAaUAAAGlCAYAAABa0umuAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAArGVYSWZNTQAqAAAACAAFARIAAwAAAAEAAQAAARoABQAAAAEAAABKARsABQAAAAEAAABSASgAAwAAAAEAAgAAh2kABAAAAAEAAABaAAAAAAAAANgAAAABAAAA2AAAAAEABJKGAAcAAAAcAAAAkKABAAMAAAABAAEAAKACAAQAAAABAAABpaADAAQAAAABAAABpQAAAABBU0NJSQAAAHt7MCwgMH0sIHs0MjAsIDQyMH19fMCoQgAAAAlwSFlzAAAhOAAAITgBRZYxYAAAAqtpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IlhNUCBDb3JlIDYuMC4wIj4KICAgPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICAgICAgPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIKICAgICAgICAgICAgeG1sbnM6ZXhpZj0iaHR0cDovL25zLmFkb2JlLmNvbS9leGlmLzEuMC8iCiAgICAgICAgICAgIHhtbG5zOnRpZmY9Imh0dHA6Ly9ucy5hZG9iZS5jb20vdGlmZi8xLjAvIj4KICAgICAgICAgPGV4aWY6UGl4ZWxYRGltZW5zaW9uPjQyMTwvZXhpZjpQaXhlbFhEaW1lbnNpb24+CiAgICAgICAgIDxleGlmOkNvbG9yU3BhY2U+MTwvZXhpZjpDb2xvclNwYWNlPgogICAgICAgICA8ZXhpZjpVc2VyQ29tbWVudD57ezAsIDB9LCB7NDIwLCA0MjB9fTwvZXhpZjpVc2VyQ29tbWVudD4KICAgICAgICAgPGV4aWY6UGl4ZWxZRGltZW5zaW9uPjQyMTwvZXhpZjpQaXhlbFlEaW1lbnNpb24+CiAgICAgICAgIDx0aWZmOlJlc29sdXRpb25Vbml0PjI8L3RpZmY6UmVzb2x1dGlvblVuaXQ+CiAgICAgICAgIDx0aWZmOk9yaWVudGF0aW9uPjE8L3RpZmY6T3JpZW50YXRpb24+CiAgICAgIDwvcmRmOkRlc2NyaXB0aW9uPgogICA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgo61Ax0AABAAElEQVR4Aey96ZMmR3Lml9VdXXf1fR9AN67BMSeJGXIODmp47HKXoijbNX2RrZkgM33Xn4Cev4TcjzSTmcyWshUlkwk9yxGHIrk85sQcmGkAjaPvq7q77tLzezw8M9+3qhrAcDBAV0V0ZUaEh4eHh+fbj2ccmdk0NVQLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUC1QLVAtUCzxKFhh5lJStuu4cC/zhi8/O0dtdza65//z3PzxPuoZqgWqB7W+B6pS2/zV+5Hr4jc89+erukV1zo6O7m927djXNyEizvr7WrK2tf3NlZeXC//1PP7vwYTuFk1tbW5vbtWvXS6r7raz/l3//2vlM17haoFrg47dAdUof/zWoGvQs8NVnz7w6Ojo6t3v3rmZiz55m/+x0MzE+3iwtrzR37z9olldX5ZxwUGvf/L/+4Sfne1U3JH//809Jzu5XVldX5ygckXMbl6ObmphoRuTslpeXm8WV1UYe78L6+vq3bty60/zNz945D28N1QLVAh+PBapT+njsXlvdxAJfefax87t2jbxC0Z7dOI+xZu/0dHP44MFmfGxMjmmpuXX7TnNrfl7Oaa1Zl3OSQ/nmimKNns6nyK89e3puYmLiFTmauXURNdZqRuXkxkb3NHv2jFq2HJ/Se5oxHeJr7j14IKd3v1mR3DXJrCOotGaNqwV+vRaoTunXa+/a2hYWePGp43NT4xOvMprhR0k8MbanmZ2aamamp5qD+/c3GvU0mr5r5u/da67futXcX1xiSk9OZE11RppVTe+NjKy/pCm6OfgIOBw7pN2jqq8VKslVuWXtkWOyc1I8JqdHfmFpsbl281bzYGnZo7HqnGzGeqoW+LVZoDqlX5upa0NbWYBpNjmhV3EgOBn5jVhLUoWpifFmxo5putk3O2sRK6srzeLiYnNdzuP+wmKzJAe0qtES9fWnQKxDKUZJ44yO5HC8PmWXZybltWYlR5WjJkZjjJzI39fI6erNm8XxrX1TU4AvQUfe+sjIXGlIOVpzuDAqZ7eqaUCmF+fvLzTf/uHF81FUz9UC1QIf1ALVKX1QS1W+X6kFcESAvMIrOuZwIsC7NjgoUhrPVOJprQFNTk40B/bubTQtJ/J6Iyeh6bxlTefdbh7IQS0sLcXUmxyC/JplMSriB86Ia3zPmNaRRhj9aNoPh1WclnjslKQL03njTOnJOTEqo/K9e/eb965fl+OLtSwkIxf9QmdNDcoZ0QaOD6kr8EpHnCCjOQ3kvrm0sjQwxYicGqoFqgU2WoD/szVUC3zkFsgt3hoR2QnhcOw7Sst7NGLBIQD4gP2iNjYQ40SgTU1O6phoDh04YIcB6K9qhIRjYjpvUU4Jx7QsGqMtduvhVZi6G5WDYQSk9So7pJzyS6fCVGHnmDSVJwfGqAnHxFQfDvCaRk3X79wNp0bbotkJFf85pg0UYzi24txoD93Rk3bQ69b8PUZ0db3qI/+11QYeZQtUp/QoX71HQHeckcYrrwj35zz6QWeBNKMQRkXpNMY90tgjlhGvG9nJaJSxKueyqs0HlLNrblYbH/ZqGg8+wH6FERMOSaMlYurlDj3K2TDhaTc5l/yx26GpHuUcBOThUNI5MVrCMWVdHAxTeu9cvepRU462qJeBEdPs1IT6JDnFoeHUOJKPaUZGXqx//ee/rc9fpe1qXC2QFtAcRQ3VAh+NBX73s0+c12jjTzXSOcvazbhAn/WdCYE9U3LTk+N2NDibSR1MnzE6scPxKCPWiRhSMTKBjkOBD2cxIqeGS0i3wDbvdABMneEYqAONPGkf1FE6HZIyluF84UmLpFMhpt19MzMaAWlNSyMfh/BpiLBuyxrhwctICX0IfeeHTvvlVA/MzMydODB9" <> ..., type: "image/png"} of type FzHttp.Configurations.Logo (a struct), Jason.Encoder protocol must always be explicitly implemented.

If you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:

    @derive {Jason.Encoder, only: [....]}
    defstruct ...

It is also possible to encode all fields, although this should be used carefully to avoid accidentally leaking private information when new fields are added:

    @derive Jason.Encoder
    defstruct ...

Finally, if you don't own the struct you want to encode to JSON, you may use Protocol.derive/3 placed outside of any module:

    Protocol.derive(Jason.Encoder, NameOfTheStruct, only: [...])
    Protocol.derive(Jason.Encoder, NameOfTheStruct)
. This protocol is implemented for the following type(s): Any, Atom, BitString, Date, DateTime, Decimal, Ecto.Association.NotLoaded, Ecto.Schema.Metadata, Float, Integer, Jason.Fragment, Jason.OrderedObject, List, Map, NaiveDateTime, Postgrex.INET, Time
        (jason 1.4.0) lib/jason.ex:213: Jason.encode_to_iodata!/2
        (phoenix 1.7.0-rc.2) lib/phoenix/controller.ex:958: anonymous fn/5 in Phoenix.Controller.template_render_to_iodata/4
        (telemetry 1.2.1) /app/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
        (phoenix 1.7.0-rc.2) lib/phoenix/controller.ex:924: Phoenix.Controller.render_and_send/4
        (fz_http 0.7.5) lib/fz_http_web/controllers/json/configuration_controller.ex:1: FzHttpWeb.JSON.ConfigurationController.action/2
        (fz_http 0.7.5) lib/fz_http_web/controllers/json/configuration_controller.ex:1: FzHttpWeb.JSON.ConfigurationController.phoenix_controller_pipeline/2
        (phoenix 1.7.0-rc.2) lib/phoenix/router.ex:425: Phoenix.Router.__call__/5
        (fz_http 0.7.5) lib/fz_http_web/endpoint.ex:1: FzHttpWeb.Endpoint.plug_builder_call/2
```

**Comment by AYDEV-FR** [comment]
Futhermore, I have the same issue when I use URL field to change logo

```
Request: GET /v0/configuration
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol Jason.Encoder not implemented for %FzHttp.Configurations.Logo{url: "https://LOGO_URL.png", data: nil, type: nil} of type FzHttp.Configurations.Logo (a struct), Jason.Encoder protocol must always be explicitly implemented.

If you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:

    @derive {Jason.Encoder, only: [....]}
    defstruct ...

It is also possible to encode all fields, although this should be used carefully to avoid accidentally leaking private information when new fields are added:

    @derive Jason.Encoder
    defstruct ...

Finally, if you don't own the struct you want to encode to JSON, you may use Protocol.derive/3 placed outside of any module:

    Protocol.derive(Jason.Encoder, NameOfTheStruct, only: [...])
    Protocol.derive(Jason.Encoder, NameOfTheStruct)
. This protocol is implemented for the following type(s): Any, Atom, BitString, Date, DateTime, Decimal, Ecto.Association.NotLoaded, Ecto.Schema.Metadata, Float, Integer, Jason.Fragment, Jason.OrderedObject, List, Map, NaiveDateTime, Postgrex.INET, Time
        (jason 1.4.0) lib/jason.ex:213: Jason.encode_to_iodata!/2
        (phoenix 1.7.0-rc.2) lib/phoenix/controller.ex:958: anonymous fn/5 in Phoenix.Controller.template_render_to_iodata/4
        (telemetry 1.2.1) /app/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
        (phoenix 1.7.0-rc.2) lib/phoenix/controller.ex:924: Phoenix.Controller.render_and_send/4
        (fz_http 0.7.5) lib/fz_http_web/controllers/json/configuration_controller.ex:1: FzHttpWeb.JSON.ConfigurationController.action/2
        (fz_http 0.7.5) lib/fz_http_web/controllers/json/configuration_controller.ex:1: FzHttpWeb.JSON.ConfigurationController.phoenix_controller_pipeline/2
        (phoenix 1.7.0-rc.2) lib/phoenix/router.ex:425: Phoenix.Router.__call__/5
        (fz_http 0.7.5) lib/fz_http_web/endpoint.ex:1: FzHttpWeb.Endpoint.plug_builder_call/2
```

**Comment by AndrewDryga** [comment]
Hey @AYDEV-FR, I'm sorry that you hit this issue. I pushed a PR to fix it, I guess we can release it pretty fast.
