### ISSUE TITLE
Increase length for Allowed IPs

### ISSUE THREAD

**Issue by ihard** [CloudFire-LLC/cloudfire#1374]
Now I get error:
```
11:53:54.406 [error] GenServer #PID<0.9000.0> terminating
** (Postgrex.Error) ERROR 22001 (string_data_right_truncation) value too long for type character varying(255)
    (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto 3.9.4) lib/ecto/repo/schema.ex:756: Ecto.Repo.Schema.apply/4
    (ecto 3.9.4) lib/ecto/repo/schema.ex:459: anonymous fn/15 in Ecto.Repo.Schema.do_update/4
```

if insert list network:
```
1.0.0.0/8, 2.0.0.0/7, 4.0.0.0/6, 8.0.0.0/7, 11.0.0.0/8, 12.0.0.0/6, 16.0.0.0/4, 32.0.0.0/3, 64.0.0.0/5, 72.0.0.0/6, 76.0.0.0/8, 77.0.0.0/10, 77.64.0.0/13, 77.72.0.0/15, 77.74.0.0/16, 77.75.0.0/17, 77.75.128.0/20, 77.75.144.0/21, 77.75.160.0/19, 77.75.192.0/18, 77.76.0.0/14, 77.80.0.0/12, 77.96.0.0/11, 77.128.0.0/9, 78.0.0.0/7, 80.0.0.0/4, 96.0.0.0/5, 104.0.0.0/6, 108.0.0.0/8, 109.0.0.0/9, 109.128.0.0/10, 109.192.0.0/11, 109.224.0.0/13, 109.232.0.0/15, 109.234.0.0/16, 109.235.0.0/17, 109.235.128.0/19, 109.235.168.0/21, 109.235.176.0/20, 109.235.192.0/18, 109.236.0.0/14, 109.240.0.0/12, 110.0.0.0/7, 112.0.0.0/5, 120.0.0.0/6, 124.0.0.0/7, 126.0.0.0/8, 128.0.0.0/3, 160.0.0.0/5, 168.0.0.0/8, 169.0.0.0/9, 169.128.0.0/10, 169.192.0.0/11, 169.224.0.0/12, 169.240.0.0/13, 169.248.0.0/14, 169.252.0.0/15, 169.255.0.0/16, 170.0.0.0/7, 172.0.0.0/12, 172.32.0.0/11, 172.64.0.0/10, 172.128.0.0/9, 173.0.0.0/8, 174.0.0.0/7, 176.0.0.0/5, 184.0.0.0/8, 185.0.0.0/10, 185.64.0.0/14, 185.68.0.0/15, 185.70.0.0/16, 185.71.0.0/18, 185.71.64.0/21, 185.71.72.0/22, 185.71.80.0/20, 185.71.96.0/19, 185.71.128.0/17, 185.72.0.0/13, 185.80.0.0/12, 185.96.0.0/11, 185.128.0.0/9, 186.0.0.0/7, 188.0.0.0/6, 192.0.0.0/9, 192.128.0.0/11, 192.160.0.0/13, 192.169.0.0/16, 192.170.0.0/15, 192.172.0.0/14, 192.176.0.0/12, 192.192.0.0/10, 193.0.0.0/8, 194.0.0.0/7, 196.0.0.0/6, 200.0.0.0/5, 208.0.0.0/4, 224.0.0.0/4, ::/3, 2000::/5, 2800::/7, 2a00::/15, 2a02::/18, 2a02:4000::/20, 2a02:5000::/24, 2a02:5100::/25, 2a02:5181::/32, 2a02:5182::/31, 2a02:5184::/30, 2a02:5188::/29, 2a02:5190::/28, 2a02:51a0::/27, 2a02:51c0::/26, 2a02:5200::/23, 2a02:5400::/22, 2a02:5800::/21, 2a02:6000::/19, 2a02:8000::/17, 2a03::/16, 2a04::/14, 2a08::/13, 2a10::/12, 2a20::/11, 2a40::/10, 2a80::/9, 2b00::/8, 2c00::/6, 3000::/4, 4000::/2, 8000::/2, c000::/3, e000::/4, f000::/5, f800::/6, fe00::/9, fec0::/10, ff00::/8
```
So many because some used networks are excluded. So that they continue to work when VPN is connected.

**Comment by jamilbk** [comment]
Thanks for the report! Should have this fixed shortly.

**Comment by AndrewDryga** [comment]
This will be addressed as part of #1352, instead of increasing the field size we should just use an array `inet[]`.

**Comment by AddRemover** [comment]
due to this limit, migration from v6.x failed:
```
2023-01-26 09:45:22.133 UTC [33] ERROR:  value too long for type character varying(255)
2023-01-26 09:45:22.133 UTC [33] STATEMENT:    UPDATE configurations
      SET default_client_allowed_ips = (
        SELECT allowed_ips
        FROM sites
        WHERE sites.name = 'default'
      )
```
so I have to manually update sites table and shrink value of Allowed_IPs.

**Comment by AndrewDryga** [comment]
I'm sorry that you hit this issue, until a proper fix is coming I'm going to release a new version today with a temporary fix to unlock your environments.
