### ISSUE TITLE
Unable to delete OpenID and SAML providers configuration

### ISSUE THREAD

**Issue by komailo** [CloudFire-LLC/cloudfire#1382]
Version: 0.7.6

I have three SAML configurations that I added to test out SAML integration with JumpCloud which is failing for some reason which I am still trying to investigate. However, I am unable to delete the configurations and noticed that the error in the logs points to another SAML configuration which I am not attempting to delete.

```
17:32:32.729 [error] GenServer #PID<0.2328.0> terminating
** (Ecto.CastError) expected params to be a :map, got: `%FzHttp.Configurations.Configuration.SAMLIdentityProvider{id: "XXXX-azuread", label: "Azure-AD", base_url: "https://XXXX.XXXX.XXXX/auth/saml", metadata: "<?xml version=\"1.0\" encoding=\"utf-8\"?><EntityDescriptor ID=\"1234\" entityID=\"1234\" xmlns=\"urn:oasis:names:tc:SAML:2.0:metadata\"><Signature xmlns=\"1234\"></Signature ></EntityDescriptor>", sign_requests: false, sign_metadata: false, signed_assertion_in_resp: false, signed_envelopes_in_resp: false, auto_create_users: false}`
    (ecto 3.9.4) lib/ecto/changeset.ex:498: Ecto.Changeset.cast/4
    (fz_http 0.7.6) lib/fz_http/configurations/configuration/saml_identity_provider.ex:29: FzHttp.Configurations.Configuration.SAMLIdentityProvider.changeset/2
    (ecto 3.9.4) lib/ecto/changeset/relation.ex:137: Ecto.Changeset.Relation.do_cast/6
    (ecto 3.9.4) lib/ecto/changeset/relation.ex:356: Ecto.Changeset.Relation.map_changes/9
    (ecto 3.9.4) lib/ecto/changeset/relation.ex:121: Ecto.Changeset.Relation.cast/5
    (ecto 3.9.4) lib/ecto/changeset.ex:832: Ecto.Changeset.cast_relation/4
    (fz_http 0.7.6) lib/fz_http/configurations/configuration.ex:83: FzHttp.Configurations.Configuration.changeset/2
    (fz_http 0.7.6) lib/fz_http/configurations.ex:70: FzHttp.Configurations.update_configuration/2
Last message: %Phoenix.Socket.Message{topic: "lv:phx-Fz3sIxyQZ0BAOQGk", event: "event", payload: %{"event" => "delete", "type" => "click", "value" => %{"key" => "XXXX-jumpcloud1", "type" => "saml", "value" => ""}}, ref: "23", join_ref: "21"}
```

I tried clean up the configuration for the configuration that the above log is erroring on and have left the minimum required data. However, unable to delete still.

**Comment by AndrewDryga** [comment]
Hey @KomailKanjee, can you please share your `schema_migrations` table?

Here is a query:
```sql
SELECT * FROM schema_migrations;
```

You can use PSQL to run it (you might need to enter DB password from `.env` file):
```bash
psql -d firezone -h 127.0.0.1 -U postgres -c "SELECT * FROM schema_migrations"
```

**Comment by komailo** [comment]
Here is the output:
```
    version     |     inserted_at
----------------+---------------------
 20200225005454 | 2023-01-18 21:50:19
 20200228145810 | 2023-01-18 21:50:19
 20200228154815 | 2023-01-18 21:50:19
 20210929172417 | 2023-01-18 21:50:19
 20211116172808 | 2023-01-18 21:50:19
 20211116173236 | 2023-01-18 21:50:19
 20211203012238 | 2023-01-18 21:50:19
 20211216155557 | 2023-01-18 21:50:19
 20211217003247 | 2023-01-18 21:50:19
 20211221183311 | 2023-01-18 21:50:19
 20211223161545 | 2023-01-18 21:50:19
 20220103175026 | 2023-01-18 21:50:19
 20220111004847 | 2023-01-18 21:50:19
 20220124162404 | 2023-01-18 21:50:20
 20220127021835 | 2023-01-18 21:50:20
 20220127191440 | 2023-01-18 21:50:20
 20220208184257 | 2023-01-18 21:50:20
 20220209005201 | 2023-01-18 21:50:20
 20220211201727 | 2023-01-18 21:50:20
 20220219165023 | 2023-01-18 21:50:20
 20220227215313 | 2023-01-18 21:50:20
 20220412144151 | 2023-01-18 21:50:20
 20220419172036 | 2023-01-18 21:50:20
 20220427140943 | 2023-01-18 21:50:20
 20220516063916 | 2023-01-18 21:50:20
 20220519034545 | 2023-01-18 21:50:20
 20220520072323 | 2023-01-18 21:50:20
 20220530073152 | 2023-01-18 21:50:20
 20220609232854 | 2023-01-18 21:50:20
 20220614192937 | 2023-01-18 21:50:20
 20220713050742 | 2023-01-18 21:50:20
 20220719014442 | 2023-01-18 21:50:20
 20220721164925 | 2023-01-18 21:50:20
 20220726205646 | 2023-01-18 21:50:20
 20220810002432 | 2023-01-18 21:50:20
 20220831060724 | 2023-01-18 21:50:20
 20221012123308 | 2023-01-18 21:50:20
 20221129002233 | 2023-01-18 21:50:20
 20221223190406 | 2023-01-18 21:50:21
 20221223223357 | 2023-01-18 21:50:21
 20221223223931 | 2023-01-18 21:50:21
 20221224210654 | 2023-01-18 21:50:21
 20221226044850 | 2023-01-18 21:50:21
 20221226143651 | 2023-01-18 21:50:21
 20221226171558 | 2023-01-18 21:50:21
 20221226193228 | 2023-01-18 21:50:21
 20221227181727 | 2023-01-18 21:50:21
 20221229154115 | 2023-01-18 21:50:21
 20230113184557 | 2023-01-18 21:50:21
 20230104000803 | 2023-01-23 04:53:17
 20230104181853 | 2023-01-23 04:53:17
 20230116200524 | 2023-01-23 04:53:17
```

**Comment by AndrewDryga** [comment]
@KomailKanjee thank you! Can you please run this one too:

```sql
SELECT openid_connect_providers, saml_identity_providers FROM configurations;
```

**Please make sure that you trim returned JSON from any secret values**, I just need to see the structure stored there.

**Comment by AndrewDryga** [comment]
To give some context we had [a migration](https://github.com/firezone/firezone/blob/master/apps/fz_http/priv/repo/migrations/20221229154115_migrate_providers_configs.exs#L8) that changed the structure for those fields, by looking at the list of your migrations it was executed, but for some reason error tells that it did not migrate the data. Just want to confirm that's the cause, and if it is you should be able to resolve it by running:

```sql
UPDATE configurations
SET openid_connect_providers = COALESCE((select jsonb_agg(o.item::jsonb || jsonb_build_object('id', key)) from jsonb_each(openid_connect_providers) as o(key, item)), '[]'::jsonb),
    saml_identity_providers = COALESCE((select jsonb_agg(s.item::jsonb || jsonb_build_object('id', key)) from jsonb_each(saml_identity_providers) as s(key, item)), '[]'::jsonb)
```

Otherwise, it's an issue somewhere in the codebase but will be easy to fix.

**Comment by komailo** [comment]
@AndrewDryga here is the output of the SQL command:
```
 openid_connect_providers |








               saml_identity_providers









--------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------
 []                       | [{"id": "jumpcloud", "label": "JumpCloud", "base_url": "https://XXXX.XXXX.com/auth/saml", "metadata": "<?xml version=\"1.0\" encoding=\"UTF-8\"?><md:EntityDescriptor xmlns:m
d=\"urn:oasis:names:tc:SAML:2.0:metadata\" entityID=\"firezone-jumpcloud\"><md:IDPSSODescriptor WantAuthnRequestsSigned=\"false\" protocolSupportEnumeration=\"urn:oasis:names:tc:SAML:2.0:protocol\"><md:KeyDescript
or use=\"signing\"><ds:KeyInfo xmlns:ds=\"http://www.w3.org/2000/09/xmldsig#\"><ds:X509Data><ds:X509Certificate>XXXXXXXX</ds:X509Certificate></ds:X509Data></ds:KeyInfo></md:KeyDescriptor><md:NameIDFormat>urn:oasis:names:tc:SAML:1.0:nameid-format:unspecified<
/md:NameIDFormat><md:SingleSignOnService Binding=\"urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST\" Location=\"https://sso.jumpcloud.com/saml2/XXXXXXXX\"/></md:IDPSSODescriptor></md:EntityDescriptor>", "sign
_metadata": true, "sign_requests": true, "auto_create_users": true, "signed_assertion_in_resp": true, "signed_envelopes_in_resp": false}, {"id": "XXXX-azuread", "label": "Azure-AD", "base_url": "https://ot
t-firezone.XXXX.com/auth/saml", "metadata": "<?xml version=\"1.0\" encoding=\"utf-8\"?><EntityDescriptor ID=\"1234\" entityID=\"1234\" xmlns=\"urn:oasis:names:tc:SAML:2.0:metadata\"><Signature xmlns=\"1234\"><
/Signature ></EntityDescriptor>", "sign_metadata": false, "sign_requests": false, "auto_create_users": false, "signed_assertion_in_resp": false, "signed_envelopes_in_resp": false}, {"id": "XXXX-jumpcloud",
 "label": "XXXX-jumpcloud", "base_url": "https://XXXX.XXXX.com/auth/saml", "metadata": "<?xml version=\"1.0\" encoding=\"utf-8\"?><EntityDescriptor ID=\"1234\" entityID=\"1234\" xmlns=\"urn:oas
is:names:tc:SAML:2.0:metadata\"><Signature xmlns=\"1234\"></Signature ></EntityDescriptor>", "sign_metadata": false, "sign_requests": false, "auto_create_users": true, "signed_assertion_in_resp": false, "signed_en
velopes_in_resp": false}]
(1 row)
```

Note: While debugging I did add another SAML provider.

**Comment by komailo** [comment]
The update command to resulted in this error:
```
docker exec -ti firezone-postgres-1 psql -d firezone -h 127.0.0.1 -U postgres -c """
    UPDATE configurations
    SET openid_connect_providers = COALESCE((select jsonb_agg(o.item::jsonb || jsonb_build_object('id', key)) from jsonb_each(openid_connect_providers) as o(key, item)), '[]'::jsonb),
        saml_identity_providers = COALESCE((select jsonb_agg(s.item::jsonb || jsonb_build_object('id', key)) from jsonb_each(saml_identity_providers) as s(key, item)), '[]'::jsonb)
    """
ERROR:  cannot call jsonb_each on a non-object
```

I might dig into the database and try deleting it manually since I am working in a dev environment.

**Comment by AndrewDryga** [comment]
So this issue is something else, give me a minute to think about it.

**Comment by komailo** [comment]
Thanks @AndrewDryga will stay put.

**Comment by AndrewDryga** [comment]
I found a bug and will push a PR with a fix shortly. Thanks for your help with debugging!

**Comment by AndrewDryga** [comment]
@KomailKanjee a new release should be out in about an hour, please let me know if it did not solve your issue.

**Comment by komailo** [comment]
@AndrewDryga I upgraded to 0.7.7 and tried deleting the existing SAML entries. Still getting the same error:
```
15:15:07.058 [error] GenServer #PID<0.545.0> terminating
** (Ecto.CastError) expected params to be a :map, got: `%FzHttp.Configurations.Configuration.SAMLIdentityProvider{id: "jumpcloud", label: "JumpCloud", base_url: "https://XXXX.XXXX.com/auth/saml", metadata: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><md:EntityDescriptor xmlns:md=\"urn:oasis:names:tc:SAML:2.0:metadata\" entityID=\"firezone-jumpcloud\"><md:IDPSSODescriptor WantAuthnRequestsSigned=\"false\" protocolSupportEnumeration=\"urn:oasis:names:tc:SAML:2.0:protocol\"><md:KeyDescriptor use=\"signing\"><ds:KeyInfo xmlns:ds=\"http://www.w3.org/2000/09/xmldsig#\"><ds:X509Data><ds:X509Certificate></ds:X509Certificate></ds:X509Data></ds:KeyInfo></md:KeyDescriptor><md:NameIDFormat>urn:oasis:names:tc:SAML:1.0:nameid-format:unspecified</md:NameIDFormat><md:SingleSignOnService Binding=\"urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST\" Location=\"https://sso.jumpcloud.com/saml2/firezone818551\"/></md:IDPSSODescriptor></md:EntityDescriptor>", sign_requests: true, sign_metadata: true, signed_assertion_in_resp: true, signed_envelopes_in_resp: false, auto_create_users: true}`
    (ecto 3.9.4) lib/ecto/changeset.ex:498: Ecto.Changeset.cast/4
    (fz_http 0.7.7) lib/fz_http/configurations/configuration/saml_identity_provider.ex:29: FzHttp.Configurations.Configuration.SAMLIdentityProvider.changeset/2
    (ecto 3.9.4) lib/ecto/changeset/relation.ex:137: Ecto.Changeset.Relation.do_cast/6
    (ecto 3.9.4) lib/ecto/changeset/relation.ex:356: Ecto.Changeset.Relation.map_changes/9
    (ecto 3.9.4) lib/ecto/changeset/relation.ex:121: Ecto.Changeset.Relation.cast/5
    (ecto 3.9.4) lib/ecto/changeset.ex:832: Ecto.Changeset.cast_relation/4
    (fz_http 0.7.7) lib/fz_http/configurations/configuration.ex:83: FzHttp.Configurations.Configuration.changeset/2
    (fz_http 0.7.7) lib/fz_http/configurations.ex:70: FzHttp.Configurations.update_configuration/2
Last message: %Phoenix.Socket.Message{topic: "lv:phx-Fz4zOvLZH9wn0wYi", event: "event", payload: %{"event" => "delete", "type" => "click", "value" => %{"key" => "XXXX-jumpcloud", "type" => "saml", "value" => ""}}, ref: "21", join_ref: "18"}
```

Migration table:
```
docker exec -ti firezone-postgres-1 psql -d firezone -h 127.0.0.1 -U postgres -c "SELECT * FROM schema_migrations"
    version     |     inserted_at
----------------+---------------------
 20200225005454 | 2023-01-18 21:50:19
 20200228145810 | 2023-01-18 21:50:19
 20200228154815 | 2023-01-18 21:50:19
 20210929172417 | 2023-01-18 21:50:19
 20211116172808 | 2023-01-18 21:50:19
 20211116173236 | 2023-01-18 21:50:19
 20211203012238 | 2023-01-18 21:50:19
 20211216155557 | 2023-01-18 21:50:19
 20211217003247 | 2023-01-18 21:50:19
 20211221183311 | 2023-01-18 21:50:19
 20211223161545 | 2023-01-18 21:50:19
 20220103175026 | 2023-01-18 21:50:19
 20220111004847 | 2023-01-18 21:50:19
 20220124162404 | 2023-01-18 21:50:20
 20220127021835 | 2023-01-18 21:50:20
 20220127191440 | 2023-01-18 21:50:20
 20220208184257 | 2023-01-18 21:50:20
 20220209005201 | 2023-01-18 21:50:20
 20220211201727 | 2023-01-18 21:50:20
 20220219165023 | 2023-01-18 21:50:20
 20220227215313 | 2023-01-18 21:50:20
 20220412144151 | 2023-01-18 21:50:20
 20220419172036 | 2023-01-18 21:50:20
 20220427140943 | 2023-01-18 21:50:20
 20220516063916 | 2023-01-18 21:50:20
 20220519034545 | 2023-01-18 21:50:20
 20220520072323 | 2023-01-18 21:50:20
 20220530073152 | 2023-01-18 21:50:20
 20220609232854 | 2023-01-18 21:50:20
 20220614192937 | 2023-01-18 21:50:20
 20220713050742 | 2023-01-18 21:50:20
 20220719014442 | 2023-01-18 21:50:20
 20220721164925 | 2023-01-18 21:50:20
 20220726205646 | 2023-01-18 21:50:20
 20220810002432 | 2023-01-18 21:50:20
 20220831060724 | 2023-01-18 21:50:20
 20221012123308 | 2023-01-18 21:50:20
 20221129002233 | 2023-01-18 21:50:20
 20221223190406 | 2023-01-18 21:50:21
 20221223223357 | 2023-01-18 21:50:21
 20221223223931 | 2023-01-18 21:50:21
 20221224210654 | 2023-01-18 21:50:21
 20221226044850 | 2023-01-18 21:50:21
 20221226143651 | 2023-01-18 21:50:21
 20221226171558 | 2023-01-18 21:50:21
 20221226193228 | 2023-01-18 21:50:21
 20221227181727 | 2023-01-18 21:50:21
 20221229154115 | 2023-01-18 21:50:21
 20230113184557 | 2023-01-18 21:50:21
 20230104000803 | 2023-01-23 04:53:17
 20230104181853 | 2023-01-23 04:53:17
 20230116200524 | 2023-01-23 04:53:17
(52 rows)
```

```
docker exec -ti firezone-postgres-1 psql -d firezone -h 127.0.0.1 -U postgres -c "SELECT openid_connect_providers, saml_identity_providers FROM configurations;"
 openid_connect_providers |








               saml_identity_providers









--------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------
 []                       | [{"id": "jumpcloud", "label": "JumpCloud", "base_url": "https://XXXX.XXXX.com/auth/saml", "metadata": "<?xml version=\"1.0\" encoding=\"UTF-8\"?><md:EntityDescriptor xmlns:m
d=\"urn:oasis:names:tc:SAML:2.0:metadata\" entityID=\"firezone-jumpcloud\"><md:IDPSSODescriptor WantAuthnRequestsSigned=\"false\" protocolSupportEnumeration=\"urn:oasis:names:tc:SAML:2.0:protocol\"><md:KeyDescript
or use=\"signing\"><ds:KeyInfo xmlns:ds=\"http://www.w3.org/2000/09/xmldsig#\"><ds:X509Data><ds:X509Certificate>XXXXXX</ds:X509Certificate></ds:X509Data></ds:KeyInfo></md:KeyDescriptor><md:NameIDFormat>urn:oasis:names:tc:SAML:1.0:nameid-format:unspecified<
/md:NameIDFormat><md:SingleSignOnService Binding=\"urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST\" Location=\"https://sso.jumpcloud.com/saml2/XXXXX\"/></md:IDPSSODescriptor></md:EntityDescriptor>", "sign
_metadata": true, "sign_requests": true, "auto_create_users": true, "signed_assertion_in_resp": true, "signed_envelopes_in_resp": false}, {"id": "XXXX-azuread", "label": "Azure-AD", "base_url": "https://XXXX.XXXX.com/auth/saml", "metadata": "<?xml version=\"1.0\" encoding=\"utf-8\"?><EntityDescriptor ID=\"1234\" entityID=\"1234\" xmlns=\"urn:oasis:names:tc:SAML:2.0:metadata\"><Signature xmlns=\"1234\"><
/Signature ></EntityDescriptor>", "sign_metadata": false, "sign_requests": false, "auto_create_users": false, "signed_assertion_in_resp": false, "signed_envelopes_in_resp": false}, {"id": "XXXX-jumpcloud",
 "label": "XXXX-jumpcloud", "base_url": "https://XXXX.XXXX.com/auth/saml", "metadata": "<?xml version=\"1.0\" encoding=\"utf-8\"?><EntityDescriptor ID=\"1234\" entityID=\"1234\" xmlns=\"urn:oas
is:names:tc:SAML:2.0:metadata\"><Signature xmlns=\"1234\"></Signature ></EntityDescriptor>", "sign_metadata": false, "sign_requests": false, "auto_create_users": true, "signed_assertion_in_resp": false, "signed_en
velopes_in_resp": false}]
(1 row)
```

**Comment by AndrewDryga** [comment]
@KomailKanjee hm, Is there a chance that you accidentally upgraded to 0.7.6 instead of 0.7.7? The error log doesn't make a lot of sense for 0.7.7 (the line it reports changed but exactly matches the line in your first report). You can make sure it's up to date by doing:

```
docker-compose down
docker pull firezone/firezone:0.7.7
docker-compose up -d
```

or better just edit `docker-compose.yaml` and set a tag `:0.7.7`:
```diff
- image: firezone/firezone
+ image: firezone/firezone:0.7.7
```

**Comment by komailo** [comment]
I do see 0.7.7 in the UI.
![image](https://user-images.githubusercontent.com/1796298/215144339-f820d254-3e88-4089-a7ab-b8c6251d5d92.png)
The image does say 2 days old even though I pulled `latest`. Will explicitly pull 0.7.7 since the sha of `latest` doesn't match `0.7.7`

**Comment by komailo** [comment]
The image 0.7.7 does resolve this problem.

Thanks @AndrewDryga
