### ISSUE TITLE
Support for AWS Cognito SSO

### ISSUE THREAD

**Issue by aaron791109** [CloudFire-LLC/cloudfire#1385]
I try to add OpenID Connect providers configuration to Firezone ,
But when i save config send the POST request , not save any config on Firezone
It's there cant read format for cognito ?

DOMAIN/.well-known/openid-configuration
```json
{
   "authorization_endpoint":"https://DOMAIN/oauth2/authorize",
   "id_token_signing_alg_values_supported":[
      "RS256"
   ],
   "issuer":"https://cognito-idp.REGION.amazonaws.com/REGION-CODE",
   "jwks_uri":"https://cognito-idp.REGIONamazonaws.com/REGION-CODE/.well-known/jwks.json",
   "response_types_supported":[
      "code",
      "token"
   ],
   "scopes_supported":[
      "openid",
      "email",
      "phone",
      "profile"
   ],
   "subject_types_supported":[
      "public"
   ],
   "token_endpoint":"https://DOMAIN/oauth2/token",
   "token_endpoint_auth_methods_supported":[
      "client_secret_basic",
      "client_secret_post"
   ],
   "userinfo_endpoint":"https://DOMAIN/oauth2/userInfo"
}
```
## Error msg
```
10:34:00.423 [error] GenServer #PID<0.733.0> terminating
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom. This protocol is implemented for the following type(s): DBConnection.PrepareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, File.Stream, Floki.HTMLTree, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, Jason.OrderedObject, List, Map, MapSet, Postgrex.Stream, Range, Stream
    (elixir 1.14.2) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir 1.14.2) lib/enum.ex:166: Enumerable.reduce/3
    (elixir 1.14.2) lib/enum.ex:4307: Enum.sort/2
    (openid_connect 1.0.0) lib/openid_connect/document.ex:129: OpenIDConnect.Document.build_document/1
    (openid_connect 1.0.0) lib/openid_connect/document.ex:25: OpenIDConnect.Document.fetch_document/1
    (fz_http 0.7.7) lib/fz_http/configurations/configuration/openid_connect_provider.ex:66: anonymous fn/2 in FzHttp.Configurations.Configuration.OpenIDConnectProvider.validate_discovery_document_uri/1
    (ecto 3.9.4) lib/ecto/changeset.ex:1735: Ecto.Changeset.validate_change/3
    (fz_http 0.7.7) lib/fz_http/configurations/configuration/openid_connect_provider.ex:57: FzHttp.Configurations.Configuration.OpenIDConnectProvider.changeset/2
```

**Comment by AndrewDryga** [comment]
Hey @aaron791109, I pushed a PR to fix this issue. A new release should be out today

**Comment by AndrewDryga** [comment]
@aaron791109 0.7.8 is out

**Comment by aaron791109** [comment]
@AndrewDryga It work , thx
