### ISSUE TITLE
Docker container no longer starts after 0.7.15

### ISSUE THREAD

**Issue by brendan-pike** [CloudFire-LLC/cloudfire#1453]
The container keeps restarting every 2 seconds, here is the log output.
```
01:39:13.919 erl_level=info application=ecto_sql domain=elixir file=lib/ecto/migrator.ex function=log/2 line=707 mfa=Ecto.Migrator.log/2 module=Ecto.Migrator pid=<0.95.0> [info] Migrations already up
01:39:15.843 erl_level=info application=phoenix domain=elixir file=lib/phoenix/endpoint/cowboy2_adapter.ex function=start_link/3 line=103 mfa=Phoenix.Endpoint.Cowboy2Adapter.start_link/3 module=Phoenix.Endpoint.Cowboy2Adapter pid=<0.370.0> [info] Running FzHttpWeb.Endpoint with cowboy 2.9.0 at 0.0.0.0:13000 (http)
01:39:15.850 erl_level=info application=phoenix domain=elixir file=lib/phoenix/endpoint/supervisor.ex function=log_access_url/2 line=404 mfa=Phoenix.Endpoint.Supervisor.log_access_url/2 module=Phoenix.Endpoint.Supervisor pid=<0.332.0> [info] Access FzHttpWeb.Endpoint at https://wg.outscribe.com.au
01:39:15.852 erl_level=warning application=fz_http domain=elixir file=lib/fz_http/config/errors.ex function=legacy_key_used/3 line=94 mfa=FzHttp.Config.Errors.legacy_key_used/3 module=FzHttp.Config.Errors pid=<0.331.0> [warning] A legacy configuration option 'OUTBOUND_EMAIL_CONFIGS' is used and it will be removed in v0.9. Please use 'OUTBOUND_EMAIL_ADAPTER_OPTS' configuration option instead.
01:39:15.854 erl_level=warning application=fz_http domain=elixir file=lib/fz_http/config/errors.ex function=legacy_key_used/3 line=94 mfa=FzHttp.Config.Errors.legacy_key_used/3 module=FzHttp.Config.Errors pid=<0.331.0> [warning] A legacy configuration option 'WIREGUARD_MTU' is used and it will be removed in v0.8. Please use 'DEFAULT_CLIENT_MTU' configuration option instead.
01:39:15.854 erl_level=warning application=fz_http domain=elixir file=lib/fz_http/config/errors.ex function=legacy_key_used/3 line=94 mfa=FzHttp.Config.Errors.legacy_key_used/3 module=FzHttp.Config.Errors pid=<0.331.0> [warning] A legacy configuration option 'ADMIN_EMAIL' is used and it will be removed in v0.9. Please use 'DEFAULT_ADMIN_EMAIL' configuration option instead.
01:39:15.854 erl_level=warning application=fz_http domain=elixir file=lib/fz_http/config/errors.ex function=legacy_key_used/3 line=94 mfa=FzHttp.Config.Errors.legacy_key_used/3 module=FzHttp.Config.Errors pid=<0.331.0> [warning] A legacy configuration option 'DATABASE_SSL' is used and it will be removed in v0.9. Please use 'DATABASE_SSL_ENABLED' configuration option instead.
01:39:15.854 erl_level=warning application=fz_http domain=elixir file=lib/fz_http/config/errors.ex function=legacy_key_used/3 line=94 mfa=FzHttp.Config.Errors.legacy_key_used/3 module=FzHttp.Config.Errors pid=<0.331.0> [warning] A legacy configuration option 'DATABASE_POOL' is used and it will be removed in v0.9. Please use 'DATABASE_POOL_SIZE' configuration option instead.
01:39:15.854 erl_level=warning application=fz_http domain=elixir file=lib/fz_http/config/errors.ex function=legacy_key_used/3 line=94 mfa=FzHttp.Config.Errors.legacy_key_used/3 module=FzHttp.Config.Errors pid=<0.331.0> [warning] A legacy configuration option 'PRIVATE_CLIENTS' is used and it will be removed in v0.9. Please use 'PHOENIX_PRIVATE_CLIENTS' configuration option instead.
01:39:15.854 erl_level=warning application=fz_http domain=elixir file=lib/fz_http/config/errors.ex function=legacy_key_used/3 line=94 mfa=FzHttp.Config.Errors.legacy_key_used/3 module=FzHttp.Config.Errors pid=<0.331.0> [warning] A legacy configuration option 'EXTERNAL_TRUSTED_PROXIES' is used and it will be removed in v0.9. Please use 'PHOENIX_EXTERNAL_TRUSTED_PROXIES' configuration option instead.
01:39:15.854 erl_level=warning application=fz_http domain=elixir file=lib/fz_http/config/errors.ex function=legacy_key_used/3 line=94 mfa=FzHttp.Config.Errors.legacy_key_used/3 module=FzHttp.Config.Errors pid=<0.331.0> [warning] A legacy configuration option 'SECURE_COOKIES' is used and it will be removed in v0.9. Please use 'PHOENIX_SECURE_COOKIES' configuration option instead.
01:39:16.598 erl_level=notice domain=otp file=application_controller.erl function=info_exited/3 line=2119 mfa=:application_controller.info_exited/3 module=application_controller pid=<0.44.0> [notice] Application fz_wall exited: FzWall.Application.start(:normal, []) returned an error: shutdown: failed to start child: FzWall.Server
    ** (EXIT) an exception was raised:
        ** (CaseClauseError) no case clause matching: {:error, [message: "is invalid"]}
            (fz_wall 0.7.15) lib/fz_wall/cli/live.ex:149: FzWall.CLI.Live.proto/1
            (fz_wall 0.7.15) lib/fz_wall/cli/live.ex:156: FzWall.CLI.Live.modify_elem/2
            (elixir 1.14.3) lib/enum.ex:980: anonymous fn/3 in Enum.each/2
            (elixir 1.14.3) lib/enum.ex:4307: anonymous fn/3 in Enum.each/2
            (elixir 1.14.3) lib/enum.ex:4751: Enumerable.List.reduce/3
            (elixir 1.14.3) lib/enum.ex:4307: Enum.each/2
            (fz_wall 0.7.15) lib/fz_wall/server.ex:18: FzWall.Server.init/1
            (stdlib 4.2) gen_server.erl:851: :gen_server.init_it/2
{"Kernel pid terminated",application_controller,"{application_start_failure,fz_wall,{{shutdown,{failed_to_start_child,'Elixir.FzWall.Server',{{case_clause,{error,[{message,<<\"is invalid\">>}]}},[{'Elixir.FzWall.CLI.Live',proto,1,[{file,\"lib/fz_wall/cli/live.ex\"},{line,149}]},{'Elixir.FzWall.CLI.Live',modify_elem,2,[{file,\"lib/fz_wall/cli/live.ex\"},{line,156}]},{'Elixir.Enum','-each/2-fun-0-',3,[{file,\"lib/enum.ex\"},{line,980}]},{'Elixir.Enum','-each/2-anonymous-3-',3,[{file,\"lib/enum.ex\"},{line,4307}]},{'Elixir.Enumerable.List',reduce,3,[{file,\"lib/enum.ex\"},{line,4751}]},{'Elixir.Enum',each,2,[{file,\"lib/enum.ex\"},{line,4307}]},{'Elixir.FzWall.Server',init,1,[{file,\"lib/fz_wall/server.ex\"},{line,18}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,851}]}]}}},{'Elixir.FzWall.Application',start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,fz_wall,{{shutdown,{failed_to_start_child,'Elixir.FzWall.Server',{{case_clause,{error,[{message,<<"is invalid">>}]}},[{'Elixir.FzWall.CLI.Live',proto,1,[{file,"lib/fz_wall/cli/live.ex"},{line,149}]},{'Elixir.FzWall.CLI.Live',modify_elem,2,[{file,"lib/fz_wall/cli/live.ex"},{line,156}]},{'Elixir.Enum','-each/2-fun-0-',3,[{file,"lib/enum.ex"},{line,980}]},{'Elixir.Enum','-each/2-anonymous-3-',3,[{file,"lib/enum.ex"},{line,4307}]},{'Elixir.Enumerable.List',reduce,3,[{file,"lib/enum.ex"},{line,4751}]},{'Elixir.Enum',each,2,[{file,"lib/enum.ex"},{line,4307}]},{'Elixir.FzWall.Server',init,1,[{file,"lib/fz_wall/server.ex"},{line,18}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,851}]}]}}},{'Elixir.FzWall.Application',start,[normal,[]]}}})

Crash dump is being written to: erl_crash.dump...done
```

My .env file:
```
EXTERNAL_URL="******"
ADMIN_EMAIL="******"
GUARDIAN_SECRET_KEY="******"
DATABASE_ENCRYPTION_KEY="******"
SECRET_KEY_BASE="******"
LIVE_VIEW_SIGNING_SALT="******"
COOKIE_SIGNING_SALT="******"
COOKIE_ENCRYPTION_SALT="******"
DATABASE_NAME="firezone"
DATABASE_HOST=postgres
DATABASE_PORT=5432
DATABASE_POOL="10"
DATABASE_SSL="false"
DATABASE_SSL_OPTS="{}"
DATABASE_PARAMETERS="{}"
EXTERNAL_TRUSTED_PROXIES="[]"
PRIVATE_CLIENTS="[]"
WIREGUARD_PORT="51820"
WIREGUARD_DNS="1.1.1.1, 1.0.0.1"
WIREGUARD_ALLOWED_IPS="0.0.0.0/0, ::/0"
WIREGUARD_PERSISTENT_KEEPALIVE="0"
WIREGUARD_MTU="1280"
WIREGUARD_ENDPOINT="******"
WIREGUARD_IPV4_ENABLED="true"
WIREGUARD_IPV4_MASQUERADE="true"
WIREGUARD_IPV4_NETWORK="10.3.2.0/24"
WIREGUARD_IPV4_ADDRESS="10.3.2.1"
WIREGUARD_IPV6_ENABLED="true"
WIREGUARD_IPV6_MASQUERADE="true"
WIREGUARD_IPV6_NETWORK="fd00::3:2:0/120"
WIREGUARD_IPV6_ADDRESS="fd00::3:2:1"
DISABLE_VPN_ON_OIDC_ERROR="false"
SECURE_COOKIES="true"
ALLOW_UNPRIVILEGED_DEVICE_MANAGEMENT="true"
ALLOW_UNPRIVILEGED_DEVICE_CONFIGURATION="true"
OUTBOUND_EMAIL_CONFIGS="{\"smtp\":{\"relay\":\"smtp.example.com\",\"port\":587,\"username\":\"\",\"password\":\"\",\"ssl\":true,\"tls\":\"always\",\"auth\":\"always\",\"no_mx_lookup\":false,\"retries\":2},\"mailgun\":{\"apikey\":null,\"domain\":null},\"mandrill\":{\"api_key\":null},\"sendgrid\":{\"api_key\":null},\"post_mark\":{\"api_key\":null},\"sendmail\":{\"cmd_path\":\"/usr/bin/sendmail\",\"cmd_args\":\"-N delay,failure,success\"}}"
AUTH_OIDC_JSON="{}"
LOCAL_AUTH_ENABLED="true"
MAX_DEVICES_PER_USER="10"
CONNECTIVITY_CHECKS_ENABLED="true"
CONNECTIVITY_CHECKS_INTERVAL="3600"
CADDY_OPTS=
DATABASE_PASSWORD="******"
DEFAULT_ADMIN_PASSWORD="******"
TLS_OPTS="tls {
  on_demand
}"

```
Let me know what further info I can provide.

Thanks

**Comment by jamilbk** [comment]
Hi @brendan-pike -- thanks for the report. I believe I see the issue -- will have a fix out in a moment.

**Comment by brendan-pike** [comment]
Thank you for the fast fix @jamilbk  just confirming that this did fix the issue.
