### ISSUE TITLE
Upgrade from 0.7.13 -> 0.7.16 - Invalid DNS server IP

### ISSUE THREAD

**Issue by gbe0** [CloudFire-LLC/cloudfire#1458]
**Describe the bug**
After upgrading from 0.7.13 -> 0.7.16, I get an error with the set of IPv6 DNS servers I have configured for clients (see logs below).

**To Reproduce**
`firezone.rb` has this configuration:

```ruby
default['firezone']['wireguard']['dns'] = '1.1.1.1, 1.0.0.1, 8.8.8.8, 8.8.4.4, 2606:4700:4700::1111, 2606:4700:4700::1001, 2001:4860:4860::8888, 2001:4860:4860::8844'
```

Removing the addresses from `firezone.rb` does not fix; rather they are set in the DB.

**Expected behavior**
The IPv6 DNS servers are allowed

**Screenshots / Logs**

```
2023-02-23_07:18:39.15981     ** (EXIT) an exception was raised:
2023-02-23_07:18:39.15981         ** (RuntimeError) Found 1 configuration errors:
2023-02-23_07:18:39.15982
2023-02-23_07:18:39.15982
2023-02-23_07:18:39.15982 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2023-02-23_07:18:39.15982
2023-02-23_07:18:39.15983 Invalid configuration for 'default_client_dns' retrieved from database configuration default_client_dns.
2023-02-23_07:18:39.15983
2023-02-23_07:18:39.15983 Errors:
2023-02-23_07:18:39.15983
2023-02-23_07:18:39.15983  - `" 2001:4860:4860::8844"`: must be one of: Elixir.FzHttp.Types.IP, string, 2001:4860:4860::8844 is not a valid FQDN
2023-02-23_07:18:39.15984  - `" 2001:4860:4860::8888"`: must be one of: Elixir.FzHttp.Types.IP, string, 2001:4860:4860::8888 is not a valid FQDN
2023-02-23_07:18:39.15984  - `" 2606:4700:4700::1001"`: must be one of: Elixir.FzHttp.Types.IP, string, 2606:4700:4700::1001 is not a valid FQDN
2023-02-23_07:18:39.15984  - `" 2606:4700:4700::1111"`: must be one of: Elixir.FzHttp.Types.IP, string, 2606:4700:4700::1111 is not a valid FQDN
2023-02-23_07:18:39.15985             (fz_http 0.7.16) lib/fz_http/config/errors.ex:10: FzHttp.Config.Errors.raise_error!/1
2023-02-23_07:18:39.15987             (fz_http 0.7.16) lib/fz_http/application.ex:12: FzHttp.Application.start/2
2023-02-23_07:18:39.15987             (kernel 8.5) application_master.erl:293: :application_master.start_it_old/4
```

**Platform (please complete the following information):**
 - Firezone Version 0.7.16
 - OS: Linux
 - Distro: Ubuntu 22.04
 - Kernel version: 5.15
 - Deployment method: Omnibus

**Additional context**
N/A

**Comment by jamilbk** [comment]
Thanks for the report @gbe0 -- we made some major improvements and updates to configuration system in 0.7.16, looks like we need to add a test for this case. Will have a fix out for this in a bit

**Comment by AndrewDryga** [comment]
@gbe0 for people running into this the simplest fix is to remove whitespace after the comma if it's not set in the database:
```
default['firezone']['wireguard']['dns'] = '1.1.1.1,1.0.0.1,8.8.8.8,8.8.4.4,2606:4700:4700::1111,2606:4700:4700::1001,2001:4860:4860::8888,2001:4860:4860::8844'
```

I'm working on a migration to fix it globally, at the same time if your DNS is set in env var we will not migrate those fields - you need to remove whitespace manually.
