### ISSUE TITLE
502 Bad Gateway error after update 0.7.17

### ISSUE THREAD

**Issue by elhananjair** [CloudFire-LLC/cloudfire#1465]
**Describe the bug**
Try to log in through the web, and it shows me 502 Bad Gateway

**To Reproduce**
Updated to the latest Firezone version, 0.7.17, and couldn't log in anymore. I am using the RPM version, not docker. 

**Expected behavior**
Should work as before

**Screenshots / Logs**
![image](https://user-images.githubusercontent.com/69236638/221165984-0d7c3ba8-aa96-4bdc-a4b8-1e1fdd12e6e4.png)

**Platform (please complete the following information):**
 - Firezone Version: 0.7.17
 - OS: Linux
 - Distro: Fedora 35
 - Kernel version: 6.0.12-100
 - Deployment method: from RPM Package

**Additional context**

**Comment by AndrewDryga** [comment]
Hello, can you please share container logs? Most likely there is something wrong with your configuration and the logs would say what exactly is wrong.

**Comment by elhananjair** [comment]
Ok am using the RPM package not a container, and here is Nginx error log
> 2023/02/24 19:41:04 [error] 1620682#0: *802 connect() failed (111: Connection refused) while connecting to upstream, client: 10.3.2.188, server: next.acso.gov.et, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:13000/", host: "next.acso.gov.et:3001"

**Comment by AndrewDryga** [comment]
@elhananjair can you please share firezone (application) logs too?

**Comment by elhananjair** [comment]
Ok sorry: I don't know if this is full but I got this running `firezone-ctl tail`
2023-02-24_15:11:53.81840 Crash dump is being written to: erl_crash.dump...done
2023-02-24_15:11:54.78703 Firezone detected a service crash loop. Taking service down. For support please email support@firezone.dev and include a copy of these crash logs.

> ==> /var/log/firezone/nginx/error.log <==
> 2023/02/24 20:35:09 [error] 1620682#0: *1265 connect() failed (111: Connection refused) while connecting to upstream, client: 104.238.223.15, server: next.acso.gov.et, request: "POST /index.php?do=orgtree&mod=system&op=orgtree HTTP/1.1", upstream: "http://127.0.0.1:13000/index.php?do=orgtree&mod=system&op=orgtree", host: "197.156.101.139:3001"
> 
> ==> /var/log/firezone/nginx/access.log <==
> - - - [2023-02-24T20:35:09+03:00]  "POST /index.php?do=orgtree&mod=system&op=orgtree HTTP/1.1" 502 433 "0.187" 552 "-" "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.2117.157 Safari/537.36"
> 
> ==> /var/log/firezone/nginx/error.log <==
> 2023/02/24 20:35:47 [error] 1620682#0: *1267 connect() failed (111: Connection refused) while connecting to upstream, client: 104.238.223.15, server: next.acso.gov.et, request: "POST /cgi-bin/login.cgi HTTP/1.1", upstream: "http://127.0.0.1:13000/cgi-bin/login.cgi", host: "197.156.101.139:3001", referrer: "https://197.156.101.139:3001"
>

**Comment by AndrewDryga** [comment]
@elhananjair the log we are looking for would be just before the lines you sent, the log is definitely not 2 lines - it should be pretty big.

**Comment by elhananjair** [comment]
ow sorry, yeah its huge
> ==> /var/log/firezone/postgresql/current <==
2023-02-24_15:11:34.25480 2023-02-24 15:11:34.253 GMT [1620768] FATAL:  the database system is shutting down
2023-02-24_15:11:34.25481 2023-02-24 15:11:34.253 GMT [1620764] FATAL:  the database system is shutting down
2023-02-24_15:11:34.25487 2023-02-24 15:11:34.254 GMT [1620772] FATAL:  the database system is shutting down
2023-02-24_15:11:34.25488 2023-02-24 15:11:34.254 GMT [1620763] FATAL:  the database system is shutting down
2023-02-24_15:11:34.28055 2023-02-24 15:11:34.280 GMT [1602577] LOG:  database system is shut down
2023-02-24_15:11:34.38159 2023-02-24 15:11:34.381 GMT [1620773] LOG:  starting PostgreSQL 13.8 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1), 64-bit
2023-02-24_15:11:34.38160 2023-02-24 15:11:34.381 GMT [1620773] LOG:  listening on IPv4 address "127.0.0.1", port 15432
2023-02-24_15:11:34.40875 2023-02-24 15:11:34.408 GMT [1620773] LOG:  listening on Unix socket "/tmp/.s.PGSQL.15432"
2023-02-24_15:11:34.45224 2023-02-24 15:11:34.452 GMT [1620774] LOG:  database system was shut down at 2023-02-24 15:11:34 GMT
2023-02-24_15:11:34.47895 2023-02-24 15:11:34.478 GMT [1620773] LOG:  database system is ready to accept connections

==> /var/log/firezone/nginx/error.log <==
2023/02/24 21:59:39 [error] 1620682#0: *2143 connect() failed (111: Connection refused) while connecting to upstream, client: 104.238.223.15, server: next.acso.gov.et, request: "GET /plugins/editors/jckeditor/plugins/jtreelink/dialogs/links.php?extension=menu&parent="%20UNION%20SELECT%20NULL,NULL,CONCAT_WS(0x203a20,USER(),DATABASE(),VERSION(),0x6e75636c65692d74656d706c617465),NULL,NULL,NULL,NULL,NULL--%20aa&view=menu HTTP/1.1", upstream: "http://127.0.0.1:13000/plugins/editors/jckeditor/plugins/jtreelink/dialogs/links.php?extension=menu&parent="%20UNION%20SELECT%20NULL,NULL,CONCAT_WS(0x203a20,USER(),DATABASE(),VERSION(),0x6e75636c65692d74656d706c617465),NULL,NULL,NULL,NULL,NULL--%20aa&view=menu", host: "197.156.101.139:3001", referrer: "https://197.156.101.139:3001"
2023/02/24 21:59:40 [error] 1620682#0: *2145 connect() failed (111: Connection refused) while connecting to upstream, client: 104.238.223.15, server: next.acso.gov.et, request: "GET /webEdition/showTempFile.php?file=../../../../etc/passwd HTTP/1.1", upstream: "http://127.0.0.1:13000/webEdition/showTempFile.php?file=../../../../etc/passwd", host: "197.156.101.139:3001"
2023/02/24 21:59:43 [error] 1620682#0: *2147 connect() failed (111: Connection refused) while connecting to upstream, client: 104.238.223.15, server: next.acso.gov.et, request: "GET /config/user.xml HTTP/1.1", upstream: "http://127.0.0.1:13000/config/user.xml", host: "197.156.101.139:3001"
2023/02/24 21:59:50 [error] 1620682#0: *2149 connect() failed (111: Connection refused) while connecting to upstream, client: 104.238.223.15, server: next.acso.gov.et, request: "GET /fw.login.php?apikey=%27UNION%20select%201,%27YToyOntzOjM6InVpZCI7czo0OiItMTAwIjtzOjIyOiJBQ1RJVkVfRElSRUNUT1JZX0lOREVYIjtzOjE6IjEiO30=%27 HTTP/1.1", upstream: "http://127.0.0.1:13000/fw.login.php?apikey=%27UNION%20select%201,%27YToyOntzOjM6InVpZCI7czo0OiItMTAwIjtzOjIyOiJBQ1RJVkVfRElSRUNUT1JZX0lOREVYIjtzOjE6IjEiO30=%27", host: "197.156.101.139:3001"
2023/02/24 21:59:58 [error] 1620682#0: *2151 connect() failed (111: Connection refused) while connecting to upstream, client: 104.238.223.15, server: next.acso.gov.et, request: "GET /firebase-debug.log HTTP/1.1", upstream: "http://127.0.0.1:13000/firebase-debug.log", host: "197.156.101.139:3001"
2023/02/24 22:00:49 [error] 1620682#0: *2153 connect() failed (111: Connection refused) while connecting to upstream, client: 104.238.223.15, server: next.acso.gov.et, request: "GET /webGui/images/green-on.png/?path=x&site[x][text]=%3C?php%20phpinfo()%20?%3E HTTP/1.1", upstream: "http://127.0.0.1:13000/webGui/images/green-on.png/?path=x&site[x][text]=%3C?php%20phpinfo()%20?%3E", host: "197.156.101.139:3001"
2023/02/24 22:01:18 [error] 1620682#0: *2155 connect() failed (111: Connection refused) while connecting to upstream, client: 104.238.223.15, server: next.acso.gov.et, request: "GET /?rsd=%3C%2Fscript%3E%3Cscript%3Ealert%28document.domain%29%3C%2Fscript%3E HTTP/1.1", upstream: "http://127.0.0.1:13000/?rsd=%3C%2Fscript%3E%3Cscript%3Ealert%28document.domain%29%3C%2Fscript%3E", host: "197.156.101.139:3001"
2023/02/24 22:01:20 [error] 1620682#0: *2157 connect() failed (111: Connection refused) while connecting to upstream, client: 104.238.223.15, server: next.acso.gov.et, request: "GET /dashboardUser HTTP/1.1", upstream: "http://127.0.0.1:13000/dashboardUser", host: "197.156.101.139:3001"
2023/02/24 22:01:22 [error] 1620682#0: *2159 connect() failed (111: Connection refused) while connecting to upstream, client: 104.238.223.15, server: next.acso.gov.et, request: "GET /repos?visibility=public HTTP/1.1", upstream: "http://127.0.0.1:13000/repos?visibility=public", host: "197.156.101.139:3001"
2023/02/24 22:01:25 [error] 1620682#0: *2161 connect() failed (111: Connection refused) while connecting to upstream, client: 104.238.223.15, server: next.acso.gov.et, request: "GET /bitbucket/repos?visibility=public HTTP/1.1", upstream: "http://127.0.0.1:13000/bitbucket/repos?visibility=public", host: "197.156.101.139:3001"

==> /var/log/firezone/nginx/access.log <==
- - - [2023-02-24T21:59:39+03:00]  "GET /plugins/editors/jckeditor/plugins/jtreelink/dialogs/links.php?extension=menu&parent=\x22%20UNION%20SELECT%20NULL,NULL,CONCAT_WS(0x203a20,USER(),DATABASE(),VERSION(),0x6e75636c65692d74656d706c617465),NULL,NULL,NULL,NULL,NULL--%20aa&view=menu HTTP/1.1" 502 497 "0.001" 552 "https://197.156.101.139:3001" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.47 Safari/537.36"
- - - [2023-02-24T21:59:40+03:00]  "GET /webEdition/showTempFile.php?file=../../../../etc/passwd HTTP/1.1" 502 294 "0.000" 552 "-" "Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
- - - [2023-02-24T21:59:43+03:00]  "GET /config/user.xml HTTP/1.1" 502 261 "0.000" 552 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
- - - [2023-02-24T21:59:50+03:00]  "GET /fw.login.php?apikey=%27UNION%20select%201,%27YToyOntzOjM6InVpZCI7czo0OiItMTAwIjtzOjIyOiJBQ1RJVkVfRElSRUNUT1JZX0lOREVYIjtzOjE6IjEiO30=%27 HTTP/1.1" 502 392 "0.000" 552 "-" "Mozilla/5.0 (X11; Ubuntu; Linux i686 on x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2820.59 Safari/537.36"
- - - [2023-02-24T21:59:58+03:00]  "GET /firebase-debug.log HTTP/1.1" 502 256 "0.000" 552 "-" "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.3319.102 Safari/537.36"
- - - [2023-02-24T22:00:49+03:00]  "GET /webGui/images/green-on.png/?path=x&site[x][text]=%3C?php%20phpinfo()%20?%3E HTTP/1.1" 502 329 "0.001" 552 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1944.0 Safari/537.36"
- - - [2023-02-24T22:01:18+03:00]  "GET /?rsd=%3C%2Fscript%3E%3Cscript%3Ealert%28document.domain%29%3C%2Fscript%3E HTTP/1.1" 502 328 "0.000" 552 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2656.18 Safari/537.36"
- - - [2023-02-24T22:01:20+03:00]  "GET /dashboardUser HTTP/1.1" 502 366 "0.001" 552 "-" "Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.3319.102 Safari/537.36"
- - - [2023-02-24T22:01:22+03:00]  "GET /repos?visibility=public HTTP/1.1" 502 269 "0.000" 552 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
- - - [2023-02-24T22:01:25+03:00]  "GET /bitbucket/repos?visibility=public HTTP/1.1" 502 276 "0.000" 552 "-" "Mozilla/5.0 (Windows NT 6.4; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2225.0 Safari/537.36"

==> /var/log/firezone/nginx/current <==

==> /var/log/firezone/wireguard/current <==
2023-02-24_18:58:30.59616 [Fri Feb 24 21:56:18 2023] wireguard: wg-firezone: Receiving keepalive packet from peer 22 (196.188.179.147:29249)
2023-02-24_18:58:30.59616 [Fri Feb 24 21:56:33 2023] wireguard: wg-firezone: Receiving keepalive packet from peer 22 (196.188.179.147:29249)
2023-02-24_18:58:30.59619 [Fri Feb 24 21:57:03 2023] wireguard: wg-firezone: Receiving keepalive packet from peer 22 (196.188.179.147:29249)
2023-02-24_18:58:30.59619 [Fri Feb 24 21:57:33 2023] wireguard: wg-firezone: Receiving keepalive packet from peer 22 (196.188.179.147:29249)
2023-02-24_18:58:30.59619 [Fri Feb 24 21:58:04 2023] wireguard: wg-firezone: Receiving keepalive packet from peer 22 (196.188.179.147:29249)
2023-02-24_18:58:30.59620 [Fri Feb 24 21:58:18 2023] wireguard: wg-firezone: Receiving handshake initiation from peer 22 (196.188.179.147:29249)
2023-02-24_18:58:30.59620 [Fri Feb 24 21:58:18 2023] wireguard: wg-firezone: Sending handshake response to peer 22 (196.188.179.147:29249)
2023-02-24_18:58:30.59621 [Fri Feb 24 21:58:18 2023] wireguard: wg-firezone: Keypair 3384 destroyed for peer 22
2023-02-24_18:58:30.59622 [Fri Feb 24 21:58:18 2023] wireguard: wg-firezone: Keypair 3386 created for peer 22
2023-02-24_18:58:30.59622 [Fri Feb 24 21:58:18 2023] wireguard: wg-firezone: Receiving keepalive packet from peer 22 (196.188.179.147:29249)

==> /var/log/firezone/phoenix/current <==
2023-02-24_15:11:52.29447             (ecto 3.9.4) lib/ecto/repo/supervisor.ex:160: Ecto.Repo.Supervisor.tuplet/2
2023-02-24_15:11:52.29447             (fz_http 0.7.17) lib/fz_http/repo.ex:2: FzHttp.Repo.one!/2
2023-02-24_15:11:52.29447             (fz_http 0.7.17) lib/fz_http/config.ex:96: FzHttp.Config.validate_runtime_config!/0
2023-02-24_15:11:52.29448             (fz_http 0.7.17) lib/fz_http/application.ex:12: FzHttp.Application.start/2
2023-02-24_15:11:52.29448             (kernel 8.5) application_master.erl:293: :application_master.start_it_old/4
2023-02-24_15:11:53.81207 {"Kernel pid terminated",application_controller,"{application_start_failure,fz_http,{bad_return,{{'Elixir.FzHttp.Application',start,[normal,[]]},{'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<\"could not lookup Ecto repo FzHttp.Repo because it was not started or it does not exist\">>},[{'Elixir.Ecto.Repo.Registry',lookup,1,[{file,\"lib/ecto/repo/registry.ex\"},{line,22},{error_info,#{module => 'Elixir.Exception'}}]},{'Elixir.Ecto.Repo.Supervisor',tuplet,2,[{file,\"lib/ecto/repo/supervisor.ex\"},{line,160}]},{'Elixir.FzHttp.Repo','one!',2,[{file,\"lib/fz_http/repo.ex\"},{line,2}]},{'Elixir.FzHttp.Config','validate_runtime_config!',0,[{file,\"lib/fz_http/config.ex\"},{line,96}]},{'Elixir.FzHttp.Application',start,2,[{file,\"lib/fz_http/application.ex\"},{line,12}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,293}]}]}}}}}"}
2023-02-24_15:11:53.81637 Kernel pid terminated (application_controller) ({application_start_failure,fz_http,{bad_return,{{'Elixir.FzHttp.Application',start,[normal,[]]},{'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"could not lookup Ecto repo FzHttp.Repo because it was not started or it does not exist">>},[{'Elixir.Ecto.Repo.Registry',lookup,1,[{file,"lib/ecto/repo/registry.ex"},{line,22},{error_info,#{module => 'Elixir.Exception'}}]},{'Elixir.Ecto.Repo.Supervisor',tuplet,2,[{file,"lib/ecto/repo/supervisor.ex"},{line,160}]},{'Elixir.FzHttp.Repo','one!',2,[{file,"lib/fz_http/repo.ex"},{line,2}]},{'Elixir.FzHttp.Config','validate_runtime_config!',0,[{file,"lib/fz_http/config.ex"},{line,96}]},{'Elixir.FzHttp.Application',start,2,[{file,"lib/fz_http/application.ex"},{line,12}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,293}]}]}}}}})
2023-02-24_15:11:53.81839 
2023-02-24_15:11:53.81840 Crash dump is being written to: erl_crash.dump...done
2023-02-24_15:11:54.78703 Firezone detected a service crash loop. Taking service down. For support please email support@firezone.dev and include a copy of these crash logs.

**Comment by AndrewDryga** [comment]
From the logs it looks the issue is that your database is either not started or your configuration variables to access it are invalid

**Comment by elhananjair** [comment]
actually, the database is running:
> run: postgresql: (pid 1620773) 75445s; run: log: (pid 994) 941741s

I haven't touched anything after an update, I am using ansible to update my system daily, it executes firezone-ctl reconfigure after updating firezone.

**Comment by AndrewDryga** [comment]
@elhananjair please check your database configuration, it's possible that DB connection params are not picked up (look for typos in environment variable names), also check your `/var/log/firezone/phoenix/current` for more information about the DB connection, there should be log explaining why database connection can not be started.

**Comment by jamilbk** [comment]
@elhananjair like @AndrewDryga mentioned -- we'll need a bit more context to debug. Try doing `sudo firezone-ctl tail phoenix`, and while that's running and displaying logs, do a `sudo firezone-ctl restart phoenix`. That should show where the crash is occurring. Please post the full backtrace from the `tail` command after the point at which you `restart` the service.

One hunch is that perhaps you had multiple MFA methods with the same name -- this was fixed recently and may cause startup issues on a very select number of instances. You can see if you have duplicate MFA method names with the following query:

```
/opt/firezone/embedded/bin/psql -U firezone -d firezone -h 127.0.0.0 -p 15432 -c "SELECT name FROM mfa_methods"
```

**Comment by elhananjair** [comment]
Hello @jamilbk @AndrewDryga 
Sorry, I didn't reply soon, I stopped using firezone on our production server for a while since our system was down because of this issue. Still, we have a clone of the production server and recently after an upgrade to 0.7.20, this got fixed and now I can log in and the system is accessible too. Thank you
