### ISSUE TITLE
Upgrade from 0.7.13 -> 0.7.17 - could not create unique index "mfa_methods_name_index"

### ISSUE THREAD

**Issue by andreaskasa** [CloudFire-LLC/cloudfire#1466]
**Describe the bug**
After i updated 2 docker instances of firezone, they both keep restarting

**Screenshots / Logs**

Ubuntu
```13:06:26.198 erl_level=info application=ecto_sql domain=elixir file=lib/ecto/migration/runner.ex function=log/3 line=338 mfa=Ecto.Migration.Runner.log/3 module=Ecto.Migration.Runner pid=<0.194.0> [info] == Running 20230116200524 FzHttp.Repo.Migrations.AddNotNullToMfaMethods.change/0 forward
13:06:26.215 erl_level=info application=ecto_sql domain=elixir file=lib/ecto/migration/runner.ex function=log/3 line=338 mfa=Ecto.Migration.Runner.log/3 module=Ecto.Migration.Runner pid=<0.194.0> [info] execute "UPDATE mfa_methods\nSET last_used_at = '1970-01-01 00:00:00+00'::timestamptz\nWHERE last_used_at IS NULL\n"
13:06:26.218 erl_level=info application=ecto_sql domain=elixir file=lib/ecto/migration/runner.ex function=log/3 line=338 mfa=Ecto.Migration.Runner.log/3 module=Ecto.Migration.Runner pid=<0.194.0> [info] execute "UPDATE mfa_methods\nSET payload = 'ebBNfXi6GYuyNXFEK737YSHF/Od752OZ28xPnfj2CzA='\nWHERE payload IS NULL\n"
13:06:26.219 erl_level=info application=ecto_sql domain=elixir file=lib/ecto/migration/runner.ex function=log/3 line=338 mfa=Ecto.Migration.Runner.log/3 module=Ecto.Migration.Runner pid=<0.194.0> [info] alter table mfa_methods
13:06:26.254 erl_level=info application=ecto_sql domain=elixir file=lib/ecto/migration/runner.ex function=log/3 line=338 mfa=Ecto.Migration.Runner.log/3 module=Ecto.Migration.Runner pid=<0.194.0> [info] create index mfa_methods_name_index
** (Postgrex.Error) ERROR 23505 (unique_violation) could not create unique index "mfa_methods_name_index"

    table: mfa_methods
    constraint: mfa_methods_name_index

Key (name)=(WorkZONE WG) is duplicated.
    (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.14.3) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:1005: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.9.2) lib/ecto/migration/runner.ex:326: Ecto.Migration.Runner.log_and_execute_ddl/3
    (ecto_sql 3.9.2) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
    (elixir 1.14.3) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql 3.9.2) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
    nofile:1: (file)
```
Centos

```13:00:39.225 erl_level=info application=ecto_sql domain=elixir file=lib/ecto/migration/runner.ex function=log/3 line=338 mfa=Ecto.Migration.Runner.log/3 module=Ecto.Migration.Runner pid=<0.194.0> [info] == Running 20230116200524 FzHttp.Repo.Migrations.AddNotNullToMfaMethods.change/0 forward
13:00:39.233 erl_level=info application=ecto_sql domain=elixir file=lib/ecto/migration/runner.ex function=log/3 line=338 mfa=Ecto.Migration.Runner.log/3 module=Ecto.Migration.Runner pid=<0.194.0> [info] execute "UPDATE mfa_methods\nSET last_used_at = '1970-01-01 00:00:00+00'::timestamptz\nWHERE last_used_at IS NULL\n"
13:00:39.237 erl_level=info application=ecto_sql domain=elixir file=lib/ecto/migration/runner.ex function=log/3 line=338 mfa=Ecto.Migration.Runner.log/3 module=Ecto.Migration.Runner pid=<0.194.0> [info] execute "UPDATE mfa_methods\nSET payload = '8R47f6Ahq0TA/0/CadcbcgJ8KiZie+hSNLLUErh3Fcw='\nWHERE payload IS NULL\n"
13:00:39.237 erl_level=info application=ecto_sql domain=elixir file=lib/ecto/migration/runner.ex function=log/3 line=338 mfa=Ecto.Migration.Runner.log/3 module=Ecto.Migration.Runner pid=<0.194.0> [info] alter table mfa_methods
13:00:39.244 erl_level=info application=ecto_sql domain=elixir file=lib/ecto/migration/runner.ex function=log/3 line=338 mfa=Ecto.Migration.Runner.log/3 module=Ecto.Migration.Runner pid=<0.194.0> [info] create index mfa_methods_name_index
 ** (Postgrex.Error) ERROR 23505 (unique_violation) could not create unique index "mfa_methods_name_index"

    table: mfa_methods
    constraint: mfa_methods_name_index

Key (name)=(HomeZONE WG) is duplicated.
    (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.14.3) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:1005: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.9.2) lib/ecto/migration/runner.ex:326: Ecto.Migration.Runner.log_and_execute_ddl/3
    (ecto_sql 3.9.2) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
    (elixir 1.14.3) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto_sql 3.9.2) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
    nofile:1: (file)
```

**Platform (please complete the following information):**
 - Firezone Version 0.7.17
 - OS: Linux
 - Distro: Ubuntu 22.04.2 LTS/Centos 7.9
 - Kernel version: 5.15.0-60/6.0.11-1
 - Deployment method: Docker

**Comment by AndrewDryga** [comment]
Hey @andreaskasa, this is because you have duplicate MFA names in your database and Firezone doesn't allow them anymore. For example, you can resolve it by renaming directly in the database:
```
psql -d firezone -h 127.0.0.1 -U postgres -c "UPDATE mfa_methods SET name = 'HomeZONE WG 2' WHERE name = 'HomeZONE WG'"
```
(and repeat it for other non-unique names)

**Comment by andreaskasa** [comment]
Hey @AndrewDryga, with 

```
psql -d firezone -h 127.0.0.1 -U postgres -c "SELECT * FROM mfa_methods WHERE name = 'WorkZONE WG';"
```

and then
```
psql -d firezone -h 127.0.0.1 -U postgres -c "UPDATE mfa_methods SET name = 'WorkZONE WG 2' WHERE id = '0f938b98-16d8-4a0f-9508-e553a71f5f02';"
```
I could fix the first problem

Then I had to delete the extra spaces in the CVS lists in the device table in the column allowed_ips with
```
psql -d firezone -h 127.0.0.1 -U postgres -c "UPDATE devices SET allowed_ips = 'hidden/24,hidden/24,hidden/16' WHERE allowed_ips = 'hidden/24, hidden/24, hidden/16';"
```

Now everything works again.

Thx Andreas
