### ISSUE TITLE
Internal Server Error when trying to add a device again

### ISSUE THREAD

**Issue by lion9453** [CloudFire-LLC/cloudfire#1482]
**Describe the bug**
Although the issue with not being able to bring up the "Add Device" window was fixed in https://github.com/firezone/firezone/issues/1477, there is now a new issue where clicking the "Generate Configuration" button results in an Internal Server Error.

The error message is:
```
02:34:29.966 erl_level=error domain=otp file=gen_server.erl function=error_info/8 line=1402 mfa=:gen_server.error_info/8 module=gen_server pid=<0.1131.0> [error] GenServer #PID<0.1131.0> terminating
** (FunctionClauseError) no function clause matching in String.graphemes/1
    (elixir 1.14.3) lib/string.ex:1902: String.graphemes(%FzHttp.Types.IPPort{type: :ipv4, address: {35, 35, 35, 35}, port: nil})
    (fz_http 0.7.19) lib/fz_http/devices.ex:288: FzHttp.Devices.maybe_add_port/1
    (fz_http 0.7.19) lib/fz_http/devices.ex:280: FzHttp.Devices.endpoint_config/2
    (fz_http 0.7.19) lib/fz_http/devices.ex:202: FzHttp.Devices.as_config/1
    (fz_http 0.7.19) lib/fz_http_web/live/device_live/unprivileged/show_live.ex:66: FzHttpWeb.DeviceLive.Unprivileged.Show.assigns/1
    (fz_http 0.7.19) lib/fz_http_web/live/device_live/unprivileged/show_live.ex:17: FzHttpWeb.DeviceLive.Unprivileged.Show.mount/3
    (phoenix_live_view 0.18.11) lib/phoenix_live_view/utils.ex:335: anonymous fn/6 in Phoenix.LiveView.Utils.maybe_call_live_view_mount!/5
    (telemetry 1.2.1) /app/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
```

Clicking on an already existing device also results in an Internal Server Error.
The error message is:
```
Request: GET /devices/33c3c6ca-00f8-46ce-aef1-d0d20d123152
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in String.graphemes/1
        (elixir 1.14.3) lib/string.ex:1902: String.graphemes(%FzHttp.Types.IPPort{type: :ipv4, address: {35, 35, 35, 35}, port: nil})
        (fz_http 0.7.19) lib/fz_http/devices.ex:288: FzHttp.Devices.maybe_add_port/1
        (fz_http 0.7.19) lib/fz_http/devices.ex:280: FzHttp.Devices.endpoint_config/2
        (fz_http 0.7.19) lib/fz_http/devices.ex:202: FzHttp.Devices.as_config/1
        (fz_http 0.7.19) lib/fz_http_web/live/device_live/admin/show_live.ex:59: FzHttpWeb.DeviceLive.Admin.Show.assigns/1
        (fz_http 0.7.19) lib/fz_http_web/live/device_live/admin/show_live.ex:15: FzHttpWeb.DeviceLive.Admin.Show.mount/3
        (phoenix_live_view 0.18.11) lib/phoenix_live_view/utils.ex:335: anonymous fn/6 in Phoenix.LiveView.Utils.maybe_call_live_view_mount!/5
        (telemetry 1.2.1) /app/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
```

```
02:58:51.391 erl_level=error application=phoenix domain=elixir file=lib/phoenix/channel/server.ex function=join/4 line=43 mfa=Phoenix.Channel.Server.join/4 module=Phoenix.Channel.Server pid=<0.3464.0> [error] an exception was raised:
    ** (FunctionClauseError) no function clause matching in String.graphemes/1
        (elixir 1.14.3) lib/string.ex:1902: String.graphemes(%FzHttp.Types.IPPort{type: :ipv4, address: {35, 35, 35, 35}, port: nil})
        (fz_http 0.7.19) lib/fz_http/devices.ex:288: FzHttp.Devices.maybe_add_port/1
        (fz_http 0.7.19) lib/fz_http/devices.ex:280: FzHttp.Devices.endpoint_config/2
        (fz_http 0.7.19) lib/fz_http/devices.ex:202: FzHttp.Devices.as_config/1
        (fz_http 0.7.19) lib/fz_http_web/live/device_live/unprivileged/show_live.ex:66: FzHttpWeb.DeviceLive.Unprivileged.Show.assigns/1
        (fz_http 0.7.19) lib/fz_http_web/live/device_live/unprivileged/show_live.ex:17: FzHttpWeb.DeviceLive.Unprivileged.Show.mount/3
        (phoenix_live_view 0.18.11) lib/phoenix_live_view/utils.ex:335: anonymous fn/6 in Phoenix.LiveView.Utils.maybe_call_live_view_mount!/5
        (telemetry 1.2.1) /app/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
```

Please check for possible causes of FzHttp.Types.IPPort errors.

**To Reproduce**

1. Click on "Add device".
2. Click on "Generate Configuration". This will result in an Internal Server Error.

Alternatively, clicking on an already existing device also results in an Internal Server Error.

**Expected behavior**

Click on the "Add Device" button.
Observe that the page displays an "Internal Server Error" message.

**Screenshots / Logs**
None

**Platform (please complete the following information):**
Firezone 0.7.19
OS: Debian
Distro: Debian 11
Kernel version: 5.10.0
Deployment method: Docker

**Additional context**
None

**Comment by AndrewDryga** [comment]
Resolved in the latest release, please give it a try and tell if there are any other issues.

**Comment by lion9453** [comment]
Thank you Firezone team for the quick bug fix. The issue has been resolved now. 👍
