### ISSUE TITLE
Lack of documentation on WIREGUARD_IPV4_NETWORK

### ISSUE THREAD

**Issue by alexqrid** [CloudFire-LLC/cloudfire#1505]
**First of all, thank you for a great job you're doing!**

**Describe the bug**
Not seems like a bug, but confuses users and takes a few time to debug.
I've been trying to setup docker compose version of `v0.7.22` and setup all needed environment
variables,as well as `WIREGUARD_IPV4_NETWORK=172.25.0.0/24`, `WIREGUARD_IPV4_ADDRESS=172.25.0.100`.
My docker network subnet was allocated at `172.25.0.0/24`.
While running migrations I received the same errors described [here](https://discourse.firez.one/t/firezone-postgres-failed-to-migrate-database/417) and couldn't understand why this was happening.  
I'd started another container in the same network and successfully connected to the `postgres`.
Then ran the `shell` in `firezone` container, installed `psql` and successfully connected to the `postgres`, but running the `/app/bin/migrate` script was still resulted in connection error.
<details><summary>error.log</summary>

```sh
21:11:25.379 erl_level=error application=db_connection domain=elixir file=lib/db_connection/connection.ex function=connect/2 line=103 mfa=DBConnection.Connection.connect/2 module=DBConnection.Connection pid=<0.163.0> [error] Postgrex.Protocol (#PID<0.163.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect (postgres:5432): host is unreachable - :ehostunreach
21:11:25.379 erl_level=error application=db_connection domain=elixir file=lib/db_connection/connection.ex function=connect/2 line=103 mfa=DBConnection.Connection.connect/2 module=DBConnection.Connection pid=<0.164.0> [error] Postgrex.Protocol (#PID<0.164.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect (postgres:5432): host is unreachable - :ehostunreach
21:11:25.401 erl_level=error application=ecto_sql domain=elixir file=lib/ecto/migrator.ex function=verbose_schema_migration/3 line=680 mfa=Ecto.Migrator.verbose_schema_migration/3 module=Ecto.Migrator pid=<0.96.0> [error] Could not create schema migrations table. This error usually happens due to the following:

  * The database does not exist
  * The "schema_migrations" table, which Ecto uses for managing
    migrations, was defined by another library
  * There is a deadlock while migrating (such as using concurrent
    indexes with a migration_lock)

To fix the first issue, run "mix ecto.create".

To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create". Alternatively you may configure Ecto to use
another table and/or repository for managing migrations:

    config :fz_http, FzHttp.Repo,
      migration_source: "some_other_table_for_schema_migrations",
      migration_repo: AnotherRepoForSchemaMigrations

The full error report is shown below.

** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2959ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:

  1. Ensuring your database is available and that you can connect to it
  2. Tracking down slow queries and making sure they are running fast enough
  3. Increasing the pool_size (although this increases resource consumption)
  4. Allowing requests to wait longer by increasing :queue_target and :queue_interval

See DBConnection.start_link/2 for more information

    (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.14.3) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:1005: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.9.2) lib/ecto/migrator.ex:677: Ecto.Migrator.verbose_schema_migration/3
    (ecto_sql 3.9.2) lib/ecto/migrator.ex:491: Ecto.Migrator.lock_for_migrations/4
    (ecto_sql 3.9.2) lib/ecto/migrator.ex:403: Ecto.Migrator.run/4
    (ecto_sql 3.9.2) lib/ecto/migrator.ex:146: Ecto.Migrator.with_repo/3
    nofile:1: (file)
```
</details>
After looking through the `/app/bin/bootstrap`, which is used by `/app/bin/migrate` I've noticed that the wireguard network is established there.
After executing /app/bin/bootstrap manually, the connection to the `postgres` server became broken. I've looked through my `ifconfig` and noticed that the networks are overlapping.

<details><summary>ifconfig</summary>

```sh
/app/bin # ifconfig 
eth0      Link encap:Ethernet  HWaddr 02:42:AC:19:00:64  
          inet addr:172.25.0.100  Bcast:172.25.255.255  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:290 errors:0 dropped:0 overruns:0 frame:0
          TX packets:151 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:3773062 (3.5 MiB)  TX bytes:11568 (11.2 KiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:56 errors:0 dropped:0 overruns:0 frame:0
          TX packets:56 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:4278 (4.1 KiB)  TX bytes:4278 (4.1 KiB)

wg-firezone Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          inet addr:172.25.0.100  P-t-P:172.25.0.100  Mask:255.255.255.255
          UP POINTOPOINT RUNNING NOARP  MTU:1280  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:22 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```
</details>

This was the reason of the errors!

### I suggest to add the information to the docs that `WIREGUARD_IPV4_NETWORK` shouldn't overlap with the docker network subnet, this would save pretty time to others.

**Expected behavior**
Migration works without problems out of the box.

**Platform (please complete the following information):**
 - 0.7.22
 - OS: Linux
 - Distro: Debian 11
 - Deployment method: Docker

**Comment by AndrewDryga** [comment]
Hello @alexqrid, we removed those environment variables from the documentation and deprecated them for exactly this purpose - they cause a lot of confusion for the users and increase our maintenance cost for no good reason. 

`WIREGUARD_IPV*_*` and others will stop working in future versions so I recommend you stop using it and use the default CGNET network range instead.
