### ISSUE TITLE
Error upon adding device

### ISSUE THREAD

**Issue by moan0s** [CloudFire-LLC/cloudfire#1526]
**Describe the bug**
Trying to add a device fails

**To Reproduce**
* Install with https://github.com/moan0s/role-firezone (I can share details if needed)
* Login
* got to User -> Add device -> fill in name -> click` Generate configuration`

-> Fails and reshows "Add device form"

**Expected behavior**
A configuration is shown.

**Screenshots / Logs**
Log
```
Mar 23 12:39:24 s3 mash-firezone[201349]: 12:39:24.802 erl_level=info application=phoenix domain=elixir file=lib/phoenix/logger.ex function=phoenix_endpoint_start/4 line=217 mfa=Phoenix.Logger.phoenix_endpoint_start/4 module=Phoenix.Logger pid=<0.605.0> request_id=F08Mtq-XMwcA2UQAAAUR [info] GET /favicon.ico
Mar 23 12:39:24 s3 mash-firezone[201349]: 12:39:24.802 erl_level=info application=phoenix domain=elixir file=lib/phoenix/logger.ex function=phoenix_endpoint_stop/4 line=231 mfa=Phoenix.Logger.phoenix_endpoint_stop/4 module=Phoenix.Logger pid=<0.605.0> request_id=F08Mtq-XMwcA2UQAAAUR [info] Sent 404 in 350µs
Mar 23 12:39:30 s3 mash-firezone[201349]: 12:39:30.161 erl_level=error domain=otp file=gen_server.erl function=error_info/8 line=1402 mfa=:gen_server.error_info/8 module=gen_server pid=<0.602.0> [error] GenServer #PID<0.602.0> terminating
Mar 23 12:39:30 s3 mash-firezone[201349]: ** (stop) {:badarg, {'aead.c', 90}, 'Unknown cipher or invalid key size'}
Mar 23 12:39:30 s3 mash-firezone[201349]:     (crypto 5.1.2) crypto.erl:985: :crypto.crypto_one_time_aead(:aes_256_gcm, "$6$rounds=655555$fz.db.ec.key$RmnCH6bgzxl4xFCBzOE3uhj7idRhSpHD9Xkn20U9tv4ZyL3hKrKwCV5j2ETwq1dC1tFj0Ri224iEacfS0oLvf0", <<130, 20, 27, 155, 128, 27, 99, 249, 85, 90, 225, 152>>, "XCg6GjyTCqyI64yRRBDkZxdL2Ao8qx+XGpDHcoT0aGo=", "AES256GCM", 16, true)
Mar 23 12:39:30 s3 mash-firezone[201349]:     (cloak 1.1.2) lib/cloak/ciphers/aes_gcm.ex:47: Cloak.Ciphers.AES.GCM.encrypt/2
Mar 23 12:39:30 s3 mash-firezone[201349]:     (fz_http 0.7.23) lib/cloak_ecto/type.ex:37: FzHttp.Encrypted.Binary.dump/1
Mar 23 12:39:30 s3 mash-firezone[201349]:     (ecto 3.9.4) lib/ecto/type.ex:941: Ecto.Type.process_dumpers/3
Mar 23 12:39:30 s3 mash-firezone[201349]:     (ecto 3.9.4) lib/ecto/repo/schema.ex:1006: Ecto.Repo.Schema.dump_field!/6
Mar 23 12:39:30 s3 mash-firezone[201349]:     (ecto 3.9.4) lib/ecto/repo/schema.ex:1019: anonymous fn/6 in Ecto.Repo.Schema.dump_fields!/5
Mar 23 12:39:30 s3 mash-firezone[201349]:     (stdlib 4.2) maps.erl:411: :maps.fold_1/3
Mar 23 12:39:30 s3 mash-firezone[201349]:     (ecto 3.9.4) lib/ecto/repo/schema.ex:1017: Ecto.Repo.Schema.dump_fields!/5
Mar 23 12:39:30 s3 mash-firezone[201349]: Last message: %Phoenix.Socket.Message{topic: "lv:phx-F08Mnj3ujDpO6ANx", event: "event", payload: %{"cid" => 3, "event" => "save", "type" => "form", "value" => "device%5Bpublic_key%5D=wvxFRnyT5ZxkvHM4720NqtjUlEK9dVtyF%2BXRWUhBIlY%3D&device%5Bpreshared_key%5D=&device%5Bname%5D=falcon&device%5Bdescription%5D=dada&device%5Buse_default_allowed_ips%5D=true&device%5Buse_default_dns%5D=true&device%5Buse_default_endpoint%5D=true&device%5Buse_default_mtu%5D=false&device%5Bmtu%5D=&device%5Buse_default_persistent_keepalive%5D=true&device%5Bipv4%5D=&device%5Bipv6%5D="}, ref: "41", join_ref: "39"}
Mar 23 12:39:41 s3 mash-firezone[201349]: 12:39:41.151 erl_level=error domain=otp file=gen_server.erl function=error_info/8 line=1402 mfa=:gen_server.error_info/8 module=gen_server pid=<0.606.0> [error] GenServer #PID<0.606.0> terminating
Mar 23 12:39:41 s3 mash-firezone[201349]: ** (stop) {:badarg, {'aead.c', 90}, 'Unknown cipher or invalid key size'}
Mar 23 12:39:41 s3 mash-firezone[201349]:     (crypto 5.1.2) crypto.erl:985: :crypto.crypto_one_time_aead(:aes_256_gcm, "$6$rounds=655555$fz.db.ec.key$RmnCH6bgzxl4xFCBzOE3uhj7idRhSpHD9Xkn20U9tv4ZyL3hKrKwCV5j2ETwq1dC1tFj0Ri224iEacfS0oLvf0", <<254, 185, 251, 126, 204, 89, 91, 29, 26, 144, 73, 215>>, "mPBVmGIHbB8L1uemPBVmGIHbB8L1ue4JdiqkzHQa90jiTTLJgjshn6QgHU4JdiqkzHQa90jiTTLJgjshn6QgHU=", "AES256GCM", 16, true)
Mar 23 12:39:41 s3 mash-firezone[201349]:     (cloak 1.1.2) lib/cloak/ciphers/aes_gcm.ex:47: Cloak.Ciphers.AES.GCM.encrypt/2
Mar 23 12:39:41 s3 mash-firezone[201349]:     (fz_http 0.7.23) lib/cloak_ecto/type.ex:37: FzHttp.Encrypted.Binary.dump/1
Mar 23 12:39:41 s3 mash-firezone[201349]:     (ecto 3.9.4) lib/ecto/type.ex:941: Ecto.Type.process_dumpers/3
Mar 23 12:39:41 s3 mash-firezone[201349]:     (ecto 3.9.4) lib/ecto/repo/schema.ex:1006: Ecto.Repo.Schema.dump_field!/6
Mar 23 12:39:41 s3 mash-firezone[201349]:     (ecto 3.9.4) lib/ecto/repo/schema.ex:1019: anonymous fn/6 in Ecto.Repo.Schema.dump_fields!/5
Mar 23 12:39:41 s3 mash-firezone[201349]:     (stdlib 4.2) maps.erl:411: :maps.fold_1/3
Mar 23 12:39:41 s3 mash-firezone[201349]:     (ecto 3.9.4) lib/ecto/repo/schema.ex:1017: Ecto.Repo.Schema.dump_fields!/5
Mar 23 12:39:41 s3 mash-firezone[201349]: Last message: %Phoenix.Socket.Message{topic: "lv:phx-F0xxxxj3ujDpO6ANx", event: "event", payload: %{"cid" => 3, "event" => "save", "type" => "form", "value" => "device%5Bpublic_key%5D=wvxFRnyT5ZxkvHM4720NqtjUlEK9dVtyF%2BXRWUhBIlY%3D&device%5Bpreshared_key%5D=&device%5Bname%5D=dodo&device%5Bdescription%5D=dada&device%5Buse_default_allowed_ips%5D=true&device%5Buse_default_dns%5D=true&device%5Buse_default_endpoint%5D=true&device%5Buse_default_mtu%5D=false&device%5Bmtu%5D=&device%5Buse_default_persistent_keepalive%5D=true&device%5Bipv4%5D=&device%5Bipv6%5D="}, ref: "45", join_ref: "42"}
```

**Platform:**
 - Firezone Version 0.7.23
 - OS: Linux
 - Distro:  Ubuntu 20.04
 - Deployment method: Docker via ansible

**Additional context**
Maybe related to #1014

**Comment by moan0s** [comment]
Same upon adding a MFA device

**Comment by moan0s** [comment]
Maybe it has to do with the following secrets?
```
GUARDIAN_SECRET_KEY=
DATABASE_ENCRYPTION_KEY===
SECRET_KEY_BASE=
LIVE_VIEW_SIGNING_SALT=
COOKIE_SIGNING_SALT=
COOKIE_ENCRYPTION_SALT=
```

They are all base64 encoded and have a length  ~90. Maybe that is to much and there are undocumented restrictions?

**Comment by AndrewDryga** [comment]
Hey @moan0s, this is most likely because of `DATABASE_ENCRYPTION_KEY` value. We don't have control over they key length and can't even validate it because the actual crypto operations are handled by libcrypto installed on your host (most likely it's OpenSSL): https://www.erlang.org/doc/man/crypto_app.html#dependencies.

A recommended way to generate it is:
```
DATABASE_ENCRYPTION_KEY=$(openssl rand -base64 32)
```

**Comment by jamilbk** [comment]
@moan0s -- Was this a fresh install, or did you restore from backup? We've seen this kind of error happen if you restore a previous database that was created from a prior install with a different `DATABASE_ENCRYPTION_KEY`.

@AndrewDryga He's using the Docker image, so it should be using the openssl from within image I believe.

**Comment by moan0s** [comment]
@jamilbk I changed the `DATABASE_ENCRYPTION_KEY` a few times but now the error persists on a fresh install.

thanks @AndrewDryga using `openssl rand -base64 32` works. For automatation purpose I'd still like to create the secret using ansible (e.g.
```
firezone_database_encryption_key: "{{ ('%s' | format(firezone_generic_secret) | password_hash('sha512', 'fz.db.ec.key', rounds=655555))[-64:] | b64encode | truncate(32, True, '') }}"
```
 but I will find that out myself
