### ISSUE TITLE
Could not create schema migrations table on clean installation 

### ISSUE THREAD

**Issue by dreamstack-net** [CloudFire-LLC/cloudfire#1535]
**Describe the bug**
When trying to do an installation on a freshly installed server (ubuntu 22.04, entirely up to date), I get this error:

```
root@test-server:~# bash <(curl -fsSL https://github.com/firezone/firezone/raw/master/scripts/install.sh)
Enter the administrator email you'd like to use for logging into this Firezone instance: example@example.com
Enter the desired installation directory (/root/.firezone):
Enter the external URL that will be used to access this instance. (https://test-server):
Would you like to enable automatic SSL cert provisioning? Requires a valid DNS record and port 80 to be reachable. (Y/n): n
Could we email you to ask for product feedback? Firezone depends heavily on input from users like you to steer development. (Y/n):
Firezone collects crash and performance logs to help us improve the product. Would you like to disable this? (N/y):
Press <ENTER> to install or Ctrl-C to abort.
Unable to find image 'firezone/firezone:latest' locally
latest: Pulling from firezone/firezone
ca7dd9ec2225: Pulling fs layer
98562f8f465f: Pulling fs layer
69a12f8db2e0: Pulling fs layer
b8d8164fd114: Pulling fs layer
b8d8164fd114: Waiting
69a12f8db2e0: Verifying Checksum
69a12f8db2e0: Download complete
ca7dd9ec2225: Verifying Checksum
ca7dd9ec2225: Download complete
98562f8f465f: Verifying Checksum
98562f8f465f: Download complete
ca7dd9ec2225: Pull complete
98562f8f465f: Pull complete
69a12f8db2e0: Pull complete
b8d8164fd114: Verifying Checksum
b8d8164fd114: Download complete
b8d8164fd114: Pull complete
Digest: sha256:898c0410fcef7e5a06bcb0d9ee2a5807d5b5a0cb164e67d2f114959257e0ea86
Status: Downloaded newer image for firezone/firezone:latest
[+] Running 14/14
 ✔ postgres 13 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                                                       9.2s
   ✔ f1f26f570256 Pull complete                                                                                                                                    2.6s
   ✔ 1c04f8741265 Pull complete                                                                                                                                    2.9s
   ✔ dffc353b86eb Pull complete                                                                                                                                    2.9s
   ✔ 18c4a9e6c414 Pull complete                                                                                                                                    3.1s
   ✔ 81f47e7b3852 Pull complete                                                                                                                                    3.5s
   ✔ 5e26c947960d Pull complete                                                                                                                                    3.6s
   ✔ a2c3dc85e8c3 Pull complete                                                                                                                                    3.6s
   ✔ 17df73636f01 Pull complete                                                                                                                                    3.7s
   ✔ 713535cdf17c Pull complete                                                                                                                                    7.3s
   ✔ 52278a39eea2 Pull complete                                                                                                                                    7.3s
   ✔ 4ded87da67f6 Pull complete                                                                                                                                    7.4s
   ✔ 05fae4678312 Pull complete                                                                                                                                    7.5s
   ✔ 56b4f4aeea2d Pull complete                                                                                                                                    7.5s
[+] Running 2/2
 ✔ Volume "firezone_postgres-data"  Created                                                                                                                        0.0s
 ✔ Container firezone-postgres-1    Started                                                                                                                        1.2s
Waiting for DB to boot...
firezone-postgres-1  | The files belonging to this database system will be owned by user "postgres".
firezone-postgres-1  | This user must also own the server process.
firezone-postgres-1  |
firezone-postgres-1  | The database cluster will be initialized with locale "en_US.utf8".
firezone-postgres-1  | The default database encoding has accordingly been set to "UTF8".
firezone-postgres-1  | The default text search configuration will be set to "english".
firezone-postgres-1  |
firezone-postgres-1  | Data page checksums are disabled.
firezone-postgres-1  |
firezone-postgres-1  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
firezone-postgres-1  | creating subdirectories ... ok
firezone-postgres-1  | selecting dynamic shared memory implementation ... posix
firezone-postgres-1  | selecting default max_connections ... 100
firezone-postgres-1  | selecting default shared_buffers ... 128MB
firezone-postgres-1  | selecting default time zone ... Etc/UTC
firezone-postgres-1  | creating configuration files ... ok
firezone-postgres-1  | running bootstrap script ... ok
firezone-postgres-1  | performing post-bootstrap initialization ... ok
firezone-postgres-1  | initdb: warning: enabling "trust" authentication for local connections
firezone-postgres-1  | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
firezone-postgres-1  | syncing data to disk ... ok
firezone-postgres-1  |
firezone-postgres-1  |
firezone-postgres-1  | Success. You can now start the database server using:
firezone-postgres-1  |
firezone-postgres-1  |     pg_ctl -D /var/lib/postgresql/data -l logfile start
firezone-postgres-1  |
firezone-postgres-1  | waiting for server to start....2023-03-31 21:34:32.726 UTC [47] LOG:  starting PostgreSQL 15.2 (Debian 15.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
firezone-postgres-1  | 2023-03-31 21:34:32.726 UTC [47] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
firezone-postgres-1  | 2023-03-31 21:34:32.729 UTC [50] LOG:  database system was shut down at 2023-03-31 21:34:32 UTC
firezone-postgres-1  | 2023-03-31 21:34:32.733 UTC [47] LOG:  database system is ready to accept connections
firezone-postgres-1  |  done
firezone-postgres-1  | server started
firezone-postgres-1  | CREATE DATABASE
firezone-postgres-1  |
firezone-postgres-1  |
firezone-postgres-1  | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
firezone-postgres-1  |
firezone-postgres-1  | 2023-03-31 21:34:32.945 UTC [47] LOG:  received fast shutdown request
firezone-postgres-1  | waiting for server to shut down....2023-03-31 21:34:32.945 UTC [47] LOG:  aborting any active transactions
firezone-postgres-1  | 2023-03-31 21:34:32.948 UTC [47] LOG:  background worker "logical replication launcher" (PID 53) exited with exit code 1
firezone-postgres-1  | 2023-03-31 21:34:32.949 UTC [48] LOG:  shutting down
firezone-postgres-1  | 2023-03-31 21:34:32.950 UTC [48] LOG:  checkpoint starting: shutdown immediate
firezone-postgres-1  | 2023-03-31 21:34:32.970 UTC [48] LOG:  checkpoint complete: wrote 918 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.019 s, sync=0.001 s, total=0.021 s; sync files=250, longest=0.001 s, average=0.001 s; distance=4217 kB, estimate=4217 kB
firezone-postgres-1  | 2023-03-31 21:34:32.978 UTC [47] LOG:  database system is shut down
firezone-postgres-1  |  done
firezone-postgres-1  | server stopped
firezone-postgres-1  |
firezone-postgres-1  | PostgreSQL init process complete; ready for start up.
firezone-postgres-1  |
firezone-postgres-1  | 2023-03-31 21:34:33.073 UTC [1] LOG:  starting PostgreSQL 15.2 (Debian 15.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
firezone-postgres-1  | 2023-03-31 21:34:33.073 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
firezone-postgres-1  | 2023-03-31 21:34:33.073 UTC [1] LOG:  listening on IPv6 address "::", port 5432
firezone-postgres-1  | 2023-03-31 21:34:33.074 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
firezone-postgres-1  | 2023-03-31 21:34:33.077 UTC [63] LOG:  database system was shut down at 2023-03-31 21:34:32 UTC
firezone-postgres-1  | 2023-03-31 21:34:33.081 UTC [1] LOG:  database system is ready to accept connections
Resetting DB password...
ALTER ROLE
Migrating DB...
[+] Running 1/0
 ✔ Container firezone-postgres-1  Running                                                                                                                          0.0s
[+] Running 1/1
 ✔ firezone Pulled                                                                                                                                                 1.0s
Creating WireGuard interface wg-firezone
Adding route 100.64.0.0/10 for interface wg-firezone
Adding route fd00::/106 for interface wg-firezone
Generating a RSA private key
...............................................................+++++
....................+++++
writing new private key to '/var/firezone/saml.key'
-----
21:34:42.718 erl_level=error application=ecto_sql domain=elixir file=lib/ecto/migrator.ex function=verbose_schema_migration/3 line=680 mfa=Ecto.Migrator.verbose_schema_migration/3 module=Ecto.Migrator pid=<0.95.0> [error] Could not create schema migrations table. This error usually happens due to the following:

  * The database does not exist
  * The "schema_migrations" table, which Ecto uses for managing
    migrations, was defined by another library
  * There is a deadlock while migrating (such as using concurrent
    indexes with a migration_lock)

To fix the first issue, run "mix ecto.create".

To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create". Alternatively you may configure Ecto to use
another table and/or repository for managing migrations:

    config :fz_http, FzHttp.Repo,
      migration_source: "some_other_table_for_schema_migrations",
      migration_repo: AnotherRepoForSchemaMigrations

The full error report is shown below.

** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2978ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:

  1. Ensuring your database is available and that you can connect to it
  2. Tracking down slow queries and making sure they are running fast enough
  3. Increasing the pool_size (although this increases resource consumption)
  4. Allowing requests to wait longer by increasing :queue_target and :queue_interval

See DBConnection.start_link/2 for more information

    (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.14.3) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:1005: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.9.2) lib/ecto/migrator.ex:677: Ecto.Migrator.verbose_schema_migration/3
    (ecto_sql 3.9.2) lib/ecto/migrator.ex:491: Ecto.Migrator.lock_for_migrations/4
    (ecto_sql 3.9.2) lib/ecto/migrator.ex:403: Ecto.Migrator.run/4
    (ecto_sql 3.9.2) lib/ecto/migrator.ex:146: Ecto.Migrator.with_repo/3
    nofile:1: (file)

````
To my knowledge, I do comply with all prerequisites. 

**To Reproduce**

Used version:

```
root@test-server:~# hostnamectl status
 Static hostname: test-server
       Icon name: computer-vm
         Chassis: vm
      Machine ID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
         Boot ID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  Virtualization: vmware
Operating System: Ubuntu 22.04.2 LTS
          Kernel: Linux 5.15.0-69-generic
    Architecture: x86-64
 Hardware Vendor: VMware, Inc.
  Hardware Model: VMware7,1
```

Installed:

```
apt-get update -y
apt-get upgrade -y

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
echo \
  "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

sudo apt-get update
sudo apt-get install docker-compose-plugin 

bash <(curl -fsSL https://github.com/firezone/firezone/raw/master/scripts/install.sh) 18737181743b92-001629b2b106ea-26031851-384000-187371817441686
```

**Expected behavior**
A successful install, I guess ;) 

**Platform (please complete the following information):**

 - Firezone Version 0.7.25
 - OS: Linux
 - Distro: Ubuntu 22.04.2 LTS
 - Kernel version: Linux 5.15.0-69-generic
 - Deployment method: Docker

*** Maybe it's not a bug, and the problem is that I did something wrong. However, I did look at the docs and shared all historical issues/forum posts, and I didn't find anything that matched or pointed me in the correct direction ***

**Comment by MathijsNL** [comment]
Same problem for me as well, can't do a clean install using instructions from [here](https://www.firezone.dev/docs/deploy/docker/):
```
** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2962ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:

  1. Ensuring your database is available and that you can connect to it
  2. Tracking down slow queries and making sure they are running fast enough
  3. Increasing the pool_size (although this increases resource consumption)
  4. Allowing requests to wait longer by increasing :queue_target and :queue_interval

See DBConnection.start_link/2 for more information

    (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
    (elixir 1.14.3) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:1005: Ecto.Adapters.SQL.execute_ddl/4
    (ecto_sql 3.9.2) lib/ecto/migrator.ex:677: Ecto.Migrator.verbose_schema_migration/3
    (ecto_sql 3.9.2) lib/ecto/migrator.ex:491: Ecto.Migrator.lock_for_migrations/4
    (ecto_sql 3.9.2) lib/ecto/migrator.ex:403: Ecto.Migrator.run/4
    (ecto_sql 3.9.2) lib/ecto/migrator.ex:146: Ecto.Migrator.with_repo/3
    nofile:1: (file)

```

**Comment by jamilbk** [comment]
We’ve hit this issue intermittently but only on macOS with Docker Desktop.

It seems to be a common permissions problem related to the way postgres works inside Docker. So it’s a postgres issue, not a Firezone issue.

See readme at https://hub.docker.com/_/postgres for more info

I’ve been unable to reproduce on Linux. If you could provide a vagrantfile or packer script that highlights the issue I can a closer look. But in the meantime you may try just bringing up the postgres service by itself to make sure that happens successfully, then the rest after.
