### ISSUE TITLE
/v0/devices json decode error

### ISSUE THREAD

**Issue by defp** [CloudFire-LLC/cloudfire#1707]
**Describe the bug**

```
firezone-firezone-1  | Request: GET /v0/devices
firezone-firezone-1  | ** (exit) an exception was raised:
firezone-firezone-1  |     ** (Protocol.UndefinedError) protocol Jason.Encoder not implemented for %Protocol.UndefinedError{protocol: Jason.Encoder, value: %FzHttp.Types.IPPort{type: :ipv4, address: {218, 108, 1, 112}, port: 51820}, description: "Jason.Encoder protocol must always be explicitly implemented.\n\nIf you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:\n\n    @derive {Jason.Encoder, only: [....]}\n    defstruct ...\n\nIt is also possible to encode all fields, although this should be used carefully to avoid accidentally leaking private information when new fields are added:\n\n    @derive Jason.Encoder\n    defstruct ...\n\nFinally, if you don't own the struct you want to encode to JSON, you may use Protocol.derive/3 placed outside of any module:\n\n    Protocol.derive(Jason.Encoder, NameOfTheStruct, only: [...])\n    Protocol.derive(Jason.Encoder, NameOfTheStruct)\n"} of type Protocol.UndefinedError (a struct), Jason.Encoder protocol must always be explicitly implemented.
firezone-firezone-1  |
firezone-firezone-1  | If you own the struct, you can derive the implementation specifying which fields should be encoded to JSON:
firezone-firezone-1  |
firezone-firezone-1  |     @derive {Jason.Encoder, only: [....]}
firezone-firezone-1  |     defstruct ...
firezone-firezone-1  |
firezone-firezone-1  | It is also possible to encode all fields, although this should be used carefully to avoid accidentally leaking private information when new fields are added:
firezone-firezone-1  |
firezone-firezone-1  |     @derive Jason.Encoder
firezone-firezone-1  |     defstruct ...
firezone-firezone-1  |
firezone-firezone-1  | Finally, if you don't own the struct you want to encode to JSON, you may use Protocol.derive/3 placed outside of any module:
firezone-firezone-1  |
firezone-firezone-1  |     Protocol.derive(Jason.Encoder, NameOfTheStruct, only: [...])
firezone-firezone-1  |     Protocol.derive(Jason.Encoder, NameOfTheStruct)
firezone-firezone-1  | . This protocol is implemented for the following type(s): Any, Atom, BitString, Date, DateTime, Decimal, Ecto.Association.NotLoaded, Ecto.Schema.Metadata, Float, Integer, Jason.Fragment, Jason.OrderedObject, List, Map, NaiveDateTime, Postgrex.INET, Time
firezone-firezone-1  |         (jason 1.4.0) lib/jason.ex:213: Jason.encode_to_iodata!/2
firezone-firezone-1  |         (phoenix 1.7.2) lib/phoenix/controller.ex:1010: anonymous fn/5 in Phoenix.Controller.template_render_to_iodata/4
firezone-firezone-1  |         (telemetry 1.2.1) /app/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
firezone-firezone-1  |         (phoenix 1.7.2) lib/phoenix/controller.ex:976: Phoenix.Controller.render_and_send/4
firezone-firezone-1  |         (phoenix 1.7.2) lib/phoenix/endpoint/render_errors.ex:84: Phoenix.Endpoint.RenderErrors.instrument_render_and_send/5
firezone-firezone-1  |         (phoenix 1.7.2) lib/phoenix/endpoint/render_errors.ex:62: Phoenix.Endpoint.RenderErrors.__catch__/5
firezone-firezone-1  |         (plug_cowboy 2.6.1) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
firezone-firezone-1  |         (cowboy 2.9.0) /app/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
```

**Platform (please complete the following information):**
VERSION=0.7.30

**Comment by jamilbk** [comment]
This was [fixed](https://github.com/firezone/firezone/pull/1670) in 0.7.31
