### ISSUE TITLE
Add Device not working

### ISSUE THREAD

**Issue by WiedenhoeverD** [CloudFire-LLC/cloudfire#1900]
**Describe the bug**
When I click Generate Configuration the button changes to Saving... for some seconds. After that the button is showing Generate Configuration again and nothing happed. When I look into the docker logs it is showing me a `Unknown cipher or invalid key size`.

**To Reproduce**
I made a fesh install with docker. I am running it without caddy because I am using NGINX Proxy Manager. After docker creation I login into my admin account and try to add a device.

**Screenshots / Logs**
```
14:00:34.437 erl_level=error domain=otp file=gen_server.erl function=error_info/8 line=1402 mfa=:gen_server.error_info/8 module=gen_server pid=<0.759.0> [error] GenServer #PID<0.759.0> terminating
** (stop) {:badarg, {'aead.c', 90}, 'Unknown cipher or invalid key size'}
    (crypto 5.1.2) crypto.erl:985: :crypto.crypto_one_time_aead(:aes_256_gcm, "n!iX6kPboisckQFiq7x7jfBxu5AQJ@knCp5s&9hguagETwYP#DQoVNfrYuDtkP&Y", <<123, 119, 176, 103, 39, 250, 143, 93, 200, 147, 48, 88>>, "2SzqQu8SEBlvhCQUwynpZ6w0aS4L5adSa0R+K4zSFdE=", "AES256GCM", 16, true)
    (cloak 1.1.2) lib/cloak/ciphers/aes_gcm.ex:47: Cloak.Ciphers.AES.GCM.encrypt/2
    (fz_http 0.7.32) lib/cloak_ecto/type.ex:37: FzHttp.Encrypted.Binary.dump/1
    (ecto 3.9.5) lib/ecto/type.ex:941: Ecto.Type.process_dumpers/3
    (ecto 3.9.5) lib/ecto/repo/schema.ex:1006: Ecto.Repo.Schema.dump_field!/6
    (ecto 3.9.5) lib/ecto/repo/schema.ex:1019: anonymous fn/6 in Ecto.Repo.Schema.dump_fields!/5
    (stdlib 4.2) maps.erl:411: :maps.fold_1/3
    (ecto 3.9.5) lib/ecto/repo/schema.ex:1017: Ecto.Repo.Schema.dump_fields!/5
Last message: %Phoenix.Socket.Message{topic: "lv:phx-F3qnPJbJ3MYjtQuU", event: "event", payload: %{"cid" => 7, "event" => "save", "type" => "form", "value" => "device%5Bpublic_key%5D=lY5fLhsPqLODo772Vg00pcx6q7ho3REDYWahZ9%2F5NUk%3D&device%5Bpreshared_key%5D=2SzqQu8SEBlvhCQUwynpZ6w0aS4L5adSa0R%2BK4zSFdE%3D&device%5Bname%5D=square-neat&device%5Bdescription%5D=&device%5Buse_default_allowed_ips%5D=true&device%5Buse_default_dns%5D=true&device%5Buse_default_endpoint%5D=true&device%5Buse_default_mtu%5D=true&device%5Buse_default_persistent_keepalive%5D=true&device%5Bipv4%5D=&device%5Bipv6%5D="}, ref: "34", join_ref: "13"}
```

**Platform (please complete the following information):**
 - Firezone Version 0.7.0
 - OS: Linux
 - Distro: debian 12
 - Kernel version: 6.1.0-10
 - Deployment method: Docker

**Comment by WiedenhoeverD** [comment]
I decoded my own created secrets and found out that the database key was the problem. To fix it I autocreated the the .env file with `docker run --rm firezone/firezone bin/gen-env > .env`. After a fresh install with the new secrets it is working.
