### ISSUE TITLE
OIDC 502 Error

### ISSUE THREAD

**Issue by zevaryx** [CloudFire-LLC/cloudfire#2167]
**Describe the bug**
Adding user via OIDC causes a 502 error after the callback. The user is registered as having an OIDC connection, but trying to use it raises a 502 error

**To Reproduce**
1. Create a user
2. Add an OIDC provider (I used GitLab)
3. Login with OIDC as user with same email as user created in step 1

**Expected behavior**
Successful login

**Screenshots / Logs**
Logs (redacted info represented with `...`):
```
firezone-firezone-1  | ** (exit) an exception was raised:
firezone-firezone-1  |     ** (Protocol.UndefinedError) protocol Phoenix.HTML.Safe not implemented for %Phoenix.Router.NoRouteError{plug_status: 404, message: "no route found for GET /favicon.ico (FzHttpWeb.Router)", conn: %Plug.Conn{adapter: {Plug.Cowboy.Conn, :...}, assigns: %{}, body_params: %{}, cookies: %Plug.Conn.Unfetched{aspect: :cookies}, halted: false, host: "fz.zevs.me", method: "GET", owner: #PID<0.1024.0>, params: %{}, path_info: ["favicon.ico"], path_params: %{}, port: 80, private: %{FzHttpWeb.Router => [], :before_send => [#Function<0.11807388/1 in Plug.Telemetry.call/2>], :phoenix_endpoint => FzHttpWeb.Endpoint, :phoenix_router => FzHttpWeb.Router, :plug_session_fetch => #Function<1.84243074/1 in Plug.Session.fetch_session/1>}, query_params: %{}, query_string: "", remote_ip: {172, 25, 0, 1}, req_cookies: %Plug.Conn.Unfetched{aspect: :cookies}, req_headers: [{"accept", "image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8"}, {"accept-encoding", "gzip, deflate, br"}, {"accept-language", "en-US,en;q=0.9"}, {"connection", "Upgrade"}, {"cookie", "_fz_http_key=...; fz_oidc_state=...; fz_pkce_code_verifier=..."}, {"dnt", "1"}, {"host", "fz.zevs.me"}, {"referer", "https://fz.zevs.me/auth/oidc/vt7AiI_m/callback/?code=..."}, {"sec-ch-ua", "\"Chromium\";v=\"116\", \"Not)A;Brand\";v=\"24\", \"Google Chrome\";v=\"116\""}, {"sec-ch-ua-mobile", "?0"}, {"sec-ch-ua-platform", "\"Windows\""}, {"sec-fetch-dest", "image"}, {"sec-fetch-mode", "no-cors"}, {"sec-fetch-site", "same-origin"}, {"user-agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"}, {"x-forwarded-for", "..."}, {"x-forwarded-proto", "https"}, {"x-real-ip", "..."}], request_path: "/favicon.ico", resp_body: nil, resp_cookies: %{}, resp_headers: [{"cache-control", "max-age=0, private, must-revalidate"}, {"x-request-id", "..."}], scheme: :http, script_name: [], secret_key_base: :..., state: :unset, status: nil}, router: FzHttpWeb.Router} of type Phoenix.Router.NoRouteError (a struct). This protocol is implemented for the following type(s): Atom, BitString, Date, DateTime, Decimal, Float, FzHttp.Types.IPPort, Integer, List, NaiveDateTime, Phoenix.HTML.Form, Phoenix.LiveComponent.CID, Phoenix.LiveView.Component, Phoenix.LiveView.Comprehension, Phoenix.LiveView.JS, Phoenix.LiveView.Rendered, Postgrex.INET, Time, Tuple, URI
firezone-firezone-1  |         (phoenix_html 3.3.1) lib/phoenix_html/safe.ex:1: Phoenix.HTML.Safe.impl_for!/1
firezone-firezone-1  |         (phoenix_html 3.3.1) lib/phoenix_html/safe.ex:15: Phoenix.HTML.Safe.to_iodata/1
firezone-firezone-1  |         (phoenix 1.7.2) lib/phoenix/controller.ex:1010: anonymous fn/5 in Phoenix.Controller.template_render_to_iodata/4
firezone-firezone-1  |         (telemetry 1.2.1) /app/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
firezone-firezone-1  |         (phoenix 1.7.2) lib/phoenix/controller.ex:976: Phoenix.Controller.render_and_send/4
firezone-firezone-1  |         (phoenix 1.7.2) lib/phoenix/endpoint/render_errors.ex:84: Phoenix.Endpoint.RenderErrors.instrument_render_and_send/5
firezone-firezone-1  |         (phoenix 1.7.2) lib/phoenix/endpoint/render_errors.ex:62: Phoenix.Endpoint.RenderErrors.__catch__/5
firezone-firezone-1  |         (plug_cowboy 2.6.1) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
```
The below are screenshots of my Firezone user and my GitLab OIDC configuration

![image](https://github.com/firezone/firezone/assets/57541873/f3686d3f-b15e-496e-9f20-677d035815c6)
![image](https://github.com/firezone/firezone/assets/57541873/89ed1cc7-7110-4e28-be4a-cbf117d79ac0)

**Platform (please complete the following information):**
 - Firezone Version: 0.7.35
 - OS: Linux
 - Distro: Ubuntu 22.04
 - Kernel version: 6.5.1
 - Deployment method: Docker

**Additional context**
I am running an external nginx proxy, so that may be the issue, but there's no guidance on nginx external proxies in the documentation

**Comment by jamilbk** [comment]
Hi @zevaryx -- yes, your nginx proxy is causing the issue. It looks like it's not serving the static assets properly. Can you ensure the favicon linked in your crash trace loads properly?

Unfortunately we don't have the resources to test on each load balancer / http proxy, so you're likely on your own for this one. PRs welcome!
