### ISSUE TITLE
500 when viewing certain clients

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2681]
https://app.firez.one/firezone/clients/587864bb-0e92-4573-9f49-c1775bd3e72a

<img width="993" alt="Screenshot 2023-11-20 at 8 18 24 AM" src="https://github.com/firezone/firezone/assets/167144/410f07b1-d4b4-410d-af37-48f7c7d8a3b2">

**Comment by AndrewDryga** [comment]
```
#PID<0.87604.0> running Web.Endpoint (connection #PID<0.87603.0>, stream id 1) terminated
Server: app.firez.one:80 (http)
Request: GET /firezone/clients/587864bb-0e92-4573-9f49-c1775bd3e72a
** (exit) an exception was raised:
    ** (KeyError) key :name not found in: nil

If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
        (web 1.20231001.0) lib/web/live/policies/components.ex:8: anonymous fn/2 in Web.Policies.Components."policy_name (overridable 1)"/1
        (web 1.20231001.0) /app/apps/web/lib/web/live/clients/show.ex:119: Web.Clients.Show.render/1
        (elixir 1.15.6) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
        (phoenix_live_view 0.20.1) lib/phoenix_live_view/diff.ex:384: Phoenix.LiveView.Diff.traverse/7
        (phoenix_live_view 0.20.1) lib/phoenix_live_view/diff.ex:538: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
        (elixir 1.15.6) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
```
