### ISSUE TITLE
500 when viewing https://app.firez.one/firezone/actors/1da651cd-c83a-42e5-a3f0-5cebdace422a

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#2690]
<img width="1552" alt="Screenshot 2023-11-22 at 11 51 56 AM" src="https://github.com/firezone/firezone/assets/167144/045afda3-c0e8-4525-baf4-bccaa154dc33">

**Comment by AndrewDryga** [comment]
```
Request: GET /firezone/actors/1da651cd-c83a-42e5-a3f0-5cebdace422a
** (exit) an exception was raised:
    ** (KeyError) key :name not found in: nil

If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
        (web 1.20231001.0) lib/web/live/policies/components.ex:8: anonymous fn/2 in Web.Policies.Components."policy_name (overridable 1)"/1
        (web 1.20231001.0) /app/apps/web/lib/web/live/actors/show.ex:201: Web.Actors.Show.render/1
        (elixir 1.15.6) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
        (phoenix_live_view 0.20.1) lib/phoenix_live_view/diff.ex:384: Phoenix.LiveView.Diff.traverse/7
        (phoenix_live_view 0.20.1) lib/phoenix_live_view/diff.ex:538: anonymous fn/4 in Phoenix.LiveView.Diff.traverse_dynamic/7
        (elixir 1.15.6) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
```

Duplicate of #2681
