### ISSUE TITLE
CentOS 8 Stream Fresh Build

### ISSUE THREAD

**Issue by RamboRogers** [CloudFire-LLC/cloudfire#364]
Hello Firezone Team,

I just created a fresh CentOS 8 box, I then installed the RPM and ran through the setup guide.  Everything was working until I clicked ad a device under my user.

I'm wondering if I'm missing a dependency for a Wireguard tool.  

`2021-12-27_23:35:25.84431 {"Kernel pid terminated",application_controller,"{application_start_failure,fz_vpn,{{shutdown,{failed_to_start_child,'Elixir.FzVpn.Server',{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<\"  Error executing command wg set wg-firezone peer dyr9ZK3R9aVudD5hVVXfVGhiZTquicU282ivTK6/fGc= allowed-ips 10.3.2.2/32,fd00:3:2::2/128.\n  Exit code: 1\n  Error message:\n  Unable to modify interface: Protocol not supported\n\n\">>},[{'Elixir.FzCommon.CLI',exec,2,[{file,\"lib/cli.ex\"},{line,28},{error_info,#{module => 'Elixir.Exception'}}]},{'Elixir.FzVpn.Server',apply_config,1,[{file,\"lib/fz_vpn/server.ex\"},{line,83}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,423}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,390}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,226}]}]}}},{'Elixir.FzVpn.Application',start,[normal,[]]}}}"}
2021-12-27_23:35:25.84495 Kernel pid terminated (application_controller) ({application_start_failure,fz_vpn,{{shutdown,{failed_to_start_child,'Elixir.FzVpn.Server',{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"  Error executing command wg set wg-firezone peer dyr9ZK3R9aVudD5hVVXfVGhiZTquicU282ivTK6/fGc= allowed-ips 10.3.2.2/32,fd00:3:2::2/128.\n  Exit code: 1\n  Error message:\n  Unable to modify interface: Protocol not supported\n\n">>},[{'Elixir.FzCommon.CLI',exec,2,[{file,"lib/cli.ex"},{line,28},{error_info,#{module => 'Elixir.Exception'}}]},{'Elixir.FzVpn.Server',apply_config,1,[{file,"lib/fz_vpn/server.ex"},{line,83}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,390}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}}},{'Elixir.FzVpn.Application',start,[normal,[]]}}})
2021-12-27_23:35:25.84801
2021-12-27_23:35:25.84803 Crash dump is being written to: erl_crash.dump...done
2021-12-27_23:35:28.97298 18:35:28.971 [info] Running FzHttpWeb.Endpoint with cowboy 2.9.0 at 127.0.0.1:13000 (http)
2021-12-27_23:35:28.98410 18:35:28.983 [info] Access FzHttpWeb.Endpoint at http://firezone.private.com:13000
2021-12-27_23:35:29.32457 18:35:29.254 [notice] Application fz_vpn exited: FzVpn.Application.start(:normal, []) returned an error: shutdown: failed to start child: FzVpn.Server
2021-12-27_23:35:29.32461     ** (EXIT) an exception was raised:
2021-12-27_23:35:29.32462         ** (RuntimeError)   Error executing command wg set wg-firezone peer dyr9ZK3R9aVudD5hVVXfVGhiZTquicU282ivTK6/fGc= allowed-ips 10.3.2.2/32,fd00:3:2::2/128.
2021-12-27_23:35:29.32462   Exit code: 1
2021-12-27_23:35:29.32463   Error message:
2021-12-27_23:35:29.32463   Unable to modify interface: Protocol not supported
2021-12-27_23:35:29.32463
2021-12-27_23:35:29.32464
2021-12-27_23:35:29.32464             (fz_common 0.2.0) lib/cli.ex:28: FzCommon.CLI.exec/2
2021-12-27_23:35:29.32464             (fz_vpn 0.2.0) lib/fz_vpn/server.ex:83: FzVpn.Server.apply_config/1
2021-12-27_23:35:29.32465             (stdlib 3.17) gen_server.erl:423: :gen_server.init_it/2
2021-12-27_23:35:29.32465             (stdlib 3.17) gen_server.erl:390: :gen_server.init_it/6
2021-12-27_23:35:29.32465             (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
2021-12-27_23:35:30.94241 {"Kernel pid terminated",application_controller,"{application_start_failure,fz_vpn,{{shutdown,{failed_to_start_child,'Elixir.FzVpn.Server',{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<\"  Error executing command wg set wg-firezone peer dyr9ZK3R9aVudD5hVVXfVGhiZTquicU282ivTK6/fGc= allowed-ips 10.3.2.2/32,fd00:3:2::2/128.\n  Exit code: 1\n  Error message:\n  Unable to modify interface: Protocol not supported\n\n\">>},[{'Elixir.FzCommon.CLI',exec,2,[{file,\"lib/cli.ex\"},{line,28},{error_info,#{module => 'Elixir.Exception'}}]},{'Elixir.FzVpn.Server',apply_config,1,[{file,\"lib/fz_vpn/server.ex\"},{line,83}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,423}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,390}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,226}]}]}}},{'Elixir.FzVpn.Application',start,[normal,[]]}}}"}
2021-12-27_23:35:30.94326 Kernel pid terminated (application_controller) ({application_start_failure,fz_vpn,{{shutdown,{failed_to_start_child,'Elixir.FzVpn.Server',{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"  Error executing command wg set wg-firezone peer dyr9ZK3R9aVudD5hVVXfVGhiZTquicU282ivTK6/fGc= allowed-ips 10.3.2.2/32,fd00:3:2::2/128.\n  Exit code: 1\n  Error message:\n  Unable to modify interface: Protocol not supported\n\n">>},[{'Elixir.FzCommon.CLI',exec,2,[{file,"lib/cli.ex"},{line,28},{error_info,#{module => 'Elixir.Exception'}}]},{'Elixir.FzVpn.Server',apply_config,1,[{file,"lib/fz_vpn/server.ex"},{line,83}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,390}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}}},{'Elixir.FzVpn.Application',start,[normal,[]]}}})`

**Comment by RamboRogers** [comment]
I did just install/add EPEL and loaded wireguard tools and still am having the same error.

`==> /var/log/firezone/wireguard/current <==
2021-12-27_23:47:15.10088 Error: Unknown device type.
2021-12-27_23:47:15.10522 Cannot find device "wg-firezone"
2021-12-27_23:47:15.11027 Cannot find device "wg-firezone"
2021-12-27_23:47:15.11462 Cannot find device "wg-firezone"
2021-12-27_23:47:15.11693 Unable to modify interface: Protocol not supported
2021-12-27_23:47:15.11926 Unable to modify interface: Protocol not supported
2021-12-27_23:47:15.12373 Cannot find device "wg-firezone"
2021-12-27_23:47:15.12804 Cannot find device "wg-firezone"
2021-12-27_23:47:15.12833 Enabling WireGuard debugging support...
2021-12-27_23:47:15.12847 WireGuard debugging enabled. Starting dmesg...`


2021-12-27_23:51:29.51357 18:51:29.442 [notice] Application fz_vpn exited: FzVpn.Application.start(:normal, []) returned an error: shutdown: failed to start child: FzVpn.Server
2021-12-27_23:51:29.51360     ** (EXIT) an exception was raised:
2021-12-27_23:51:29.51361         ** (RuntimeError)   Error executing command wg set wg-firezone peer dyr9ZK3R9aVudD5hVVXfVGhiZTquicU282ivTK6/fGc= allowed-ips 10.3.2.2/32,fd00:3:2::2/128.
2021-12-27_23:51:29.51361   Exit code: 1
2021-12-27_23:51:29.51361   Error message:
2021-12-27_23:51:29.51362   Unable to modify interface: Protocol not supported

**Comment by jamilbk** [comment]
Hi @RamboRogers -- thanks for the detailed report and log message!

Haven't seen this particular issue before, but it looks like your WireGuard kernel module may not be available or loaded. You shouldn't actually need the `wireguard-tools` userspace utilities because Firezone includes those.

Did you install the WireGuard kernel module using one of the methods listed on https://www.wireguard.com/install/ ?

What's the output of `uname -a`? Are you able to successfully add a WireGuard device with `ip link add dev wg0 type wireguard`?

**Comment by RamboRogers** [comment]
@jamilbk -- so I installed and it fixed it!  I'm really surprised that yum let me install wireguard tools without enabling the kernel module for them to actually work.

> yum install elrepo-release epel-release
> yum install kmod-wireguard wireguard-tools

Now it just works! Cool application, now that it's running I'm going to do some poking around.
