### ISSUE TITLE
Installation failure with 0.3.3 - "RPC failed with reason :nodedown" - Ubuntu and AmazonLinux2

### ISSUE THREAD

**Issue by BenPhegan** [CloudFire-LLC/cloudfire#521]
Hi,

I have tried installing now on both AmazonLinux2 and Ubuntu 20.04, and in both cases when running the second `sudo firezone-ctl create-or-reset-admin` I get the following:

```
ubuntu@ip-10-0-2-146:~$ sudo firezone-ctl create-or-reset-admin
[2022-04-07T00:40:48+00:00] INFO: Started Chef Infra Zero at chefzero://localhost:1 with repository at /opt/firezone/embedded (One version per cookbook)
Starting Chef Infra Client, version 16.17.51
Patents: https://www.chef.io/patents
[2022-04-07T00:40:48+00:00] INFO: *** Chef Infra Client 16.17.51 ***
[2022-04-07T00:40:48+00:00] INFO: Platform: x86_64-linux
[2022-04-07T00:40:48+00:00] INFO: Chef-client pid: 3123
[2022-04-07T00:40:52+00:00] WARN: Run List override has been provided.
[2022-04-07T00:40:52+00:00] WARN: Original Run List: [recipe[firezone::default]]
[2022-04-07T00:40:52+00:00] WARN: Overridden Run List: [recipe[firezone::create_admin]]
[2022-04-07T00:40:52+00:00] INFO: Run List is [recipe[firezone::create_admin]]
[2022-04-07T00:40:52+00:00] INFO: Run List expands to [firezone::create_admin]
[2022-04-07T00:40:52+00:00] INFO: Starting Chef Infra Client Run for ip-10-0-2-146.ap-southeast-9.compute.internal
[2022-04-07T00:40:52+00:00] INFO: Running start handlers
[2022-04-07T00:40:52+00:00] INFO: Start handlers complete.
resolving cookbooks for run list: ["firezone::create_admin"]
[2022-04-07T00:40:52+00:00] INFO: Loading cookbooks [firezone@0.0.1, enterprise@1.2.0, runit@5.1.6, line@4.4.4, packagecloud@1.0.1, yum-epel@4.4.1]
[2022-04-07T00:40:52+00:00] INFO: Skipping removal of obsoleted cookbooks from the cache
Synchronizing Cookbooks:
  - firezone (0.0.1)
  - enterprise (1.2.0)
  - runit (5.1.6)
  - line (4.4.4)
  - packagecloud (1.0.1)
  - yum-epel (4.4.1)
Installing Cookbook Gems:
Compiling Cookbooks...
[2022-04-07T00:40:52+00:00] INFO: Creating secrets file /etc/firezone/secrets.json
Converging 12 resources
Recipe: firezone::config
  * linux_user[firezone] action create[2022-04-07T00:40:52+00:00] INFO: Processing linux_user[firezone] action create (firezone::config line 54)
 (up to date)
  * group[firezone] action create[2022-04-07T00:40:52+00:00] INFO: Processing group[firezone] action create (firezone::config line 56)
 (up to date)
  * directory[/etc/firezone] action create[2022-04-07T00:40:52+00:00] INFO: Processing directory[/etc/firezone] action create (firezone::config line 60)
 (up to date)
  * directory[/var/opt/firezone] action create[2022-04-07T00:40:52+00:00] INFO: Processing directory[/var/opt/firezone] action create (firezone::config line 65)
 (up to date)
  * directory[/opt/firezone/embedded/service/firezone/tmp] action create[2022-04-07T00:40:52+00:00] INFO: Processing directory[/opt/firezone/embedded/service/firezone/tmp] action create (firezone::config line 72)
 (up to date)
  * directory[/var/log/firezone] action create[2022-04-07T00:40:52+00:00] INFO: Processing directory[/var/log/firezone] action create (firezone::config line 79)
 (up to date)
  * directory[/var/opt/firezone/etc] action create[2022-04-07T00:40:52+00:00] INFO: Processing directory[/var/opt/firezone/etc] action create (firezone::config line 86)
 (up to date)
  * file[configuration-variables] action create[2022-04-07T00:40:52+00:00] INFO: Processing file[configuration-variables] action create (firezone::config line 92)
 (up to date)
  * file[/etc/firezone/secrets.json] action create[2022-04-07T00:40:52+00:00] INFO: Processing file[/etc/firezone/secrets.json] action create (firezone::config line 99)
 (up to date)
  * file[/var/opt/firezone/cache/wg_private_key] action create_if_missing[2022-04-07T00:40:52+00:00] INFO: Processing file[/var/opt/firezone/cache/wg_private_key] action create_if_missing (firezone::config line 105)
 (up to date)
Recipe: firezone::create_admin
  * execute[create_admin] action run[2022-04-07T00:40:53+00:00] INFO: Processing execute[create_admin] action run (firezone::create_admin line 23)

    [execute] --rpc-eval : RPC failed with reason :nodedown
    
    ================================================================================
    Error executing action `run` on resource 'execute[create_admin]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of bin/firezone rpc "FzHttp.Release.create_admin_user" ----
    STDOUT: 
    STDERR: --rpc-eval : RPC failed with reason :nodedown
    ---- End output of bin/firezone rpc "FzHttp.Release.create_admin_user" ----
    Ran bin/firezone rpc "FzHttp.Release.create_admin_user" returned 1
    
    Resource Declaration:
    ---------------------
    # In /var/opt/firezone/cache/cache/cookbooks/firezone/recipes/create_admin.rb
    
     23: execute 'create_admin' do
     24:   command 'bin/firezone rpc "FzHttp.Release.create_admin_user"'
     25:   cwd node['firezone']['app_directory']
     26:   environment(Firezone::Config.app_env(node))
     27:   user node['firezone']['user']
     28: end
     29: 
    
    Compiled Resource:
    ------------------
    # Declared in /var/opt/firezone/cache/cache/cookbooks/firezone/recipes/create_admin.rb:23:in `from_file'
    
    execute("create_admin") do
      action [:run]
      default_guard_interpreter :execute
      command "bin/firezone rpc \"FzHttp.Release.create_admin_user\""
      declared_type :execute
      cookbook_name "firezone"
      recipe_name "create_admin"
      cwd "/opt/firezone/embedded/service/firezone"
      environment {"EGRESS_INTERFACE"=>"ens5", "WG_PATH"=>"/opt/firezone/embedded/bin/wg", "NFT_PATH"=>"/opt/firezone/embedded/sbin/nft", "MIX_ENV"=>"prod", "DATABASE_NAME"=>"firezone", "DATABASE_USER"=>"firezone", "DATABASE_HOST"=>"127.0.0.1", "DATABASE_PORT"=>"15432", "DATABASE_POOL"=>"10", "DATABASE_SSL"=>"false", "DATABASE_SSL_OPTS"=>"{}", "DATABASE_PARAMETERS"=>"{}", "PHOENIX_PORT"=>"13000", "EXTERNAL_URL"=>"https://ec2-82-69-173-69.ap-southeast-9.compute.amazonaws.com/", "ADMIN_EMAIL"=>"firezone@localhost", "WIREGUARD_INTERFACE_NAME"=>"wg-firezone", "WIREGUARD_PORT"=>"51820", "WIREGUARD_MTU"=>"1420", "WIREGUARD_ENDPOINT"=>"82.69.173.69", "WIREGUARD_DNS"=>"1.1.1.1, 1.0.0.1", "WIREGUARD_ALLOWED_IPS"=>"0.0.0.0/0, ::/0", "WIREGUARD_PERSISTENT_KEEPALIVE"=>"0", "WIREGUARD_PUBLIC_KEY"=>"qFQchanBJyg9ye9dLNday0/YEKgumLsBZsF1p8qvIBw=", "WIREGUARD_IPV4_ENABLED"=>"true", "WIREGUARD_IPV4_NETWORK"=>"10.3.2.0/24", "WIREGUARD_IPV4_ADDRESS"=>"10.3.2.1", "WIREGUARD_IPV6_ENABLED"=>"true", "WIREGUARD_IPV6_NETWORK"=>"fd00::3:2:0/120", "WIREGUARD_IPV6_ADDRESS"=>"fd00::3:2:1", "MAX_DEVICES_PER_USER"=>"10", "TELEMETRY_ENABLED"=>"true", "TELEMETRY_ID"=>"0579b421-7243-4668-9f40-60689f9dac18", "CONNECTIVITY_CHECKS_ENABLED"=>"true", "CONNECTIVITY_CHECKS_INTERVAL"=>"3600", "LOCAL_AUTH_ENABLED"=>"true", "OKTA_AUTH_ENABLED"=>"false", "OKTA_CLIENT_ID"=>nil, "OKTA_CLIENT_SECRET"=>nil, "OKTA_SITE"=>"https://your-domain.okta.com", "GOOGLE_AUTH_ENABLED"=>"false", "GOOGLE_CLIENT_ID"=>nil, "GOOGLE_CLIENT_SECRET"=>nil, "GOOGLE_REDIRECT_URI"=>nil, "GUARDIAN_SECRET_KEY"=>"XXH/AN4p0Flzo86k3M2fnPs7w4W1GrwcJ9JqiUpGXjZWHzq/JTnRLTvIO5TAt9S+", "SECRET_KEY_BASE"=>"w8QxZAs4H9jCdXiynvcQ39u34/IMtbf5rxxHzPX3viva7LeCPbk9jSsPY+ia8sPg", "LIVE_VIEW_SIGNING_SALT"=>"fXW1g5Jxw65MLiM0zzNvafcgCAV0/g/R", "COOKIE_SIGNING_SALT"=>"YO0OGS9W", "DATABASE_ENCRYPTION_KEY"=>"tno2BTO2rPF9xe+J6DmMaNLHtuKcnxnS+1Ly7vRXS/Y=", "DEFAULT_ADMIN_PASSWORD"=>"+jMtsSs5y6lc7Rgh"}
      user "firezone"
      domain nil
    end
    
    System Info:
    ------------
    chef_version=16.17.51
    platform=ubuntu
    platform_version=20.04
    ruby=ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-linux]
    program_name=/opt/firezone/embedded/bin/chef-client
    executable=/opt/firezone/embedded/bin/chef-client
    
[2022-04-07T00:40:54+00:00] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
[2022-04-07T00:40:54+00:00] ERROR: Running exception handlers
Running handlers complete
[2022-04-07T00:40:54+00:00] ERROR: Exception handlers complete
Chef Infra Client failed. 0 resources updated in 05 seconds
[2022-04-07T00:40:55+00:00] FATAL: Stacktrace dumped to /var/opt/firezone/cache/cache/chef-stacktrace.out
[2022-04-07T00:40:55+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2022-04-07T00:40:55+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: execute[create_admin] (firezone::create_admin line 23) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of bin/firezone rpc "FzHttp.Release.create_admin_user" ----
STDOUT: 
STDERR: --rpc-eval : RPC failed with reason :nodedown
---- End output of bin/firezone rpc "FzHttp.Release.create_admin_user" ----
Ran bin/firezone rpc "FzHttp.Release.create_admin_user" returned 1
```

Stacktrace looks like this:
```
Generated at 2022-04-07 01:09:23 +0000
Mixlib::ShellOut::ShellCommandFailed: execute[create_admin] (firezone::create_admin line 23) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of bin/firezone rpc "FzHttp.Release.create_admin_user" ----
STDOUT: 
STDERR: --rpc-eval : RPC failed with reason :nodedown
---- End output of bin/firezone rpc "FzHttp.Release.create_admin_user" ----
Ran bin/firezone rpc "FzHttp.Release.create_admin_user" returned 1
/opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.2.7/lib/mixlib/shellout.rb:300:in `invalid!'
/opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.2.7/lib/mixlib/shellout.rb:287:in `error!'
/opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.2.7/lib/mixlib/shellout/helper.rb:130:in `shell_out_compacted!'
/opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.2.7/lib/mixlib/shellout/helper.rb:54:in `shell_out!'
/opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/provider/execute.rb:52:in `block (2 levels) in <class:Execute>'
/opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/mixin/why_run.rb:51:in `add_action'
/opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/provider.rb:265:in `converge_by'
/opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/provider/execute.rb:50:in `block in <class:Execute>'
(eval):2:in `block in action_run'
/opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/provider.rb:276:in `instance_eval'
/opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/provider.rb:276:in `compile_and_converge_action'
(eval):2:in `action_run'
/opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/provider.rb:217:in `run_action'
/opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/resource.rb:599:in `block in run_action'
/opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/resource.rb:626:in `with_umask'
/opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/resource.rb:598:in `run_action'
/opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/runner.rb:74:in `run_action'
/opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/runner.rb:108:in `block in run_all_actions'
/opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/runner.rb:108:in `each'
/opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/runner.rb:108:in `run_all_actions'
/opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/runner.rb:132:in `block in converge'
/opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
/opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/resource_collection/stepable_iterator.rb:54:in `each_with_index'
/opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
/opt/firezone/embedded/lib/ruby/2.7.0/forwardable.rb:235:in `execute_each_resource'
/opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/runner.rb:130:in `converge'
/opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/client.rb:687:in `block in converge'
/opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/client.rb:682:in `catch'
/opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/client.rb:682:in `converge'
/opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/client.rb:706:in `converge_and_save'
/opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/client.rb:286:in `run'
/opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/application.rb:305:in `run_with_graceful_exit_option'
/opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/application.rb:281:in `block in run_chef_client'
/opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/application.rb:264:in `run_chef_client'
/opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/application/base.rb:337:in `run_application'
/opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/chef-16.17.51/lib/chef/application.rb:67:in `run'
/opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/chef-bin-16.17.51/bin/chef-client:25:in `<top (required)>'
/opt/firezone/embedded/bin/chef-client:23:in `load'
/opt/firezone/embedded/bin/chef-client:23:in `<main>'
```

As it is failing in the same way on both Ubuntu and AmazonLinux, I assume that I am doing something wrong.  However, I cannot spot it.  Ports that are open include those suggested (80, 443, 22, 51820).  I can keep trying on other distributions, but it would be good to understand what is occurring here before I continue.

Any pointers?

Thanks.

**Comment by BenPhegan** [comment]
As an update, added a Debian 11 instance, with identical environment, and it worked.

**Comment by jamilbk** [comment]
Hey @BenPhegan -- looks like `phoenix` isn't starting up normally. Could you post the logs with `firezone-ctl tail phoenix`?

This can sometimes happen when the kernel version is too low to support the `nftables` features we use.

**Comment by jamilbk** [comment]
@BenPhegan Any luck here? Haven't been able to reproduce. I've opened #541 to check for kernel version a bit more gracefully in the future.

**Comment by elhananjair** [comment]
> Hey @BenPhegan -- looks like `phoenix` isn't starting up normally. Could you post the logs with `firezone-ctl tail phoenix`?
> 
> This can sometimes happen when the kernel version is too low to support the `nftables` features we use.

@jamilbk am facing the same issue I removed the old Firezone and installed the latest one. Here is the output of _firezone-ctl tail phoenix_ 

> [root@fedora~]# firezone-ctl tail phoenix
2022-08-15_14:23:21.88388             (fz_vpn 0.5.4) lib/fz_vpn/interface.ex:42: FzVpn.Interface.set/3
2022-08-15_14:23:21.88389             (fz_vpn 0.5.4) lib/fz_vpn/server.ex:76: FzVpn.Server.update_changed_peers/2
2022-08-15_14:23:21.88391             (stdlib 4.0.1) gen_server.erl:848: :gen_server.init_it/2
2022-08-15_14:23:21.88391             (stdlib 4.0.1) gen_server.erl:811: :gen_server.init_it/6
2022-08-15_14:23:21.88392             (stdlib 4.0.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
2022-08-15_14:23:23.42039 {"Kernel pid terminated",application_controller,"{application_start_failure,fz_vpn,{{shutdown,{failed_to_start_child,'Elixir.FzVpn.Server',{<<\"Could not decode field :peers on %NifDeviceConfig{}\">>,[{'Elixir.Wireguardex',set_device,[#{'__struct__' => 'Elixir.Wireguardex.DeviceConfig',fwmark => nil,listen_port => nil,peers => [#{'__struct__' => 'Elixir.Wireguardex.PeerConfig',allowed_ips => [<<\"10.3.2.10/32\">>,<<\"fd00::3:2:2/128\">>],endpoint => nil,persistent_keepalive_interval => nil,preshared_key => error,public_key => <<\"5b/cO18fiBunbVjuhS0Uh4tViNf5sS7eQJbdbbQg+VQ=\">>},#{'__struct__' => 'Elixir.Wireguardex.PeerConfig',allowed_ips => [<<\"10.3.2.3/32\">>,<<\"fd00::3:2:3/128\">>],endpoint => nil,persistent_keepalive_interval => nil,preshared_key => error,public_key => <<\"8Mzvn+LKvD1bK+Un8c0WXE8KXt29xaniUr/tCYHjUxs=\">>}],private_key => nil,public_key => nil,replace_peers => false},<<\"wg-firezone\">>],[]},{'Elixir.FzVpn.Interface',set,3,[{file,\"lib/fz_vpn/interface.ex\"},{line,42}]},{'Elixir.FzVpn.Server',update_changed_peers,2,[{file,\"lib/fz_vpn/server.ex\"},{line,76}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,848}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,811}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,240}]}]}}},{'Elixir.FzVpn.Application',start,[normal,[]]}}}"}
2022-08-15_14:23:23.42241 Kernel pid terminated (application_controller) ({application_start_failure,fz_vpn,{{shutdown,{failed_to_start_child,'Elixir.FzVpn.Server',{<<"Could not decode field :peers on %NifDeviceConfig{}">>,[{'Elixir.Wireguardex',set_device,[#{'__struct__' => 'Elixir.Wireguardex.DeviceConfig',fwmark => nil,listen_port => nil,peers => [#{'__struct__' => 'Elixir.Wireguardex.PeerConfig',allowed_ips => [<<"10.3.2.10/32">>,<<"fd00::3:2:2/128">>],endpoint => nil,persistent_keepalive_interval => nil,preshared_key => error,public_key => <<"5b/cO18fiBunbVjuhS0Uh4tViNf5sS7eQJbdbbQg+VQ=">>},#{'__struct__' => 'Elixir.Wireguardex.PeerConfig',allowed_ips => [<<"10.3.2.3/32">>,<<"fd00::3:2:3/128">>],endpoint => nil,persistent_keepalive_interval => nil,preshared_key => error,public_key => <<"8Mzvn+LKvD1bK+Un8c0WXE8KXt29xaniUr/tCYHjUxs=">>}],private_key => nil,public_key => nil,replace_peers => false},<<"wg-firezone">>],[]},{'Elixir.FzVpn.Interface',set,3,[{file,"lib/fz_vpn/interface.ex"},{line,42}]},{'Elixir.FzVpn.Server',update_chan
2022-08-15_14:23:23.42406 
2022-08-15_14:23:23.42408 Crash dump is being written to: erl_crash.dump...done
2022-08-15_14:23:25.67652 Firezone detected a service crash loop. Taking service down. For support please email support@firez.one and include a copy of these crash logs.

**Comment by BenPhegan** [comment]
Apologies @jamilbk as I missed your responses.  I had moved on from testing Firezone and really can't offer anything else on this one.

**Comment by FxllenCode** [comment]
@jamilbk I'm having this same issue - Ubuntu 20.04 with the Docker install now. 

![firefox_E8zkj2FS0p](https://user-images.githubusercontent.com/40151425/196067593-39ca4a69-428e-4065-a3ad-2f7f92b7df21.png)

Was this ever resolved? I cannot login anymore and I am not sure what the default password is to login without an account as it is not working.

**Comment by elhananjair** [comment]
@jamilbk @FxllenCode In my case it's working fine, I am using the latest Firezone version.

**Comment by jamilbk** [comment]
> @jamilbk I'm having this same issue - Ubuntu 20.04 with the Docker install now.
> 
> ![firefox_E8zkj2FS0p](https://user-images.githubusercontent.com/40151425/196067593-39ca4a69-428e-4065-a3ad-2f7f92b7df21.png)
> 
> Was this ever resolved? I cannot login anymore and I am not sure what the default password is to login without an account as it is not working.

Is this happening with the docker install script? Likely it's because the app isn't booted before the bin/create-or-reset-admin script runs. See #1031 

Try giving the container about 15 seconds to boot then running `docker compose exec firezone bin/create-or-reset-admin` again.
