### ISSUE TITLE
Can't delete accounts with active providers

### ISSUE THREAD

**Issue by jamilbk** [CloudFire-LLC/cloudfire#5335]
Seems like there's a lock preventing deleting accounts with an active, syncing provider:

```
iex(web@web-lkt6.us-east1-d.c.firezone-prod.internal)1> Domain.Ops.delete_disabled_account("7c76c08b-9a27-4d7c-8203-b0e4465fa6d1")

04:39:23.342 [debug] QUERY OK source="accounts" db=1.6ms idle=1321.0ms
SELECT a0."id", a0."name", a0."slug", a0."legal_name", a0."features", a0."limits", a0."config", a0."metadata", a0."warning", a0."warning_delivery_attempts", a0."warning_last_sent_at", a0."disabled_reason", a0."disabled_at", a0."deleted_at", a0."inserted_at", a0."updated_at" FROM "accounts" AS a0 WHERE (a0."deleted_at" IS NULL) AND (NOT (a0."disabled_at" IS NULL)) AND (a0."id" = $1) ["7c76c08b-9a27-4d7c-8203-b0e4465fa6d1"]

04:39:38.347 [debug] QUERY ERROR source="accounts" db=15002.2ms queue=2.1ms idle=1323.4ms
DELETE FROM "accounts" WHERE "id" = $1 ["7c76c08b-9a27-4d7c-8203-b0e4465fa6d1"]
** (Postgrex.Error) ERROR 57014 (query_canceled) canceling statement due to user request
    (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1054: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto 3.11.2) lib/ecto/repo/schema.ex:775: Ecto.Repo.Schema.apply/4
    (ecto 3.11.2) lib/ecto/repo/schema.ex:571: anonymous fn/13 in Ecto.Repo.Schema.do_delete/4
    (domain 1.0.6) lib/domain/ops.ex:95: Domain.Ops.delete_disabled_account/1
    iex:1: (file)
```

**Comment by jamilbk** [comment]
Poked around a bit, but didn't want to break anything so I'll leave this one up to @AndrewDryga  :-). Probably needs a fix in the Domain.Ops.delete_disabled_account/1
