### ISSUE TITLE
Linux GUI client crashes after clicking on "Login"

### ISSUE THREAD

**Issue by thomaseizinger** [CloudFire-LLC/cloudfire#5424]
I am not sure if we can support this currently but trying to run the GUI client on my system crashes after clicking on "Login". When running it through `gdb`, I was able to capture the following backtrace:

```
#0  0x00007ffff21d7ab9 in g_type_check_instance () from /nix/store/n2x4y1n23m8xnq1gpl3f9vf43vfifcf9-glib-2.78.6/lib/libgobject-2.0.so.0
#1  0x00007ffff21cced4 in g_signal_handlers_disconnect_matched () from /nix/store/n2x4y1n23m8xnq1gpl3f9vf43vfifcf9-glib-2.78.6/lib/libgobject-2.0.so.0
#2  0x00007ffff26bad5d in gtk_accel_label_set_accel_closure () from /nix/store/1w549xnfbx1ja7r0z251103ghj5vnhzs-gtk+3-3.24.41/lib/libgtk-3.so.0
#3  0x00007ffff26baf87 in gtk_accel_label_set_accel_widget () from /nix/store/1w549xnfbx1ja7r0z251103ghj5vnhzs-gtk+3-3.24.41/lib/libgtk-3.so.0
#4  0x00007ffff26bb04b in gtk_accel_label_destroy () from /nix/store/1w549xnfbx1ja7r0z251103ghj5vnhzs-gtk+3-3.24.41/lib/libgtk-3.so.0
#5  0x00007ffff21b3431 in g_closure_invoke () from /nix/store/n2x4y1n23m8xnq1gpl3f9vf43vfifcf9-glib-2.78.6/lib/libgobject-2.0.so.0
#6  0x00007ffff21c5fca in signal_emit_unlocked_R.isra.0 () from /nix/store/n2x4y1n23m8xnq1gpl3f9vf43vfifcf9-glib-2.78.6/lib/libgobject-2.0.so.0
#7  0x00007ffff21c7b8c in signal_emit_valist_unlocked () from /nix/store/n2x4y1n23m8xnq1gpl3f9vf43vfifcf9-glib-2.78.6/lib/libgobject-2.0.so.0
#8  0x00007ffff21cd832 in g_signal_emit_valist () from /nix/store/n2x4y1n23m8xnq1gpl3f9vf43vfifcf9-glib-2.78.6/lib/libgobject-2.0.so.0
#9  0x00007ffff21cd8df in g_signal_emit () from /nix/store/n2x4y1n23m8xnq1gpl3f9vf43vfifcf9-glib-2.78.6/lib/libgobject-2.0.so.0
#10 0x00007ffff295b520 in gtk_widget_dispose () from /nix/store/1w549xnfbx1ja7r0z251103ghj5vnhzs-gtk+3-3.24.41/lib/libgtk-3.so.0
#11 0x00007ffff21b9f88 in g_object_run_dispose () from /nix/store/n2x4y1n23m8xnq1gpl3f9vf43vfifcf9-glib-2.78.6/lib/libgobject-2.0.so.0
#12 0x00007ffff2727298 in gtk_container_destroy () from /nix/store/1w549xnfbx1ja7r0z251103ghj5vnhzs-gtk+3-3.24.41/lib/libgtk-3.so.0
#13 0x00007ffff21b3431 in g_closure_invoke () from /nix/store/n2x4y1n23m8xnq1gpl3f9vf43vfifcf9-glib-2.78.6/lib/libgobject-2.0.so.0
#14 0x00007ffff21c5fca in signal_emit_unlocked_R.isra.0 () from /nix/store/n2x4y1n23m8xnq1gpl3f9vf43vfifcf9-glib-2.78.6/lib/libgobject-2.0.so.0
#15 0x00007ffff21c7b8c in signal_emit_valist_unlocked () from /nix/store/n2x4y1n23m8xnq1gpl3f9vf43vfifcf9-glib-2.78.6/lib/libgobject-2.0.so.0
#16 0x00007ffff21cd832 in g_signal_emit_valist () from /nix/store/n2x4y1n23m8xnq1gpl3f9vf43vfifcf9-glib-2.78.6/lib/libgobject-2.0.so.0
#17 0x00007ffff21cd8df in g_signal_emit () from /nix/store/n2x4y1n23m8xnq1gpl3f9vf43vfifcf9-glib-2.78.6/lib/libgobject-2.0.so.0
#18 0x00007ffff295b520 in gtk_widget_dispose () from /nix/store/1w549xnfbx1ja7r0z251103ghj5vnhzs-gtk+3-3.24.41/lib/libgtk-3.so.0
#19 0x00007ffff21b9f88 in g_object_run_dispose () from /nix/store/n2x4y1n23m8xnq1gpl3f9vf43vfifcf9-glib-2.78.6/lib/libgobject-2.0.so.0
#20 0x00007ffff281936d in gtk_menu_shell_forall () from /nix/store/1w549xnfbx1ja7r0z251103ghj5vnhzs-gtk+3-3.24.41/lib/libgtk-3.so.0
#21 0x00007ffff2727298 in gtk_container_destroy () from /nix/store/1w549xnfbx1ja7r0z251103ghj5vnhzs-gtk+3-3.24.41/lib/libgtk-3.so.0
#22 0x00007ffff21b34f0 in g_closure_invoke () from /nix/store/n2x4y1n23m8xnq1gpl3f9vf43vfifcf9-glib-2.78.6/lib/libgobject-2.0.so.0
#23 0x00007ffff21c5fca in signal_emit_unlocked_R.isra.0 () from /nix/store/n2x4y1n23m8xnq1gpl3f9vf43vfifcf9-glib-2.78.6/lib/libgobject-2.0.so.0
#24 0x00007ffff21c7b8c in signal_emit_valist_unlocked () from /nix/store/n2x4y1n23m8xnq1gpl3f9vf43vfifcf9-glib-2.78.6/lib/libgobject-2.0.so.0
#25 0x00007ffff21cd832 in g_signal_emit_valist () from /nix/store/n2x4y1n23m8xnq1gpl3f9vf43vfifcf9-glib-2.78.6/lib/libgobject-2.0.so.0
#26 0x00007ffff21cd8df in g_signal_emit () from /nix/store/n2x4y1n23m8xnq1gpl3f9vf43vfifcf9-glib-2.78.6/lib/libgobject-2.0.so.0
#27 0x00007ffff295b520 in gtk_widget_dispose () from /nix/store/1w549xnfbx1ja7r0z251103ghj5vnhzs-gtk+3-3.24.41/lib/libgtk-3.so.0
#28 0x00007ffff21b84b0 in g_object_unref () from /nix/store/n2x4y1n23m8xnq1gpl3f9vf43vfifcf9-glib-2.78.6/lib/libgobject-2.0.so.0
#29 0x00007ffff27255c8 in gtk_container_remove () from /nix/store/1w549xnfbx1ja7r0z251103ghj5vnhzs-gtk+3-3.24.41/lib/libgtk-3.so.0
#30 0x00007ffff295b444 in gtk_widget_dispose () from /nix/store/1w549xnfbx1ja7r0z251103ghj5vnhzs-gtk+3-3.24.41/lib/libgtk-3.so.0
#31 0x00007ffff21b84b0 in g_object_unref () from /nix/store/n2x4y1n23m8xnq1gpl3f9vf43vfifcf9-glib-2.78.6/lib/libgobject-2.0.so.0
#32 0x00007fffea600e87 in app_indicator_set_menu () from /nix/store/dhrqfsvpdzkg2lcfrmi3ma7r2cr9wj9a-libappindicator-gtk3-12.10.1+20.10.20200706.1/lib/libappindicator3.so.1
#33 0x000055555644f607 in libappindicator_sys::app_indicator_set_menu (self_=0x555557ab8830, menu=0x5555588ea250) at src/lib.rs:985
#34 0x0000555556449436 in libappindicator::AppIndicator::set_menu (self=0x555557ab5520, menu=0x7ffffffd71c8) at src/lib.rs:59
#35 0x00005555563b1b8d in tao::platform_impl::platform::system_tray::SystemTray::set_menu (self=0x555557ab54e8, tray_menu=0x7ffffffd99b0) at src/platform_impl/linux/system_tray.rs:103
#36 0x00005555563e34a4 in tao::system_tray::SystemTray::set_menu (self=0x555557ab54e8, tray_menu=0x7ffffffd99b0) at src/system_tray.rs:111
#37 0x0000555555f55adb in tauri_runtime_wry::handle_user_message<tauri::EventLoopMessage> (event_loop=0x7ffffffdde00, message=..., context=..., web_context=0x7ffffffde020) at /home/thomas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-runtime-wry-0.14.8/src/lib.rs:2744
#38 0x0000555555a1d01a in tauri_runtime_wry::handle_event_loop<tauri::EventLoopMessage> (event=..., event_loop=0x7ffffffdde00, control_flow=0x7ffffffdcd00, context=..., web_context=0x7ffffffde020) at /home/thomas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-runtime-wry-0.14.8/src/lib.rs:3052
#39 0x0000555555a21d9d in tauri_runtime_wry::{impl#50}::run::{closure#0}<tauri::EventLoopMessage, tauri::app::{impl#18}::run::{closure_env#0}<tauri_runtime_wry::Wry<tauri::EventLoopMessage>, firezone_gui_client::client::gui::run::{closure_env#3}>> (event=..., event_loop=0x7ffffffdde00, control_flow=0x7ffffffdcd00)
    at /home/thomas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-runtime-wry-0.14.8/src/lib.rs:2325
#40 0x0000555555aa1812 in tao::platform_impl::platform::event_loop::{impl#1}::run_return::{closure#0}<tauri_runtime_wry::Message<tauri::EventLoopMessage>, tauri_runtime_wry::{impl#50}::run::{closure_env#0}<tauri::EventLoopMessage, tauri::app::{impl#18}::run::{closure_env#0}<tauri_runtime_wry::Wry<tauri::EventLoopMessage>, firezone_gui_client::client::gui::run::{closure_env#3}>>> () at /home/thomas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tao-0.16.8/src/platform_impl/linux/event_loop.rs:1034
#41 0x0000555555a6f367 in glib::auto::main_context::MainContext::with_thread_default<i32, tao::platform_impl::platform::event_loop::{impl#1}::run_return::{closure_env#0}<tauri_runtime_wry::Message<tauri::EventLoopMessage>, tauri_runtime_wry::{impl#50}::run::{closure_env#0}<tauri::EventLoopMessage, tauri::app::{impl#18}::run::{closure_env#0}<tauri_runtime_wry::Wry<tauri::EventLoopMessage>, firezone_gui_client::client::gui::run::{closure_env#3}>>>> (self=0x7ffffffddd38, func=...) at /home/thomas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glib-0.15.12/src/main_context.rs:156
#42 0x0000555555aa0abe in tao::platform_impl::platform::event_loop::EventLoop<tauri_runtime_wry::Message<tauri::EventLoopMessage>>::run_return<tauri_runtime_wry::Message<tauri::EventLoopMessage>, tauri_runtime_wry::{impl#50}::run::{closure_env#0}<tauri::EventLoopMessage, tauri::app::{impl#18}::run::{closure_env#0}<tauri_runtime_wry::Wry<tauri::EventLoopMessage>, firezone_gui_client::client::gui::run::{closure_env#3}>>> (self=0x7ffffffdde00, callback=...) at /home/thomas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tao-0.16.8/src/platform_impl/linux/event_loop.rs:958
#43 0x0000555555aa1e6d in tao::platform_impl::platform::event_loop::EventLoop<tauri_runtime_wry::Message<tauri::EventLoopMessage>>::run<tauri_runtime_wry::Message<tauri::EventLoopMessage>, tauri_runtime_wry::{impl#50}::run::{closure_env#0}<tauri::EventLoopMessage, tauri::app::{impl#18}::run::{closure_env#0}<tauri_runtime_wry::Wry<tauri::EventLoopMessage>, firezone_gui_client::client::gui::run::{closure_env#3}>>> (self=..., callback=<error reading variable: Cannot access memory at address 0x18>) at /home/thomas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tao-0.16.8/src/platform_impl/linux/event_loop.rs:912
#44 0x00005555557a8ba9 in tao::event_loop::EventLoop<tauri_runtime_wry::Message<tauri::EventLoopMessage>>::run<tauri_runtime_wry::Message<tauri::EventLoopMessage>, tauri_runtime_wry::{impl#50}::run::{closure_env#0}<tauri::EventLoopMessage, tauri::app::{impl#18}::run::{closure_env#0}<tauri_runtime_wry::Wry<tauri::EventLoopMessage>, firezone_gui_client::client::gui::run::{closure_env#3}>>> (self=..., event_handler=<error reading variable: Cannot access memory at address 0x18>) at /home/thomas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tao-0.16.8/src/event_loop.rs:179
#45 0x0000555555a218fc in tauri_runtime_wry::{impl#50}::run<tauri::EventLoopMessage, tauri::app::{impl#18}::run::{closure_env#0}<tauri_runtime_wry::Wry<tauri::EventLoopMessage>, firezone_gui_client::client::gui::run::{closure_env#3}>> (self=..., callback=...)
    at /home/thomas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-runtime-wry-0.14.8/src/lib.rs:2299
#46 0x00005555557d5e53 in tauri::app::App<tauri_runtime_wry::Wry<tauri::EventLoopMessage>>::run<tauri_runtime_wry::Wry<tauri::EventLoopMessage>, firezone_gui_client::client::gui::run::{closure_env#3}> (self=..., callback=...)
    at /home/thomas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-1.6.7/src/app.rs:868
#47 0x0000555555a9dbae in firezone_gui_client::client::gui::run (cli=..., advanced_settings=...) at gui-client/src-tauri/src/client/gui.rs:272
#48 0x0000555555808aa2 in firezone_gui_client::client::run_gui (cli=...) at gui-client/src-tauri/src/client.rs:123
#49 0x000055555580b939 in firezone_gui_client::client::run () at gui-client/src-tauri/src/client.rs:74
#50 0x000055555596e8e6 in firezone_gui_client::main () at gui-client/src-tauri/src/main.rs:9
```

My glibc version is 2.38 if that matters. I am running kernel 6.8.11 on NixOS.

**Comment by ReactorScram** [comment]
The crash handler is supposed to get backtraces too, they end up in the log directory

Ubuntu 20.04 (where we build the binaries) has glibc 2.31, and I thought glibc was supposed to be backwards-compatible  🤔 

If we wanted really broad distro support we could bundle all the libs, and have 100 MB downloads, and at that point we may as well use Electron.

I am getting more serious that we should just use the OS' terminal and make a TUI app. We don't display any graphics except the Firezone logo. Too bad there isn't a WebView equivalent for terminals that would allow us to spawn and control little terminal windows. We aren't even displaying stdout so bundling a crummy xterm clone and just using it as a character display might be doable. It would just look awful to investors

**Comment by thomaseizinger** [comment]
I fixed the title, it is not glibc but some gnome version I guess?

**Comment by thomaseizinger** [comment]
> I am getting more serious that we should just use the OS' terminal and make a TUI app. We don't display any graphics except the Firezone logo. Too bad there isn't a WebView equivalent for terminals that would allow us to spawn and control little terminal windows. We aren't even displaying stdout so bundling a crummy xterm clone and just using it as a character display might be doable. It would just look awful to investors

Wouldn't it make more sense to devise an auth scheme that works with the headless client? That one is already cross-platform.

**Comment by ReactorScram** [comment]
The headless client can do our auth scheme, the reason we have all these compatibility problems is the GUI for the settings window and the tray menu

**Comment by jamilbk** [comment]
> Wouldn't it make more sense to devise an auth scheme that works with the headless client? That one is already cross-platform.

You mean like a user-present CLI auth scheme? Yeah I think that would be good to have. It's a ton of work though. We need a new auth flow in the portal to handle CLI auth, and a websocket channel from CLI to portal to facilitate the exchange / verification. We could get by with just showing a one-time copyable token in the web browser after authenticating with the CLI to avoid the websocket.

**Comment by thomaseizinger** [comment]
If the make the CLI keyring aware, we could use the same deep-link scheme by starting another instance of the CLI and saving the token.

Then, the next start of the background daemon can take the token and run in the background.

**Comment by thomaseizinger** [comment]
Was a problem with glibc mismatch.
