### ISSUE TITLE
Support TLS Authentication for PostgreSQL connection

### ISSUE THREAD

**Issue by vlaborie** [CloudFire-LLC/cloudfire#6452]
#### Describe the bug

Hello, i try to use TLS authentification for Postgresql connection but **certfile**, **keyfile** or **certs_keys** ssl options seem to not be supported.

#### To Reproduce

Configure DATABASE_SSL_OPTS to use certfile and keyfile:

~~~
DATABASE_SSL_OPTS="{ \"verify\": \"verify_peer\", \"cacertfile\": \"/etc/ssl/certs/ca.crt\", \"certfile\": \"/etc/ssl/certs/tls.crt\", \"keyfile\": \"/etc/ssl/private/tls.key\" }"
~~~

I also try with certs_keys parameter (certfile and keyfile have been deprecated to the benefit of certs_keys) :

~~~
DATABASE_SSL_OPTS="{ \"verify\": \"verify_peer\", \"cacertfile\": \"/etc/ssl/certs/ca.crt\", \"certs_keys\": [{\"certfile\": \"/etc/ssl/certs/tls.crt\", \"keyfile\": \"/etc/ssl/private/tls.key\"}] }"
~~~

#### Expected behavior

I want Firezone to use this cert and key to authenticate to Postgresql.

#### Screenshots / Logs

~~~
ERROR! Config provider Config.Reader failed with:
** (ArgumentError) unsupported key certfile in ssl opts
    (domain 1.0.5) lib/domain/config/dumper.ex:28: Domain.Config.Dumper.map_values/2
    (domain 1.0.5) lib/domain/config/dumper.ex:20: anonymous fn/1 in Domain.Config.Dumper.dump_ssl_opts/1
    (elixir 1.16.2) lib/keyword.ex:202: anonymous fn/3 in Keyword.new/2
    (elixir 1.16.2) lib/keyword.ex:206: Keyword."-new/2-lists^foldl/2-0-"/3
    (domain 1.0.5) lib/domain/config/fetcher.ex:21: Domain.Config.Fetcher.fetch_source_and_config/4
    (domain 1.0.5) lib/domain/config.ex:36: Domain.Config.compile_config!/3
    /app/releases/1.0.5/runtime.exs:18: (file)
    (elixir 1.16.2) src/elixir.erl:405: :elixir.eval_external_handler/3

Runtime terminating during boot ({#{message=><<"unsupported key certfile in ssl opts">>,'__struct__'=>'Elixir.ArgumentError','__exception__'=>true},[{'Elixir.Domain.Config.Dumper',map_values,2,[{file,"lib/domain/config/dumper.ex"},{line,28}]},{'Elixir.Domain.Config.Dumper','-dump_ssl_opts/1-fun-0-',1,[{file,"lib/domain/config/dumper.ex"},{line,20}]},{'Elixir.Keyword','-new/2-fun-0-',3,[{file,"lib/keyword.ex"},{line,202}]},{'Elixir.Keyword','-new/2-lists^foldl/2-0-',3,[{file,"lib/keyword.ex"},{line,206}]},{'Elixir.Domain.Config.Fetcher',fetch_source_and_config,4,[{file,"lib/domain/config/fetcher.ex"},{line,21}]},{'Elixir.Domain.Config','compile_config!',3,[{file,"lib/domain/config.ex"},{line,36}]},{elixir_eval,'__FILE__',1,[{file,"/app/releases/1.0.5/runtime.exs"},{line,18}]},{elixir,eval_external_handler,3,[{file,"src/elixir.erl"},{line,405}]}]})
~~~

I have the same error with **keyfile** or **certs_keys**.

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal): web
- _Firezone Version (e.g. 1.0.0 or N/A): 1.0.5
- _OS and version: (e.g. Ubuntu 22.04 or N/A): N/A
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A): Docker

#### Additional context

I don't known Erlang/Elexir but for what i understand, ssl options need to be "whitelisted" in https://github.com/firezone/firezone/blob/main/elixir/apps/domain/lib/domain/config/dumper.ex

**Comment by jamilbk** [comment]
Thanks for the request! I don't _think_ this will be difficult to accommodate, but @AndrewDryga might be able to clarify otherwise.

**Comment by jamilbk** [comment]
I think this is now supported with `DATABASE_SSL`.
