### ISSUE TITLE
Can't setup SMTP mailer

### ISSUE THREAD

**Issue by baznikin** [CloudFire-LLC/cloudfire#6665]
#### Describe the bug

Trying to setup firezone admin portal with Helmchart, got strange error:

```
** (FunctionClauseError) no function clause matching in :lists.partition_1/4
	(stdlib 6.0.1) lists.erl:2231:in `:lists.partition_1(#Function<0.14248608/1 in :smtp_socket.proplist_merge/2>, nil, [active: false, keepalive: true, packet: :line], [])'
    (gen_smtp 1.2.0) /app/deps/gen_smtp/src/smtp_socket.erl:339:in `:smtp_socket.proplist_merge/2'
    (gen_smtp 1.2.0) /app/deps/gen_smtp/src/smtp_socket.erl:329:in `:smtp_socket.tcp_connect_options/2'
    (gen_smtp 1.2.0) /app/deps/gen_smtp/src/smtp_socket.erl:107:in `:smtp_socket.connect/5'
    (gen_smtp 1.2.0) /app/deps/gen_smtp/src/gen_smtp_client.erl:820:in `:gen_smtp_client.connect/2'
    (gen_smtp 1.2.0) /app/deps/gen_smtp/src/gen_smtp_client.erl:378:in `:gen_smtp_client.open_smtp_session/2'
    (gen_smtp 1.2.0) /app/deps/gen_smtp/src/gen_smtp_client.erl:316:in `:gen_smtp_client.try_smtp_sessions/3'
    (gen_smtp 1.2.0) /app/deps/gen_smtp/src/gen_smtp_client.erl:289:in `:gen_smtp_client.send_it/2'
```

Env vars:
```
OUTBOUND_EMAIL_ADAPTER=Elixir.Swoosh.Adapters.SMTP
OUTBOUND_EMAIL_ADAPTER_OPTS={"port":1025,"relay":"mailer.mydomain.io"}
OUTBOUND_EMAIL_FROM=firezone@mydomain.com
```

Start with full SMTP configuration, stripped it down to minimal one. No attempts to connect to mail relay.

#### Screenshots / Logs

```
{"message":"Headers: [\n  {\"From\", \"firezone@mydomain.com\"},\n  {\"To\", \"username@mydomain.com\"},\n  {\"Subject\", \"Welcome to Firezone\"},\n  {\"MIME-Version\", \"1.0\"}\n]","time":"2024-09-11T13:04:11.688Z","domain":["gen_smtp"],"otel_trace_flags":[48,49],"severity":"DEBUG","logging.googleapis.com/sourceLocation":{"file":"/app/deps/gen_smtp/src/mimemail.erl","line":409,"function":"mimemail.get_header_value/3"},"logging.googleapis.com/operation":{"producer":"#PID<0.848.0>"},"logging.googleapis.com/spanId":"3c5218a4b59fc13d","logging.googleapis.com/trace":"c9c853e27691f833657313a83bd95d79"}
{"message":"Headers: [\n  {\"From\", \"firezone@mydomain.com\"},\n  {\"To\", \"username@mydomain.com\"},\n  {\"Subject\", \"Welcome to Firezone\"},\n  {\"MIME-Version\", \"1.0\"}\n]","time":"2024-09-11T13:04:11.692Z","domain":["gen_smtp"],"otel_trace_flags":[48,49],"severity":"DEBUG","logging.googleapis.com/sourceLocation":{"file":"/app/deps/gen_smtp/src/mimemail.erl","line":409,"function":"mimemail.get_header_value/3"},"logging.googleapis.com/operation":{"producer":"#PID<0.848.0>"},"logging.googleapis.com/spanId":"3c5218a4b59fc13d","logging.googleapis.com/trace":"c9c853e27691f833657313a83bd95d79"}
{"message":"Headers: [\n  {\"From\", \"firezone@mydomain.com\"},\n  {\"To\", \"username@mydomain.com\"},\n  {\"Subject\", \"Welcome to Firezone\"},\n  {\"MIME-Version\", \"1.0\"}\n]","time":"2024-09-11T13:04:11.692Z","domain":["gen_smtp"],"otel_trace_flags":[48,49],"severity":"DEBUG","logging.googleapis.com/sourceLocation":{"file":"/app/deps/gen_smtp/src/mimemail.erl","line":409,"function":"mimemail.get_header_value/3"},"logging.googleapis.com/operation":{"producer":"#PID<0.848.0>"},"logging.googleapis.com/spanId":"3c5218a4b59fc13d","logging.googleapis.com/trace":"c9c853e27691f833657313a83bd95d79"}
{"message":"Headers: [\n  {\"Content-Type\",\n   \"multipart/alternative;boundary=\\\"_=305h4l5t6g4q0w1j0e6f175r595a2q60=_\\\"\"},\n  {\"MIME-Version\", \"1.0\"},\n  {\"Subject\", \"Welcome to Firezone\"},\n  {\"To\", \"username@mydomain.com\"},\n  {\"From\", \"firezone@mydomain.com\"}\n]","time":"2024-09-11T13:04:11.697Z","domain":["gen_smtp"],"otel_trace_flags":[48,49],"severity":"DEBUG","logging.googleapis.com/sourceLocation":{"file":"/app/deps/gen_smtp/src/mimemail.erl","line":409,"function":"mimemail.get_header_value/3"},"logging.googleapis.com/operation":{"producer":"#PID<0.848.0>"},"logging.googleapis.com/spanId":"3c5218a4b59fc13d","logging.googleapis.com/trace":"c9c853e27691f833657313a83bd95d79"}
{"message":"Headers: [\n  {\"Content-Type\",\n   \"multipart/alternative;boundary=\\\"_=305h4l5t6g4q0w1j0e6f175r595a2q60=_\\\"\"},\n  {\"MIME-Version\", \"1.0\"},\n  {\"Subject\", \"Welcome to Firezone\"},\n  {\"To\", \"username@mydomain.com\"},\n  {\"From\", \"firezone@mydomain.com\"}\n]","time":"2024-09-11T13:04:11.697Z","domain":["gen_smtp"],"otel_trace_flags":[48,49],"severity":"DEBUG","logging.googleapis.com/sourceLocation":{"file":"/app/deps/gen_smtp/src/mimemail.erl","line":409,"function":"mimemail.get_header_value/3"},"logging.googleapis.com/operation":{"producer":"#PID<0.848.0>"},"logging.googleapis.com/spanId":"3c5218a4b59fc13d","logging.googleapis.com/trace":"c9c853e27691f833657313a83bd95d79"}
{"message":"Headers: [\n  {\"Date\", \"Wed, 11 Sep 2024 13:04:11 +0000\"},\n  {\"Content-Type\",\n   \"multipart/alternative;boundary=\\\"_=305h4l5t6g4q0w1j0e6f175r595a2q60=_\\\"\"},\n  {\"MIME-Version\", \"1.0\"},\n  {\"Subject\", \"Welcome to Firezone\"},\n  {\"To\", \"username@mydomain.com\"},\n  {\"From\", \"firezone@mydomain.com\"}\n]","time":"2024-09-11T13:04:11.697Z","domain":["gen_smtp"],"otel_trace_flags":[48,49],"severity":"DEBUG","logging.googleapis.com/sourceLocation":{"file":"/app/deps/gen_smtp/src/mimemail.erl","line":409,"function":"mimemail.get_header_value/3"},"logging.googleapis.com/operation":{"producer":"#PID<0.848.0>"},"logging.googleapis.com/spanId":"3c5218a4b59fc13d","logging.googleapis.com/trace":"c9c853e27691f833657313a83bd95d79"}
{"message":"Headers: [\n  {\"Date\", \"Wed, 11 Sep 2024 13:04:11 +0000\"},\n  {\"Content-Type\",\n   \"multipart/alternative;boundary=\\\"_=305h4l5t6g4q0w1j0e6f175r595a2q60=_\\\"\"},\n  {\"MIME-Version\", \"1.0\"},\n  {\"Subject\", \"Welcome to Firezone\"},\n  {\"To\", \"username@mydomain.com\"},\n  {\"From\", \"firezone@mydomain.com\"}\n]","time":"2024-09-11T13:04:11.698Z","domain":["gen_smtp"],"otel_trace_flags":[48,49],"severity":"DEBUG","logging.googleapis.com/sourceLocation":{"file":"/app/deps/gen_smtp/src/mimemail.erl","line":409,"function":"mimemail.get_header_value/3"},"logging.googleapis.com/operation":{"producer":"#PID<0.848.0>"},"logging.googleapis.com/spanId":"3c5218a4b59fc13d","logging.googleapis.com/trace":"c9c853e27691f833657313a83bd95d79"}
{"message":"Headers: [\n  {\"Message-ID\",\n   \"<4e851f1ad984aca07155c492dbd22de7@firezone-web-5cb466d467-58zgf>\"},\n  {\"Date\", \"Wed, 11 Sep 2024 13:04:11 +0000\"},\n  {\"Content-Type\",\n   \"multipart/alternative;boundary=\\\"_=305h4l5t6g4q0w1j0e6f175r595a2q60=_\\\"\"},\n  {\"MIME-Version\", \"1.0\"},\n  {\"Subject\", \"Welcome to Firezone\"},\n  {\"To\", \"username@mydomain.com\"},\n  {\"From\", \"firezone@mydomain.com\"}\n]","time":"2024-09-11T13:04:11.700Z","domain":["gen_smtp"],"otel_trace_flags":[48,49],"severity":"DEBUG","logging.googleapis.com/sourceLocation":{"file":"/app/deps/gen_smtp/src/mimemail.erl","line":409,"function":"mimemail.get_header_value/3"},"logging.googleapis.com/operation":{"producer":"#PID<0.848.0>"},"logging.googleapis.com/spanId":"3c5218a4b59fc13d","logging.googleapis.com/trace":"c9c853e27691f833657313a83bd95d79"}
{"message":"Headers: [\n  {\"Message-ID\",\n   \"<4e851f1ad984aca07155c492dbd22de7@firezone-web-5cb466d467-58zgf>\"},\n  {\"Date\", \"Wed, 11 Sep 2024 13:04:11 +0000\"},\n  {\"Content-Type\",\n   \"multipart/alternative;boundary=\\\"_=305h4l5t6g4q0w1j0e6f175r595a2q60=_\\\"\"},\n  {\"MIME-Version\", \"1.0\"},\n  {\"Subject\", \"Welcome to Firezone\"},\n  {\"To\", \"username@mydomain.com\"},\n  {\"From\", \"firezone@mydomain.com\"}\n]","time":"2024-09-11T13:04:11.701Z","domain":["gen_smtp"],"otel_trace_flags":[48,49],"severity":"DEBUG","logging.googleapis.com/sourceLocation":{"file":"/app/deps/gen_smtp/src/mimemail.erl","line":409,"function":"mimemail.get_header_value/3"},"logging.googleapis.com/operation":{"producer":"#PID<0.848.0>"},"logging.googleapis.com/spanId":"3c5218a4b59fc13d","logging.googleapis.com/trace":"c9c853e27691f833657313a83bd95d79"}
{"message":"Headers: [\n  {\"Message-ID\",\n   \"<4e851f1ad984aca07155c492dbd22de7@firezone-web-5cb466d467-58zgf>\"},\n  {\"Date\", \"Wed, 11 Sep 2024 13:04:11 +0000\"},\n  {\"Content-Type\",\n   \"multipart/alternative;boundary=\\\"_=305h4l5t6g4q0w1j0e6f175r595a2q60=_\\\"\"},\n  {\"MIME-Version\", \"1.0\"},\n  {\"Subject\", \"Welcome to Firezone\"},\n  {\"To\", \"username@mydomain.com\"},\n  {\"From\", \"firezone@mydomain.com\"}\n]","time":"2024-09-11T13:04:11.701Z","domain":["gen_smtp"],"otel_trace_flags":[48,49],"severity":"DEBUG","logging.googleapis.com/sourceLocation":{"file":"/app/deps/gen_smtp/src/mimemail.erl","line":409,"function":"mimemail.get_header_value/3"},"logging.googleapis.com/operation":{"producer":"#PID<0.848.0>"},"logging.googleapis.com/spanId":"3c5218a4b59fc13d","logging.googleapis.com/trace":"c9c853e27691f833657313a83bd95d79"}
{"message":"Headers: [\n  {\"Content-Type\", \"text/plain; charset=\\\"utf-8\\\"\"},\n  {\"Content-Transfer-Encoding\", \"quoted-printable\"}\n]","time":"2024-09-11T13:04:11.702Z","domain":["gen_smtp"],"otel_trace_flags":[48,49],"severity":"DEBUG","logging.googleapis.com/sourceLocation":{"file":"/app/deps/gen_smtp/src/mimemail.erl","line":409,"function":"mimemail.get_header_value/3"},"logging.googleapis.com/operation":{"producer":"#PID<0.848.0>"},"logging.googleapis.com/spanId":"3c5218a4b59fc13d","logging.googleapis.com/trace":"c9c853e27691f833657313a83bd95d79"}
{"message":"Headers: [\n  {\"Content-Type\", \"text/plain; charset=\\\"utf-8\\\"\"},\n  {\"Content-Transfer-Encoding\", \"quoted-printable\"}\n]","time":"2024-09-11T13:04:11.702Z","domain":["gen_smtp"],"otel_trace_flags":[48,49],"severity":"DEBUG","logging.googleapis.com/sourceLocation":{"file":"/app/deps/gen_smtp/src/mimemail.erl","line":409,"function":"mimemail.get_header_value/3"},"logging.googleapis.com/operation":{"producer":"#PID<0.848.0>"},"logging.googleapis.com/spanId":"3c5218a4b59fc13d","logging.googleapis.com/trace":"c9c853e27691f833657313a83bd95d79"}
{"message":"Headers: [\n  {\"Content-Type\", \"text/plain; charset=\\\"utf-8\\\"\"},\n  {\"Content-Transfer-Encoding\", \"quoted-printable\"}\n]","time":"2024-09-11T13:04:11.703Z","domain":["gen_smtp"],"otel_trace_flags":[48,49],"severity":"DEBUG","logging.googleapis.com/sourceLocation":{"file":"/app/deps/gen_smtp/src/mimemail.erl","line":409,"function":"mimemail.get_header_value/3"},"logging.googleapis.com/operation":{"producer":"#PID<0.848.0>"},"logging.googleapis.com/spanId":"3c5218a4b59fc13d","logging.googleapis.com/trace":"c9c853e27691f833657313a83bd95d79"}
{"message":"Headers: [\n  {\"Content-Type\", \"text/plain; charset=\\\"utf-8\\\"\"},\n  {\"Content-Transfer-Encoding\", \"quoted-printable\"},\n  {\"Content-Disposition\", \"inline\"}\n]","time":"2024-09-11T13:04:11.703Z","domain":["gen_smtp"],"otel_trace_flags":[48,49],"severity":"DEBUG","logging.googleapis.com/sourceLocation":{"file":"/app/deps/gen_smtp/src/mimemail.erl","line":409,"function":"mimemail.get_header_value/3"},"logging.googleapis.com/operation":{"producer":"#PID<0.848.0>"},"logging.googleapis.com/spanId":"3c5218a4b59fc13d","logging.googleapis.com/trace":"c9c853e27691f833657313a83bd95d79"}
{"message":"Headers: [\n  {\"Content-Type\", \"text/html; charset=\\\"utf-8\\\"\"},\n  {\"Content-Transfer-Encoding\", \"quoted-printable\"}\n]","time":"2024-09-11T13:04:11.704Z","domain":["gen_smtp"],"otel_trace_flags":[48,49],"severity":"DEBUG","logging.googleapis.com/sourceLocation":{"file":"/app/deps/gen_smtp/src/mimemail.erl","line":409,"function":"mimemail.get_header_value/3"},"logging.googleapis.com/operation":{"producer":"#PID<0.848.0>"},"logging.googleapis.com/spanId":"3c5218a4b59fc13d","logging.googleapis.com/trace":"c9c853e27691f833657313a83bd95d79"}
{"message":"Headers: [\n  {\"Content-Type\", \"text/html; charset=\\\"utf-8\\\"\"},\n  {\"Content-Transfer-Encoding\", \"quoted-printable\"}\n]","time":"2024-09-11T13:04:11.704Z","domain":["gen_smtp"],"otel_trace_flags":[48,49],"severity":"DEBUG","logging.googleapis.com/sourceLocation":{"file":"/app/deps/gen_smtp/src/mimemail.erl","line":409,"function":"mimemail.get_header_value/3"},"logging.googleapis.com/operation":{"producer":"#PID<0.848.0>"},"logging.googleapis.com/spanId":"3c5218a4b59fc13d","logging.googleapis.com/trace":"c9c853e27691f833657313a83bd95d79"}
{"message":"Headers: [\n  {\"Content-Type\", \"text/html; charset=\\\"utf-8\\\"\"},\n  {\"Content-Transfer-Encoding\", \"quoted-printable\"}\n]","time":"2024-09-11T13:04:11.705Z","domain":["gen_smtp"],"otel_trace_flags":[48,49],"severity":"DEBUG","logging.googleapis.com/sourceLocation":{"file":"/app/deps/gen_smtp/src/mimemail.erl","line":409,"function":"mimemail.get_header_value/3"},"logging.googleapis.com/operation":{"producer":"#PID<0.848.0>"},"logging.googleapis.com/spanId":"3c5218a4b59fc13d","logging.googleapis.com/trace":"c9c853e27691f833657313a83bd95d79"}
{"message":"Headers: [\n  {\"Content-Type\", \"text/html; charset=\\\"utf-8\\\"\"},\n  {\"Content-Transfer-Encoding\", \"quoted-printable\"},\n  {\"Content-Disposition\", \"inline\"}\n]","time":"2024-09-11T13:04:11.705Z","domain":["gen_smtp"],"otel_trace_flags":[48,49],"severity":"DEBUG","logging.googleapis.com/sourceLocation":{"file":"/app/deps/gen_smtp/src/mimemail.erl","line":409,"function":"mimemail.get_header_value/3"},"logging.googleapis.com/operation":{"producer":"#PID<0.848.0>"},"logging.googleapis.com/spanId":"3c5218a4b59fc13d","logging.googleapis.com/trace":"c9c853e27691f833657313a83bd95d79"}
{"message":"QUERY OK db=0.4ms\nrollback []","time":"2024-09-11T13:04:11.831Z","domain":["elixir"],"application":"ecto_sql","otel_trace_flags":[48,49],"severity":"DEBUG","logging.googleapis.com/sourceLocation":{"file":"lib/ecto/adapters/sql.ex","line":1276,"function":"Elixir.Ecto.Adapters.SQL.log/4"},"logging.googleapis.com/operation":{"producer":"#PID<0.848.0>"},"logging.googleapis.com/spanId":"3c5218a4b59fc13d","logging.googleapis.com/trace":"c9c853e27691f833657313a83bd95d79"}
{"error_logger":{"tag":"error","report_cb":"&:gen_server.format_log/1"},"message":"no function clause matching in :lists.partition_1/4","time":"2024-09-11T13:04:11.838Z","domain":["otp"],"context":{"reportLocation":{"filePath":"gen_server.erl","functionName":"gen_server.error_info/8","lineNumber":2474}},"otel_trace_flags":[48,49],"severity":"ERROR","logging.googleapis.com/sourceLocation":{"file":"gen_server.erl","line":2474,"function":"gen_server.error_info/8"},"logging.googleapis.com/operation":{"producer":"#PID<0.848.0>"},"logging.googleapis.com/spanId":"2c0b9c1e4afdd12c","logging.googleapis.com/trace":"c9c853e27691f833657313a83bd95d79","@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","serviceContext":{"service":"firezone@10.244.0.147"},"stack_trace":"** (FunctionClauseError) no function clause matching in :lists.partition_1/4\n    (stdlib 6.0.1) lists.erl:2231:in `:lists.partition_1(#Function<0.14248608/1 in :smtp_socket.proplist_merge/2>, nil, [active: false, keepalive: true, packet: :line], [])'\n    (gen_smtp 1.2.0) /app/deps/gen_smtp/src/smtp_socket.erl:339:in `:smtp_socket.proplist_merge/2'\n    (gen_smtp 1.2.0) /app/deps/gen_smtp/src/smtp_socket.erl:329:in `:smtp_socket.tcp_connect_options/2'\n    (gen_smtp 1.2.0) /app/deps/gen_smtp/src/smtp_socket.erl:107:in `:smtp_socket.connect/5'\n    (gen_smtp 1.2.0) /app/deps/gen_smtp/src/gen_smtp_client.erl:820:in `:gen_smtp_client.connect/2'\n    (gen_smtp 1.2.0) /app/deps/gen_smtp/src/gen_smtp_client.erl:378:in `:gen_smtp_client.open_smtp_session/2'\n    (gen_smtp 1.2.0) /app/deps/gen_smtp/src/gen_smtp_client.erl:316:in `:gen_smtp_client.try_smtp_sessions/3'\n    (gen_smtp 1.2.0) /app/deps/gen_smtp/src/gen_smtp_client.erl:289:in `:gen_smtp_client.send_it/2'\n"}
{"message":"MOUNT Web.SignUp\n  Parameters: %{}\n  Session: %{\"_csrf_token\" => \"ub8Cvd7abTCgRGm6tWmt5kky\"}","time":"2024-09-11T13:04:12.887Z","domain":["elixir"],"application":"phoenix_live_view","severity":"DEBUG","logging.googleapis.com/sourceLocation":{"file":"lib/phoenix_live_view/logger.ex","line":75,"function":"Elixir.Phoenix.LiveView.Logger.lv_mount_start/4"},"logging.googleapis.com/operation":{"producer":"#PID<0.853.0>"}}
{"message":"Replied in 558µs","time":"2024-09-11T13:04:12.888Z","domain":["elixir"],"application":"phoenix_live_view","otel_trace_flags":[48,49],"severity":"DEBUG","logging.googleapis.com/sourceLocation":{"file":"lib/phoenix_live_view/logger.ex","line":99,"function":"Elixir.Phoenix.LiveView.Logger.lv_mount_stop/4"},"logging.googleapis.com/operation":{"producer":"#PID<0.853.0>"},"logging.googleapis.com/spanId":"a08108937fd76929","logging.googleapis.com/trace":"c716654b3c926707c844aca0cf9d8f08"}
```

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_ Admin portal
- _Firezone Version (e.g. 1.0.0 or N/A):_ 235c2f3b161348c0bbf6fa21747e11c17f5ca7f5
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_ NA
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_ Docker (k8s)

**Comment by baznikin** [comment]
[Here](https://github.com/Intuinewin/helm-charts/issues/40#issuecomment-2323504195) @Intuinewin recommends to set `sockopts` to `{}` since default values are broken in firezone. I tried `{}`, `[]`, `''`. I found default values here https://github.com/gen-smtp/gen_smtp but still no luck. Errors on strart like:

```
ERROR! Config provider Config.Reader failed with:
** (Protocol.UndefinedError) protocol Enumerable not implemented for "{}" of type BitString. This protocol is implemented for the following type(s): DBConnection.PrepareStream, DBConnection.Stream, Date.Range, Ecto.Adapters.SQL.Stream, File.Stream, Floki.HTMLTree, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, Jason.OrderedObject, List, Map, MapSet, Phoenix.LiveView.LiveStream, Postgrex.Stream, Range, Stream
    (elixir 1.17.2) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir 1.17.2) lib/enum.ex:166: Enumerable.reduce/3
    (elixir 1.17.2) lib/enum.ex:4423: Enum.reverse/1
    (elixir 1.17.2) lib/keyword.ex:209: Keyword.new/2
    (elixir 1.17.2) lib/keyword.ex:1182: Keyword.update_guarded/4
    (elixir 1.17.2) lib/keyword.ex:1186: Keyword.update_guarded/4
    (domain 0.1.0+deadbeef) lib/domain/config/fetcher.ex:21: Domain.Config.Fetcher.fetch_source_and_config/4
    /app/releases/0.1.0+deadbeef/runtime.exs:229: (file)

Runtime terminating during boot ({#{value=><<"{}">>,protocol=>'Elixir.Enumerable',description=><<>>,'__struct__'=>'Elixir.Protocol.UndefinedError','__exception__'=>true},[{'Elixir.Enumerable','impl_for!',1,[{file,"lib/enum.ex"},{line,1}]},{'Elixir.Enumerable',reduce,3,[{file,"lib/enum.ex"},{line,166}]},{'Elixir.Enum',reverse,1,[{file,"lib/enum.ex"},{line,4423}]},{'Elixir.Keyword',new,2,[{file,"lib/keyword.ex"},{line,209}]},{'Elixir.Keyword',update_guarded,4,[{file,"lib/keyword.ex"},{line,1182}]},{'Elixir.Keyword',update_guarded,4,[{file,"lib/keyword.ex"},{line,1186}]},{'Elixir.Domain.Config.Fetcher',fetch_source_and_config,4,[{file,"lib/domain/config/fetcher.ex"},{line,21}]},{elixir_eval,'__FILE__',1,[{file,"/app/releases/0.1.0+deadbeef/runtime.exs"},{line,229}]}]})

Crash dump is being written to: erl_crash.dump...
```

**Comment by Intuinewin** [comment]
Hey, thanks for the ping, I just sent a PR with a fix for the default value of sockopts
