### ISSUE TITLE
Allow nil DNS server list

### ISSUE THREAD

**Issue by gbe0** [CloudFire-LLC/cloudfire#670]
As per the configuration file, it should be possible to **not** set a list of DNS servers:

```
# # Default DNS servers to use for generated device configs.
# # Defaults to CloudFlare's public DNS. Set to nil to omit DNS from generated
# # device configurations.
default['firezone']['wireguard']['dns'] = nil
```

If set to `nil` it will lead to a Phoenix crash:

```
2022-06-01_13:55:34.64890 ERROR! Config provider Config.Reader failed with:
2022-06-01_13:55:34.65449 ** (ArgumentError) could not fetch environment variable "WIREGUARD_DNS" because it is not set
2022-06-01_13:55:34.65450     (elixir 1.13.4) lib/system.ex:698: System.fetch_env!/1
2022-06-01_13:55:34.65450     (stdlib 3.17.2) erl_eval.erl:685: :erl_eval.do_apply/6
2022-06-01_13:55:34.65450     (stdlib 3.17.2) erl_eval.erl:446: :erl_eval.expr/5
2022-06-01_13:55:34.65450     (stdlib 3.17.2) erl_eval.erl:123: :erl_eval.exprs/5
2022-06-01_13:55:34.65450     (elixir 1.13.4) src/elixir.erl:296: :elixir.recur_eval/3
2022-06-01_13:55:34.65451     (elixir 1.13.4) src/elixir.erl:274: :elixir.eval_forms/3
2022-06-01_13:55:34.65451     (elixir 1.13.4) lib/code.ex:404: Code.validated_eval_string/3
2022-06-01_13:55:34.65451     (elixir 1.13.4) lib/config.ex:260: Config.__eval__!/3
2022-06-01_13:55:34.65451
2022-06-01_13:55:34.65461 {"init terminating in do_boot",{#{'__exception__'=>true,'__struct__'=>'Elixir.ArgumentError',message=><<"could not fetch environment variable \"WIREGUARD_DNS\" because it is not set">>},[{'Elixir.System','fetch_env!',1,[{file,"lib/system.ex"},{line,698}]},{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,685}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,446}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,123}]},{elixir,recur_eval,3,[{file,"src/elixir.erl"},{line,296}]},{elixir,eval_forms,3,[{file,"src/elixir.erl"},{line,274}]},{'Elixir.Code',validated_eval_string,3,[{file,"lib/code.ex"},{line,404}]},{'Elixir.Config','__eval__!',3,[{file,"lib/config.ex"},{line,260}]}]}}
2022-06-01_13:55:34.65834 init terminating in do_boot ({,[{Elixir.System,fetch_env!,1,[{_},{_}]},{erl_eval,do_apply,6,[{_},{_}]},{erl_eval,expr,5,[{_},{_}]},{erl_eval,exprs,5,[{_},{_}]},{elixir,recur_eval,3,[{_},{_}]},{elixir,eval_forms,3,[{_},{_}]},{Elixir.Code,validated_eval_string,3,[{_},{_}]},{Elixir.Config,__eval__!,3,[{_},{_}]}]})
2022-06-01_13:55:34.66005
2022-06-01_13:55:34.66006 Crash dump is being written to: erl_crash.dump...done
```

In `runtime.exs`, `WIREGUARD_DNS` is required: https://github.com/firezone/firezone/blob/795416f9f287ad45e43dda4c53f1849f820b7d18/config/runtime.exs#L45

This would need to be changed to make the config optional. However there is more to fix as without that value set the config will be returned as:

```
DNS = error
```

Discourse reference: https://discourse.firez.one/t/omit-dns-from-generated-device-configurations/82

**Comment by jamilbk** [comment]
Thanks for all the detail! I believe we have [logic](https://github.com/firezone/firezone/blob/master/apps/fz_http/lib/fz_http/devices.ex#L203) to handle nil DNS entries already -- the issue is we're using `System.fetch_env!` which raises if the env var isn't set instead of `System.get_env` which return a default of `nil`.

@conectado Want to take a stab at this one?

**Comment by conectado** [comment]
Yeah!
