### ISSUE TITLE
OIDC token length issue when using Keycloack

### ISSUE THREAD

**Issue by salemgolemugoo** [CloudFire-LLC/cloudfire#696]
Connected my firezone installation to Keycloack via OIDC integration. But when I get redirected to the firezone account page i receive "Internal Server Error".
Checked the logs and I see:
```2022-06-10_14:39:04.24107 Server: vpn.tglobal.market:80 (http)
2022-06-10_14:39:04.24107 Request: GET /auth/oidc/keycloack/callback/?state=dR895uVN7inMkGpR&session_state=59708b46-dd7a-46e4-82c7-900765b02b14&code=7cc7c346-fe96-4dbf-9df8-74ab4bbc3c8b.59708b46-dd7a-46e4-82c7-900765b02b14.b910d42a-c9cd-4462-8cc7-ae081ce28186
2022-06-10_14:39:04.24111 ** (exit) an exception was raised:
2022-06-10_14:39:04.24111     ** (Postgrex.Error) ERROR 22001 (string_data_right_truncation) value too long for type character varying(255)
2022-06-10_14:39:04.24111         (ecto_sql 3.8.2) lib/ecto/adapters/sql.ex:932: Ecto.Adapters.SQL.raise_sql_call_error/1
2022-06-10_14:39:04.24112         (ecto 3.8.3) lib/ecto/repo/schema.ex:744: Ecto.Repo.Schema.apply/4
2022-06-10_14:39:04.24112         (ecto 3.8.3) lib/ecto/repo/schema.ex:367: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
2022-06-10_14:39:04.24113         (fz_http 0.3.17) lib/fz_http_web/controllers/auth_controller.ex:72: FzHttpWeb.AuthController.callback/2
2022-06-10_14:39:04.24113         (fz_http 0.3.17) lib/fz_http_web/controllers/auth_controller.ex:1: FzHttpWeb.AuthController.action/2
2022-06-10_14:39:04.24113         (fz_http 0.3.17) lib/fz_http_web/controllers/auth_controller.ex:1: FzHttpWeb.AuthController.phoenix_controller_pipeline/2
2022-06-10_14:39:04.24115         (phoenix 1.6.9) lib/phoenix/router.ex:354: Phoenix.Router.__call__/2
2022-06-10_14:39:04.24115         (fz_http 0.3.17) lib/fz_http_web/endpoint.ex:1: FzHttpWeb.Endpoint.plug_builder_call/2
2022-06-10_14:39:23.03988 14:39:23.039 request_id=FvdJSFG6AWFSYdEAAAJi [info] GET /
2022-06-10_14:39:23.04427 14:39:23.044 request_id=FvdJSFG6AWFSYdEAAAJi [info] Sent 200 in 4ms
2022-06-10_14:40:54.01277 14:40:54.012 request_id=FvdJXYAjogf8-bcAAAJy [info] GET /
2022-06-10_14:40:54.01397 14:40:54.013 request_id=FvdJXYAjogf8-bcAAAJy [info] Sent 200 in 1ms
2022-06-10_14:41:36.66103 14:41:36.660 request_id=FvdJZ24idd5_uFAAAAKC [info] GET /auth/oidc/keycloack/callback/
2022-06-10_14:41:36.84491 14:41:36.844 request_id=FvdJZ24idd5_uFAAAAKC [info] Sent 500 in 184ms
2022-06-10_14:41:36.84575 14:41:36.845 [error] #PID<0.565.0> running FzHttpWeb.Endpoint (connection #PID<0.564.0>, stream id 1) terminated
```

**Comment by jamilbk** [comment]
Thanks for the report. @princemaple just fixed this -- 0.3.18 will contain the fix. Will cut a release shortly.
