### ISSUE TITLE
Cannot make or login account via Azure SSO

### ISSUE THREAD

**Issue by mlunax** [CloudFire-LLC/cloudfire#757]
Some account cannot login via Azure SSO
Logs from phoenix
```
2022-06-25_18:57:25.95849 18:57:25.957 [error] #PID<0.777.0> running FzHttpWeb.Endpoint (connection #PID<0.776.0>, stream id 1) terminated
2022-06-25_18:57:25.95850 Server: REDACTED_DOMAIN:80 (http)
2022-06-25_18:57:25.95851 Request: GET /auth/oidc/azure/callback/?code=REDACTED_THERE_WAS_CALLBACK_CODE
2022-06-25_18:57:25.95852 ** (exit) an exception was raised:
2022-06-25_18:57:25.95852     ** (FunctionClauseError) no function clause matching in FzHttpWeb.UserFromAuth.find_or_create/2
2022-06-25_18:57:25.95852         (fz_http 0.4.4) lib/fz_http_web/user_from_auth.ex:28: FzHttpWeb.UserFromAuth.find_or_create(:azure, %{"aud" => "REDACTED", "exp" => REDACTED, "iat" => REDACTED, "iss" => "https://login.microsoftonline.com/REDACTED/v2.0", "name" => "test Test", "nbf" => REDACTED, "oid" => "REDACTED", "preferred_username" => "user.test@REDACTED", "rh" => "REDACTED", "sub" => "REDACTED", "tid" => "REDACTED", "uti" => "REDACTED", "ver" => "2.0"})
2022-06-25_18:57:25.95853         (fz_http 0.4.4) lib/fz_http_web/controllers/auth_controller.ex:68: FzHttpWeb.AuthController.callback/2
2022-06-25_18:57:25.95853         (fz_http 0.4.4) lib/fz_http_web/controllers/auth_controller.ex:1: FzHttpWeb.AuthController.action/2
2022-06-25_18:57:25.95854         (fz_http 0.4.4) lib/fz_http_web/controllers/auth_controller.ex:1: FzHttpWeb.AuthController.phoenix_controller_pipeline/2
2022-06-25_18:57:25.95855         (phoenix 1.6.9) lib/phoenix/router.ex:354: Phoenix.Router.__call__/2
2022-06-25_18:57:25.95856         (fz_http 0.4.4) lib/fz_http_web/endpoint.ex:1: FzHttpWeb.Endpoint.plug_builder_call/2
2022-06-25_18:57:25.95856         (fz_http 0.4.4) lib/fz_http_web/endpoint.ex:1: FzHttpWeb.Endpoint.call/2
2022-06-25_18:57:25.95856         (phoenix 1.6.9) lib/phoenix/endpoint/cowboy2_handler.ex:54: Phoenix.Endpoint.Cowboy2Handler.init/4
2022-06-25_18:57:38.06124 18:57:38.060 request_id=FvvyFIyUfyu-o90AAAdx [info] GET /
2022-06-25_18:57:38.06493 18:57:38.064 request_id=FvvyFIyUfyu-o90AAAdx [info] Sent 500 in 3ms
```

**Comment by jamilbk** [comment]
Hi @mlunax -- looks like the `email` field is missing in the claims map for those users. Have you ensured that the email permission is allowed in your Azure API Graph permissions?

<img width="1411" alt="Screen Shot 2022-06-25 at 2 13 56 PM" src="https://user-images.githubusercontent.com/167144/175790701-be3793a9-3ff2-4cd8-970c-c38e19bad764.png">

Also, could you provide the OIDC scopes you've configured in your `/etc/firezone/firezone.rb`?

**Comment by mlunax** [comment]
The administrator of AD can log in into but other user cannot.

The scopes in firezone.rb:
```
    scope: "openid email profile offline_access",
```

**Comment by jamilbk** [comment]
@mlunax The error you're hitting [is here](https://github.com/firezone/firezone/blob/master/apps/fz_http/lib/fz_http_web/user_from_auth.ex#L28):

```elixir
  def find_or_create(_provider, %{"email" => email, "sub" => _sub}) do
    case Users.get_by_email(email) do
      nil -> maybe_create_user(email)
      user -> {:ok, user}
    end
  end
```

Judging from your logs, the `email` field is missing from the response from Azure. Did you follow our [Azure configuration guide](https://docs.firezone.dev/docs/authenticate/azure-ad/)? Do your settings match what's shown in that guide?

**Comment by jamilbk** [comment]
@mlunax Were you able to resolve this?

**Comment by mlunax** [comment]
I found my account had empty field "email" in AAD. Not every account has email license (outlook/exchange etc.)
As far I understand and know the app takes email from "email" field, but the better solution is taking from UPN field.

**Comment by jamilbk** [comment]
@mlunax Yeah, the issue is that field is specific to Azure AD. We could add an edge case for it -- but it looks like from your example above, `preferred_username` is the field that contains your user's email in your case.

Instead of trying to handle each edge case in Firezone -- would it possible for you to map the UPN or `preferred_username` field to `email` using this guide? https://docs.microsoft.com/en-us/azure/active-directory/app-provisioning/customize-application-attributes

**Comment by jamilbk** [comment]
@mlunax Just following up -- were you able to map this field or did we need to work on a solution for this Azure edge case?

**Comment by jamilbk** [comment]
Closing for now to keep our backlog groomed. Feel free to re-open if this is still an issue!
