### ISSUE TITLE
Install Script Failure - OpenSSL

### ISSUE THREAD

**Issue by kstorbakken** [CloudFire-LLC/cloudfire#847]
I'm trying to stand up a firezone test machine and the install script keeps failing on a certificate validation step. I'm using a self signed cert for now for testing, which my understanding is that it uses this configuration by default. Here's my set up output, I'm using all defaults
```
Starting Chef Infra Client, version 16.17.51
Patents: https://www.chef.io/patents
resolving cookbooks for run list: ["firezone::default"]
Synchronizing Cookbooks:
  - enterprise (1.2.0)
  - runit (5.1.7)
  - line (4.5.2)
  - firezone (0.0.1)
  - packagecloud (1.0.1)
  - yum-epel (4.5.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 55 resources
Recipe: firezone::config
  * linux_user[firezone] action create (up to date)
  * group[firezone] action create (up to date)
  * directory[/etc/firezone] action create (up to date)
  * directory[/var/opt/firezone] action create (up to date)
  * directory[/opt/firezone/embedded/service/firezone/tmp] action create (up to date)
  * directory[/var/log/firezone] action create (up to date)
  * directory[/var/opt/firezone/etc] action create (up to date)
  * file[configuration-variables] action create (up to date)
  * file[/etc/firezone/secrets.json] action create (up to date)
  * file[/var/opt/firezone/cache/wg_private_key] action create (up to date)
Recipe: firezone::log_management
  * directory[/var/opt/firezone/etc/logrotate.d] action create (up to date)
  * template[/var/opt/firezone/etc/logrotate.conf] action create (up to date)
  * template[/etc/cron.hourly/firezone_logrotate] action create (up to date)
Recipe: firezone::ssl
  * directory[/var/opt/firezone/ssl] action create (up to date)
  * directory[/var/opt/firezone/ssl/ca] action create (up to date)
  * openssl_dhparam[/var/opt/firezone/ssl/ca/dhparams.pem] action create
    * file[/var/opt/firezone/ssl/ca/dhparams.pem] action create (up to date)
     (up to date)
  * openssl_x509_certificate[/var/opt/firezone/ssl/ca/70.67.60.41.crt] action create
    * file[/var/opt/firezone/ssl/ca/70.67.60.41.crt] action create_if_missing (up to date)
    * file[/var/opt/firezone/ssl/ca/70.67.60.41.key] action create_if_missing (up to date)
     (up to date)
  * link[/var/opt/firezone/ssl/cacert.pem] action create (up to date)
Recipe: firezone::network
  * replace_or_add[IPv4 packet forwarding] action edit
    * file[/etc/sysctl.conf] action create (up to date)
     (up to date)
  * replace_or_add[IPv6 packet forwarding] action edit
    * file[/etc/sysctl.conf] action create (up to date)
     (up to date)
  * execute[sysctl -p /etc/sysctl.conf] action run
    [32m- execute sysctl -p /etc/sysctl.conf[0m
Recipe: enterprise::runit
  * component_runit_supervisor[firezone] action create
    * template[/etc/systemd/system/firezone-runsvdir-start.service] action create (up to date)
    * execute[systemctl daemon-reload] action nothing (skipped due to action :nothing)
    * file[/usr/lib/systemd/system/firezone-runsvdir-start.service] action delete (up to date)
    * service[firezone-runsvdir-start.service] action enable (up to date)
    * service[firezone-runsvdir-start.service] action start (up to date)
     (up to date)
Recipe: firezone::postgresql
  * sysctl[kernel.shmmax] action apply (up to date)
  * sysctl[kernel.shmall] action apply (up to date)
  * directory[/var/log/firezone/postgresql] action create (up to date)
  * enterprise_pg_cluster[firezone] action init
    * directory[/var/opt/firezone/postgresql/13.3/data] action create (up to date)
    * execute[initialize_cluster_/var/opt/firezone/postgresql/13.3/data] action run (skipped due to not_if)
    * template[/var/opt/firezone/postgresql/13.3/data/postgresql.conf] action create (up to date)
    * template[/var/opt/firezone/postgresql/13.3/data/pg_hba.conf] action create (up to date)
     (up to date)
  * component_runit_service[postgresql] action enable
    * template[/var/log/firezone/postgresql/config] action create (up to date)
  Recipe: <Dynamically Defined Resource>
    * service[postgresql] action nothing (skipped due to action :nothing)
    * runit_service[postgresql] action enable
      * ruby_block[restart_service] action nothing (skipped due to action :nothing)
      * ruby_block[restart_log_service] action nothing (skipped due to action :nothing)
      * directory[/opt/firezone/sv/postgresql] action create (up to date)
      * template[/opt/firezone/sv/postgresql/run] action create (up to date)
      * directory[/opt/firezone/sv/postgresql/log] action create (up to date)
      * directory[/opt/firezone/sv/postgresql/log/main] action create (up to date)
      * directory[/var/log/postgresql] action create (up to date)
      * template[/opt/firezone/sv/postgresql/log/config] action create (up to date)
      * link[/var/log/postgresql/config] action create (up to date)
      * template[/opt/firezone/sv/postgresql/log/run] action create (up to date)
      * directory[/opt/firezone/sv/postgresql/env] action create (up to date)
      * ruby_block[Delete unmanaged env files for postgresql service] action run (skipped due to only_if)
      * template[/opt/firezone/sv/postgresql/check] action create (skipped due to only_if)
      * template[/opt/firezone/sv/postgresql/finish] action create (skipped due to only_if)
      * directory[/opt/firezone/sv/postgresql/control] action create (up to date)
      * template[/opt/firezone/sv/postgresql/control/t] action create (up to date)
      * link[/opt/firezone/init/postgresql] action create (up to date)
      * file[/opt/firezone/sv/postgresql/down] action nothing (skipped due to action :nothing)
      * directory[/opt/firezone/service] action create (up to date)
      * link[/opt/firezone/service/postgresql] action create (up to date)
      * ruby_block[wait for postgresql service socket] action run
        [32m- execute the ruby block wait for postgresql service socket[0m
    
  
Recipe: firezone::nginx
  * directory[/var/opt/firezone/nginx/cache] action create (up to date)
  * directory[/var/log/firezone/nginx] action create (up to date)
  * directory[/var/opt/firezone/nginx/etc] action create (up to date)
  * directory[/var/opt/firezone/nginx/etc/conf.d] action create (up to date)
  * directory[/var/opt/firezone/nginx/etc/sites-enabled] action create (up to date)
  * link[/var/opt/firezone/nginx/etc/mime.types] action create (up to date)
  * template[nginx.conf] action create (up to date)
  * component_runit_service[nginx] action enable
    * template[/var/log/firezone/nginx/config] action create (up to date)
  Recipe: <Dynamically Defined Resource>
    * service[nginx] action nothing (skipped due to action :nothing)
    * runit_service[nginx] action enable
      * ruby_block[restart_service] action nothing (skipped due to action :nothing)
      * ruby_block[restart_log_service] action nothing (skipped due to action :nothing)
      * directory[/opt/firezone/sv/nginx] action create (up to date)
      * template[/opt/firezone/sv/nginx/run] action create (up to date)
      * directory[/opt/firezone/sv/nginx/log] action create (up to date)
      * directory[/opt/firezone/sv/nginx/log/main] action create (up to date)
      * directory[/var/log/nginx] action create (up to date)
      * template[/opt/firezone/sv/nginx/log/config] action create (up to date)
      * link[/var/log/nginx/config] action create (up to date)
      * template[/opt/firezone/sv/nginx/log/run] action create (up to date)
      * directory[/opt/firezone/sv/nginx/env] action create (up to date)
      * ruby_block[Delete unmanaged env files for nginx service] action run (skipped due to only_if)
      * template[/opt/firezone/sv/nginx/check] action create (skipped due to only_if)
      * template[/opt/firezone/sv/nginx/finish] action create (skipped due to only_if)
      * directory[/opt/firezone/sv/nginx/control] action create (up to date)
      * link[/opt/firezone/init/nginx] action create (up to date)
      * file[/opt/firezone/sv/nginx/down] action nothing (skipped due to action :nothing)
      * directory[/opt/firezone/service] action create (up to date)
      * link[/opt/firezone/service/nginx] action create (up to date)
      * ruby_block[wait for nginx service socket] action run
        [32m- execute the ruby block wait for nginx service socket[0m
    
  
Recipe: firezone::nginx
  * template[/var/opt/firezone/etc/logrotate.d/nginx] action create (up to date)
Recipe: firezone::database
  * enterprise_pg_user[firezone] action create (skipped due to not_if)
  * enterprise_pg_database[firezone] action create
    * execute[create_database_firezone] action run (skipped due to not_if)
     (up to date)
  * execute[create postgresql plpgsql extension] action run (skipped due to not_if)
  * execute[create postgresql pg_trgm extension] action run (skipped due to not_if)
Recipe: firezone::setcap
  * file[/opt/firezone/embedded/sbin/nft] action touch
    [32m- update utime on file /opt/firezone/embedded/sbin/nft[0m
  * execute[setcap_nft] action run
    [32m- execute setcap 'cap_net_admin,cap_net_raw+eip' /opt/firezone/embedded/sbin/nft[0m
Recipe: firezone::wireguard
  * directory[/var/log/firezone/wireguard] action create (up to date)
  * component_runit_service[wireguard] action enable
    * template[/var/log/firezone/wireguard/config] action create (up to date)
  Recipe: <Dynamically Defined Resource>
    * service[wireguard] action nothing (skipped due to action :nothing)
    * runit_service[wireguard] action enable
      * ruby_block[restart_service] action nothing (skipped due to action :nothing)
      * ruby_block[restart_log_service] action nothing (skipped due to action :nothing)
      * directory[/opt/firezone/sv/wireguard] action create (up to date)
      * template[/opt/firezone/sv/wireguard/run] action create (up to date)
      * directory[/opt/firezone/sv/wireguard/log] action create (up to date)
      * directory[/opt/firezone/sv/wireguard/log/main] action create (up to date)
      * directory[/var/log/wireguard] action create (up to date)
      * template[/opt/firezone/sv/wireguard/log/config] action create (up to date)
      * link[/var/log/wireguard/config] action create (up to date)
      * template[/opt/firezone/sv/wireguard/log/run] action create (up to date)
      * directory[/opt/firezone/sv/wireguard/env] action create (up to date)
      * ruby_block[Delete unmanaged env files for wireguard service] action run (skipped due to only_if)
      * template[/opt/firezone/sv/wireguard/check] action create (skipped due to only_if)
      * template[/opt/firezone/sv/wireguard/finish] action create (skipped due to only_if)
      * directory[/opt/firezone/sv/wireguard/control] action create (up to date)
      * link[/opt/firezone/init/wireguard] action create (up to date)
      * file[/opt/firezone/sv/wireguard/down] action nothing (skipped due to action :nothing)
      * directory[/opt/firezone/service] action create (up to date)
      * link[/opt/firezone/service/wireguard] action create (up to date)
      * ruby_block[wait for wireguard service socket] action run
        [32m- execute the ruby block wait for wireguard service socket[0m
    
  
Recipe: firezone::phoenix
  * directory[/var/log/firezone/phoenix] action create (up to date)
  * directory[/var/opt/firezone/phoenix/run] action create (up to date)
  * template[phoenix.nginx.conf] action create (up to date)
  * component_runit_service[phoenix] action enable
    * template[/var/log/firezone/phoenix/config] action create (up to date)
  Recipe: <Dynamically Defined Resource>
    * service[phoenix] action nothing (skipped due to action :nothing)
    * runit_service[phoenix] action enable
      * ruby_block[restart_service] action nothing (skipped due to action :nothing)
      * ruby_block[restart_log_service] action nothing (skipped due to action :nothing)
      * directory[/opt/firezone/sv/phoenix] action create (up to date)
      * template[/opt/firezone/sv/phoenix/run] action create (up to date)
      * directory[/opt/firezone/sv/phoenix/log] action create (up to date)
      * directory[/opt/firezone/sv/phoenix/log/main] action create (up to date)
      * directory[/var/log/phoenix] action create (up to date)
      * template[/opt/firezone/sv/phoenix/log/config] action create (up to date)
      * link[/var/log/phoenix/config] action create (up to date)
      * template[/opt/firezone/sv/phoenix/log/run] action create (up to date)
      * directory[/opt/firezone/sv/phoenix/env] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/EGRESS_INTERFACE] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/NFT_PATH] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/MIX_ENV] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/DATABASE_NAME] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/DATABASE_USER] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/DATABASE_HOST] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/DATABASE_PORT] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/DATABASE_POOL] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/DATABASE_SSL] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/DATABASE_SSL_OPTS] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/DATABASE_PARAMETERS] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/PHOENIX_LISTEN_ADDRESS] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/PHOENIX_PORT] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/EXTERNAL_URL] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/ADMIN_EMAIL] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/WIREGUARD_INTERFACE_NAME] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/WIREGUARD_PORT] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/WIREGUARD_MTU] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/WIREGUARD_ENDPOINT] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/WIREGUARD_DNS] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/WIREGUARD_ALLOWED_IPS] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/WIREGUARD_PERSISTENT_KEEPALIVE] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/WIREGUARD_IPV4_ENABLED] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/WIREGUARD_IPV4_MASQUERADE] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/WIREGUARD_IPV4_NETWORK] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/WIREGUARD_IPV4_ADDRESS] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/WIREGUARD_IPV6_MASQUERADE] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/WIREGUARD_IPV6_ENABLED] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/WIREGUARD_IPV6_NETWORK] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/WIREGUARD_IPV6_ADDRESS] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/MAX_DEVICES_PER_USER] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/ALLOW_UNPRIVILEGED_DEVICE_MANAGEMENT] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/TELEMETRY_ENABLED] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/TELEMETRY_ID] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/CONNECTIVITY_CHECKS_ENABLED] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/CONNECTIVITY_CHECKS_INTERVAL] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/OUTBOUND_EMAIL_PROVIDER] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/OUTBOUND_EMAIL_CONFIGS] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/OUTBOUND_EMAIL_FROM] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/WIREGUARD_PRIVATE_KEY_PATH] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/LOCAL_AUTH_ENABLED] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/OKTA_AUTH_ENABLED] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/OKTA_CLIENT_ID] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/OKTA_CLIENT_SECRET] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/OKTA_SITE] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/GOOGLE_AUTH_ENABLED] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/GOOGLE_CLIENT_ID] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/GOOGLE_CLIENT_SECRET] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/GOOGLE_REDIRECT_URI] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/DISABLE_VPN_ON_OIDC_ERROR] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/AUTO_CREATE_OIDC_USERS] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/AUTH_OIDC] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/GUARDIAN_SECRET_KEY] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/SECRET_KEY_BASE] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/LIVE_VIEW_SIGNING_SALT] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/COOKIE_SIGNING_SALT] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/COOKIE_ENCRYPTION_SALT] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/DATABASE_ENCRYPTION_KEY] action create (up to date)
      * file[/opt/firezone/sv/phoenix/env/DEFAULT_ADMIN_PASSWORD] action create (up to date)
      * ruby_block[Delete unmanaged env files for phoenix service] action run (skipped due to only_if)
      * template[/opt/firezone/sv/phoenix/check] action create (skipped due to only_if)
      * template[/opt/firezone/sv/phoenix/finish] action create (up to date)
      * directory[/opt/firezone/sv/phoenix/control] action create (up to date)
      * template[/opt/firezone/sv/phoenix/control/t] action create (up to date)
      * link[/opt/firezone/init/phoenix] action create (up to date)
      * file[/opt/firezone/sv/phoenix/down] action nothing (skipped due to action :nothing)
      * directory[/opt/firezone/service] action create (up to date)
      * link[/opt/firezone/service/phoenix] action create (up to date)
      * ruby_block[wait for phoenix service socket] action run
        [32m- execute the ruby block wait for phoenix service socket[0m
    
  
Recipe: firezone::app
  * execute[fix app permissions] action run
    [32m- execute chown -R firezone:firezone /opt/firezone/embedded/service/firezone && chmod -R o-rwx /opt/firezone/embedded/service/firezone && chmod -R g-rwx /opt/firezone/embedded/service/firezone[0m
  * execute[setcap_beam] action run
    [32m- execute setcap 'cap_net_admin+eip' /opt/firezone/embedded/service/firezone/erts-13.0.1/bin/beam.smp[0m
  * file[environment-variables] action create (up to date)
  * execute[database schema] action run
    [32m- execute bin/firezone eval "FzHttp.Release.migrate"[0m
Recipe: firezone::telemetry
  * file[disable_telemetry] action delete (up to date)
Recipe: firezone::default
  * file[/etc/firezone/firezone-running.json] action create (up to date)
  * file[/var/opt/firezone/.license.accepted] action create (up to date)
Recipe: firezone::phoenix
  * component_runit_service[phoenix] action restart
  Recipe: <Dynamically Defined Resource>
    * service[phoenix] action nothing (skipped due to action :nothing)
    * runit_service[phoenix] action restart (up to date)
     (up to date)

Running handlers:
Running handlers complete
Chef Infra Client finished, 18/226 resources updated in 04 seconds
[2022-07-25T16:04:22-07:00] WARN: This release of Chef Infra Client became end of life (EOL) on May 1st 2022. Please update to a supported release to receive new features, bug fixes, and security updates.

Traceback (most recent call last):
        13: from /opt/firezone/embedded/bin/omnibus-ctl:23:in `<main>'
        12: from /opt/firezone/embedded/bin/omnibus-ctl:23:in `load'
        11: from /opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/omnibus-ctl-0.6.0/bin/omnibus-ctl:31:in `<top (required)>'
        10: from /opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/omnibus-ctl-0.6.0/lib/omnibus-ctl.rb:747:in `run'
         9: from /opt/firezone/embedded/lib/ruby/gems/2.7.0/gems/omnibus-ctl-0.6.0/lib/omnibus-ctl.rb:204:in `block in add_command_under_category'
         8: from /opt/firezone/embedded/service/omnibus-ctl/create_admin.rb:44:in `block in load_file'
         7: from /opt/firezone/embedded/service/omnibus-ctl/reconfigure.rb:27:in `capture'
         6: from /opt/firezone/embedded/lib/ruby/2.7.0/net/http.rb:500:in `post'
         5: from /opt/firezone/embedded/lib/ruby/2.7.0/net/http.rb:606:in `start'
         4: from /opt/firezone/embedded/lib/ruby/2.7.0/net/http.rb:932:in `start'
         3: from /opt/firezone/embedded/lib/ruby/2.7.0/net/http.rb:943:in `do_start'
         2: from /opt/firezone/embedded/lib/ruby/2.7.0/net/http.rb:1009:in `connect'
         1: from /opt/firezone/embedded/lib/ruby/2.7.0/net/protocol.rb:44:in `ssl_socket_connect'
/opt/firezone/embedded/lib/ruby/2.7.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate) (OpenSSL::SSL::SSLError)

```
Everything looks to be up and running after this, but I never get my login creds displayed. I've tried manually running `firezone-ctl create-or-reset-admin` but I receive the same traceback errors about the SSL error. The errors about it being self signed are expected, does the OpenSSL config just need to be tweaked to bypass this? 
Edit: Apologies, forgot to include OS. I'm running Rocky Linux 8.5.0. Kernel-ml is installed and wireguard kernel modules are active.

**Comment by jamilbk** [comment]
@kstorbakken Hmm. I think the error is unrelated to firezone itself and may be an issue with our external ip ping service. Let me take a quick look.

**Comment by jamilbk** [comment]
@kstorbakken Do you have any outbound HTTP(s) proxies that would be intercepting requests made by this instance? That would cause a cert failure as we have a couple diagnostic pings that get sent out periodically to determine the instance's public IP for connectivity purposes. You can disable these with:

```
default['firezone']['telemetry']['enabled'] = false
default['firezone']['connectivity_checks']['enabled'] = false
```

in your /etc/firezone/firezone.rb.

That should help for now :-).

**Comment by kstorbakken** [comment]
I do not have any outbound HTTP(s) proxies, but this machine doesn't have connectivity from WAN so I can see why it'd be failing those checks. I mostly just wanted to play around with it on an isolated network. I made the changes you suggested and it indeed works with no issues now.  I'll close this issue since I have my workaround and it looks like you're working on things to prevent this in the future. Much appreciated!
