### ISSUE TITLE
RPC failed with reason :nodedown

### ISSUE THREAD

**Issue by jobcespedes** [CloudFire-LLC/cloudfire#894]
Running `firezone-ctl create-or-reset-admin` gives error:
```
RPC failed with reason :nodedown
```
Info:
This happens in AWS, Amazon Linux 2 (kernel 5.15 ) and Centos Stream 9 (Kernel 5.14 ), Arm64 arquitecture.
Logs:
```
==> /var/log/firezone/phoenix/current <==
2022-08-06_15:22:18.00441 15:22:18.004 request_id=FwjKtDQoNgnoOCcAAABS [info] GET /
2022-08-06_15:22:18.00540 15:22:18.005 request_id=FwjKtDQoNgnoOCcAAABS remote_ip=136.144.42.13 [info] Sent 200 in 1ms
2022-08-06_15:22:30.63229 15:22:30.631 request_id=FwjKtyTW3OyCwZcAAABi [info] GET /
2022-08-06_15:22:30.63332 15:22:30.633 request_id=FwjKtyTW3OyCwZcAAABi remote_ip=136.144.42.13 [info] Sent 200 in 1ms
2022-08-06_15:22:30.65632 15:22:30.656 request_id=FwjKtyZGCGtQis8AAABy [info] GET /
2022-08-06_15:22:30.65727 15:22:30.657 request_id=FwjKtyZGCGtQis8AAABy remote_ip=136.144.42.13 [info] Sent 200 in 1ms
2022-08-06_15:22:59.31250 15:22:59.312 request_id=FwjKvdJQQRC9POEAAACC [info] GET /
2022-08-06_15:22:59.31359 15:22:59.313 request_id=FwjKvdJQQRC9POEAAACC remote_ip=136.144.42.13 [info] Sent 200 in 1ms
2022-08-06_15:22:59.34825 15:22:59.348 request_id=FwjKvdR0EULuRWUAAAIR [info] GET /
2022-08-06_15:22:59.34969 15:22:59.349 request_id=FwjKvdR0EULuRWUAAAIR remote_ip=136.144.42.13 [info] Sent 200 in 1ms
```
Status:
```
run: nginx: (pid 17084) 242s; run: log: (pid 17083) 242s
run: phoenix: (pid 17087) 242s; run: log: (pid 17086) 242s
run: postgresql: (pid 17082) 242s; run: log: (pid 17080) 242s
run: wireguard: (pid 17085) 242s; run: log: (pid 17081) 242s
```

**Comment by jamilbk** [comment]
@jobcespedes Thanks for the report! This usually happens when the phoenix service is flapping, but it looks like yours is running fine. Could you show (or check) the full output of `/var/log/firezone/phoenix/current`? You should see Erlang BEAM crashes which were causing the `:nodedown` error.

If you try `create-or-reset-admin` now, does it work?

**Comment by jamilbk** [comment]
Also, can I ask how you're installing Firezone? Using the automatic install script or installing from our package repository?

**Comment by jobcespedes** [comment]
> Could you show (or check) the full output of /var/log/firezone/phoenix/current? 

```
2022-08-06_16:10:02.25593 16:10:01.327 [notice] Application fz_http exited: FzHttp.Application.start(:normal, []) returned an error: shutdown: failed to start child: FzHttp.Conf.Cache
2022-08-06_16:10:02.25601     ** (EXIT) an exception was raised:
2022-08-06_16:10:02.25601         ** (Postgrex.Error) ERROR 42P01 (undefined_table) relation "configurations" does not exist
2022-08-06_16:10:02.25601  
2022-08-06_16:10:02.25601     query: SELECT c0."id", c0."logo", c0."local_auth_enabled", c0."allow_unprivileged_device_management", c0."openid_connect_providers", c0."disable_vpn_on_oidc_error", c0."auto_create_oidc_users", c0."inserted_at", c0."updated_at" FROM "configurations" AS c0
2022-08-06_16:10:02.25601             (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:932: Ecto.Adapters.SQL.raise_sql_call_error/1
2022-08-06_16:10:02.25602             (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:847: Ecto.Adapters.SQL.execute/6
2022-08-06_16:10:02.25602             (ecto 3.8.4) lib/ecto/repo/queryable.ex:221: Ecto.Repo.Queryable.execute/4
2022-08-06_16:10:02.25602             (ecto 3.8.4) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
2022-08-06_16:10:02.25602             (ecto 3.8.4) lib/ecto/repo/queryable.ex:155: Ecto.Repo.Queryable.one!/3
2022-08-06_16:10:02.25602             (fz_http 0.5.2) lib/fz_http/conf/cache.ex:27: FzHttp.Conf.Cache.init/1
2022-08-06_16:10:02.25603             (stdlib 4.0.1) gen_server.erl:848: :gen_server.init_it/2
2022-08-06_16:10:02.25603             (stdlib 4.0.1) gen_server.erl:811: :gen_server.init_it/6
```

> Also, can I ask how you're installing Firezone? Using the automatic install script or installing from our package repository?

In AWS, t4g.nano instance, cloudinit script:
```
curl -1sLf "https://dl.cloudsmith.io/public/firezone/firezone/setup.rpm.sh" | bash
dnf install -y firezone
```

**Comment by jamilbk** [comment]
@jobcespedes -- Does `firezone-ctl reconfigure` complete successfully for you? The error you're getting means the DB is not fully migrated. The DB migrations occur during `reconfigure`.

**Comment by jobcespedes** [comment]
I changed aws instance from t4g.nano to t4g.micro and there were no errors. I don't know why.

> Does firezone-ctl reconfigure complete successfully for you?

I think so

**Comment by jamilbk** [comment]
Hmm. Resource limits shouldn't be an issue in day to day Firezone operation, but perhaps the postgres process is getting killed during migrations and the `reconfigure` isn't noticing? Possibly related: https://discourse.firez.one/t/cannt-install-firezone-on-new-server-try-ubuntu-and-debian/138/2

Does this instance have swap enabled? Any `process killed` errors in your kernel log?

**Comment by jobcespedes** [comment]
No swap and yes there is an error in kernel log:
`[  565.586846] Out of memory: Killed process 5241 (beam.smp) total-vm:2354500kB, anon-rss:74224kB, file-rss:0kB, shmem-rss:27844kB, UID:1001 pgtables:472kB oom_score_adj:0`

**Comment by jamilbk** [comment]
Looks like order has been restored to the universe :-). I'll add a note to update our docs with these findings.

**Comment by jamilbk** [comment]
https://docs.firezone.dev/deploy/prerequisites#resource-requirements
